validation-test/README.md
validation-test/requirements.txt
validation-test/setup.py
validation-test/storagetest/core/common_fixtures.py
validation-test/storagetest/core/test_longhorn_vm.py
validation-test/storagetest/core/test_longhorn_vm_as_service.py
validation-test/storagetest/core/test_longhorn_vmsnapshot.py
validation-test/test
validation-test/tox.ini

@yasker , can you review the test cases?

Basic test cases for VM deployment using volumes in longhorn driver

---

validation-test/setup.py
validation-test/storagetest/core/common_fixtures.py
validation-test/storagetest/core/test_longhorn_vm.py
validation-test/storagetest/core/test_longhorn_vm_as_service.py
validation-test/storagetest/core/test_longhorn_vmsnapshot.py

@sangeethah @yasker 
fix test common setup for default longhorn catalog and env VM enable operations

fix test common setup for longhorn catalog and env VM enable

---

validation-test/storagetest/core/common_fixtures.py

Configure Backup Targets 

---

validation-test/storagetest/core/common_fixtures.py
validation-test/storagetest/core/test_longhorn_vm_as_service.py

@yasker , can you review the fixes done for cleaning up volumes ?

Fixed cleanup code to attempt deletion of root/data volumes in longhorn only when they exist

---

validation-test/storagetest/core/common_fixtures.py

@yasker @jimengliu can you review the changes made to wait for Storage pool and Virtual Machine stack for maximum of 30 secs to prevent execution of test cases too quickly resulting in failure.

Added code to wait for Storage pool and Virtual Machine stack to be available

---

.gitignore
Dockerfile.dapper
validation-test/README.md
validation-test/storagetest/core/common_fixtures.py
validation-test/storagetest/core/test_longhorn_basic.py

a fix for longhorn validation tests

fix test_container_replica_down

---

manager/integration/tests/test_basic.py

longhorn manager: 0cad90d418192ac9aeb6079b6b96df7f20f1f908

manager: Update setting test

---

manager/integration/tests/conftest.py

manager: Fix recurring job test was always ran

---

manager/integration/deploy/test.yaml
manager/integration/tests/common.py
manager/integration/tests/requirements.txt
manager/integration/tests/test_csi.py

Relate to: https://github.com/rancher/longhorn-manager/pull/68
How to run:
1. Deploy longhorn and [longhorn-csi](https://github.com/niusmallnan/longhorn-csi/tree/master/deploy/csi)
2. Run CSI cases: `py.test -v test_csi.py`
Results:
```
test_csi.py::test_volume_mount PASSED
test_csi.py::test_volume_io PASSED
```

Add CSI test cases

---

manager/integration/deploy/test.yaml

Work with Longhorn Manager: 99bf3fe7a17556e5c1b74aa6a8b31f4c584b0387

manager: Update image

---

manager/integration/deploy/test.yaml

Matching longhorn manager a34bd98b85ee34d895d697852d2579807aecf55f

Update image to rancher/longhorn-manager-test:c0a71ec

---

manager/integration/tests/test_basic.py

Add test-case for replica scheduler.

add scheduler test-case

---

manager/integration/Makefile
manager/integration/deploy/test.yaml
manager/integration/deploy/update_image.sh

Also add update_image.sh and Makefile

Update image to rancher/longhorn-manager-test:a96f5e9

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

Host API has been removed from manager, using Node API instead of it.

Replace Host API in test

---

manager/integration/deploy/test.yaml

Match manager: rancher/longhorn-manager:cc732c2
Commit: addaf4fbb2f74e8af41572f77322075e05afba20

manager: Update image to rancher/longhorn-manager-test:5766348

---

manager/integration/deploy/test.yaml

Matches:
commit 1b8dfe6aab50e0353a1586dcc05f572dc2619739
Date:   Sun Jul 15 17:17:49 2018 -0700
Update image to rancher/longhorn-manager:ca05cce

manager: Update image to rancher/longhorn-manager-test:e36c5c4

---

manager/integration/deploy/test.yaml

Matching Longhorn Manager:
commit 85b1264f9235c6fc1db6a798be049f51231f3d5c
Date:   Tue Jul 24 20:56:54 2018 -0700
Update images
Manager to rancher/longhorn-manager:9b29b88
UI to rancher/longhorn-ui:4b87493
Currently we have backend websocket issues. If click on UI doesn't trigger
operations, please refresh the UI manually.

manager: update image to rancher/longhorn-manager-test:e006699

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_node.py

integration test for phase 3
Add StorageOverProvisioningPercentage and StorageMinimalAvailablePercentage settings for multiple disks scheduling test

Update test for multiple disk scheduling

---

manager/integration/deploy/test.yaml
manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_engine_upgrade.py
manager/integration/tests/test_flexvolume.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_migration.py
manager/integration/tests/test_node.py
manager/integration/tests/test_provisioner.py
manager/integration/tests/test_statefulset.py

Also updated the API for endpoint and engine changes.

Migration support

---

manager/integration/tests/common.py

Add cleanup node disks after node test, delete all test disks from node.
Fixed issue: https://github.com/rancher/longhorn/issues/136 and https://github.com/rancher/longhorn/issues/137

Add cleanup disks after node test

---

manager/integration/tests/common.py

Fixed issue: https://github.com/rancher/longhorn/issues/137

Add reset disks and settings after node tests

---

manager/integration/tests/test_node.py

Update DiskState tag with manager.
https://github.com/rancher/longhorn-manager/pull/140

Update DISK_STATE tag from State to state

---

manager/integration/tests/test_node.py

Fixed issue: https://github.com/rancher/longhorn/issues/141

Separate node test cases into small functions

---

manager/integration/tests/common.py

manager: Use hexdigest() for checksum

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

Fixed issue: https://github.com/rancher/longhorn/issues/136

Add test for delete umounted disks from node

---

manager/integration/tests/conftest.py
manager/integration/tests/test_base_image.py

Only run base image tests if all nodes support mount propagation

Conditionally run base image tests

---

manager/integration/tests/common.py
manager/integration/tests/conftest.py
manager/integration/tests/test_node.py

Test update for https://github.com/rancher/longhorn-manager/pull/151

Change disk state and node mountpropagation to condition

---

manager/integration/tests/common.py
manager/integration/tests/conftest.py

Fixed issue: https://github.com/rancher/longhorn/issues/180

Add check for node whether it has conditions key or not

---

manager/integration/deploy/test.yaml

Match manager:
commit 34bac041a58b1086361f6d7d653fcd9954ff104b
Date:   Wed Aug 8 01:09:34 2018 -0700
Update image
Manager to rancher/longhorn-manager:9838a5f
UI to rancher/longhorn-ui:99252cc

manager: update image to rancher/longhorn-manager-test:3a75952

---

manager/integration/tests/test_node.py

Add test case for https://github.com/rancher/longhorn-manager/pull/155

Add check disk schedule condition case

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_node.py

Add validation tests for https://github.com/rancher/longhorn-manager/pull/169

Add test for disks and settings validation

---

manager/integration/tests/test_node.py

After remove storageMaximum to disk status, api won't allow update maximum value, change test cases using reserved value to test edge case.
https://github.com/rancher/longhorn-manager/pull/174

remove set disk storageMaximum from test_node cases

---

manager/integration/deploy/test.yaml

Matching Longhorn Manager:
commit 266f566783e47ce5e351f98491ea5b7b86a875d2
Date:   Tue Aug 21 11:48:22 2018 -0700
Update images
Manager: rancher/longhorn-manager:2c17d9e
UI: rancher/longhorn-ui:72303d9

Update image to rancher/longhorn-manager-test:f9d9f7b

---

manager/integration/tests/test_node.py

https://github.com/rancher/longhorn/issues/243

Fix just under overprovisioning test for new scheduler algorithm

---

manager/integration/tests/conftest.py
manager/integration/tests/test_node.py

https://github.com/rancher/longhorn/issues/255

Add skip mark to node test when cluster didn't support MountPropagation

---

manager/integration/tests/common.py
manager/integration/tests/test_base_image.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py

https://github.com/rancher/longhorn/issues/287

Add test cases for backup/restore with csi

---

manager/integration/tests/test_ha.py

https://github.com/rancher/longhorn/issues/415

manager: Test prohibiting user from deleting the last replica

---

manager/integration/Dockerfile
manager/integration/tests/common.py
manager/integration/tests/test_basic.py

https://github.com/rancher/longhorn/issues/446

manager: add test for listing invalid backup volume

---

manager/integration/tests/common.py
manager/integration/tests/longhorn.py
manager/integration/tests/requirements.txt
manager/integration/tests/test_kubernetes.py

https://github.com/rancher/longhorn/issues/476

catched error caused by deleting a non-existing object

---

manager/integration/tests/test_recurring_job.py

https://github.com/rancher/longhorn/issues/362

added tests for recurringJob

---

manager/integration/tests/common.py
manager/integration/tests/test_kubernetes.py

https://github.com/rancher/longhorn/issues/512

manager: added test for PVC creation with default StorageClass set

---

manager/integration/tests/common.py
manager/integration/tests/test_kubernetes.py

https://github.com/rancher/longhorn/issues/513

refactor PV/PVC creation test

---

manager/integration/tests/test_basic.py

https://github.com/rancher/longhorn/issues/558

Use list_backupVolume to update last backup field in test_restore_inc()

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

https://github.com/rancher/longhorn/issues/557

Fix issue 'test_replica_scheduler_too_large_volume_fit_any_disks failed sometime'

---

manager/integration/deploy/backupstores/minio-backupstore.yaml
manager/integration/deploy/backupstores/nfs-backupstore.yaml

see: https://github.com/rancher/longhorn/pull/590

specify default namespace explicitly

---

test_framework/scripts/longhorn-setup.sh

- Use Longhorn images with master tag from longhornio dockerhub account

Use latest Longhorn images in testing framework

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py

Test cases to check if restoration completed when restoration call ended

Added testcases for restoration of new restored volume

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/602

Modified test cases for standby volume due to automatic attach feature

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py

Fixed previous commit for flake8 check

---

manager/integration/tests/test_scheduling.py

This PR modifies some of the assertions used to check the `Replicas` of a `Volume` in response to the fixes introduced to `longhorn-manager` in longhorn/longhorn-manager#324.
Previously, due to the scheduling behavior, the tests had to ensure that there were still running `Replicas` that were healthy, and that there were anywhere from two to four new `Replicas` that were attempting to be scheduled due to how the `longhorn-manager` logic was scheduling new `Replicas`. Now, since an unscheduled `replica` will not be marked as failed unless the `Node` goes offline, the checks have been modified to check for the following conditions in the case of a scheduling failure:
- There are two healthy `Replicas` that still exist.
- There is one `Replica` that is not scheduled.
- There should only be …

Modify replica assertions in scheduler tests

---

manager/integration/deploy/test.yaml

Reverts longhorn/longhorn-tests#161

Revert "manager: Update deployment to longhornio/longhorn-manager-test:master"

---

manager/integration/tests/test_kubernetes.py

This PR modifies the `KubernetesStatus` tests that deal with backing up the value of a `Volume`'s `KubernetesStatus` based on the changes in longhorn/longhorn-manager#342. There are two changes here:
- The `test_backup_kubernetes_status_pv` test has been completely removed, with the `test_backup_kubernetes_status_pod` renamed to just `test_backup_kubernetes_status`.
- Some of the `KubernetesStatus` values in `test_backup_kubernetes_status` have been modified to reflect the fact that the `PVName` and `PVStatus` fields should remain empty upon restore even though they may be stored in the `KubernetesStatus` of the backup.

Modify backup KubernetesStatus tests for PV changes

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/598

Add testcase for backup volume deletion, and function to wait for backup completion

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/629

Test Attaching volume without frontend

---

manager/integration/tests/conftest.py

This PR adds an option to `conftest.py` that allows for the user to disable any tests labeled as `Base Image` tests when using it. This option has also been enabled by default in the test spec file for now since the current iteration of the `Instance Manager` refactor does not support the `Base Image` feature.
This PR implements the `longhorn-tests` portion of longhorn/longhorn#650.

Disable Base Image tests for now

---

test_framework/Dockerfile.setup
test_framework/scripts/longhorn-setup.sh

- Use updated yml files from longhorn-manager to install longhorn.

test framework: fix longhorn deploy script

---

test_framework/scripts/longhorn-setup.sh

- check for instance-manager pods status before running tests

test framework: check instance manager pods status

---

manager/integration/deploy/test.yaml
manager/integration/tests/cloudprovider.py
manager/integration/tests/conftest.py
manager/integration/tests/digitalocean.py
manager/integration/tests/test_infra.py
test_framework/scripts/rke-setup.sh
test_framework/templates/3-nodes-k8s.yml

Add offline node test scenario to manager integration test

---

manager/integration/deploy/test.yaml

Signed-off-by: Shuo Wu <shuo@rancher.com>

Update test image to longhornio/longhorn-manager-test:staging

---

manager/integration/deploy/test.yaml
manager/integration/tests/common.py
manager/integration/tests/test_toleration_setting.py

https://github.com/longhorn/longhorn/issues/584

 Add test for toleration setting

---

manager/integration/tests/common.py
manager/integration/tests/test_base_image.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_recurring_job.py
manager/integration/tests/test_statefulset.py
test_framework/scripts/build.sh

Merging staging branch to master

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py

https://github.com/longhorn/longhorn/issues/709
https://github.com/longhorn/longhorn/issues/710

Add and use func delete_backup()

---

manager/integration/tests/test_basic.py

add fromBackup for StorageClass & PV creation test

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py

Included PR:
https://github.com/longhorn/longhorn-tests/pull/198

Merge PR from `staging` to `master` for backup test failure

---

manager/integration/deploy/test.yaml
manager/integration/tests/common.py
manager/integration/tests/test_toleration_setting.py

Included PR:
https://github.com/longhorn/longhorn-tests/pull/192

Merge PR from `staging` to `master` with modifications for toleration setting test

---

manager/integration/tests/common.py
manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/716

Set random backstore for recurring job tests

---

manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/717

Fix the failure of test_hard_anti_affinity_scheduling

---

manager/integration/tests/common.py
manager/integration/tests/test_toleration_setting.py

https://github.com/longhorn/longhorn-manager/pull/414

Update tests after standardizing labels

---

manager/integration/tests/test_engine_upgrade.py

https://github.com/longhorn/longhorn/issues/712

Retains ref count after live upgrade

---

manager/test_containers/compatibility/generate_version_image.sh
manager/test_containers/compatibility/package/Dockerfile

https://github.com/longhorn/longhorn/issues/729

Update build files for compatibility test image

---

manager/integration/tests/test_basic.py

We cannot use `wait_for_volume_healthy()` for the restoration volume. The `attached` time for restoration is short and the test may miss it.

Fix the issue then rewrite for test_storage_class_from_backup

---

manager/integration/Dockerfile
manager/integration/deploy/stress.yml
manager/integration/tests/common.py
manager/integration/tests/conftest.py
manager/integration/tests/test_stress.py

Add stress test

---

manager/integration/tests/test_toleration_setting.py

https://github.com/longhorn/longhorn/issues/734

Check engine image state in toleration setting test

---

manager/integration/tests/common.py
manager/integration/tests/test_base_image.py
manager/integration/tests/test_engine_upgrade.py

https://github.com/longhorn/longhorn/issues/718

Wait and check engine image deletion

---

manager/integration/tests/common.py

https://github.com/longhorn/longhorn/issues/740

Reset engine image when cleaning up client

---

manager/integration/tests/common.py

https://github.com/longhorn/longhorn/issues/734

Fix bug for func monitor_restore_progress()

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/747

Disable SETTING_CREATE_DEFAULT_DISK_LABELED_NODES before cleanup

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_kubernetes.py
manager/integration/tests/test_statefulset.py
manager/integration/tests/test_stress.py

add wait to create snapshot function

---

manager/integration/deploy/test.yaml
manager/integration/tests/common.py
manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/776

Test if replica directory of disk path is checked and recreated

---

manager/integration/tests/test_recurring_job.py

Check backup status in test_recurring_job

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

Add process crash case for ha_salvage_test()

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

manager: Fix missing changes for wait_for_volume_no_frontend()

---

manager/integration/deploy/stress.yml
manager/integration/tests/test_stress.py

stress test improvement

---

manager/integration/tests/common.py
manager/integration/tests/test_statefulset.py

Update CSI driver name

---

manager/integration/tests/common.py
manager/integration/tests/test_csi.py

Add test for CSI block volume

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/872

Add retry when checking the from-backup volume in test_storage_class_from_backup

---

manager/integration/tests/longhorn.py

longhorn.py: Add __iter__() for obj.__dict__

---

Dockerfile.dapper
manager/integration/Dockerfile
manager/integration/pytest.ini
manager/integration/tests/common.py
manager/integration/tests/conftest.py
manager/integration/tests/digitalocean.py
manager/integration/tests/longhorn.py
manager/integration/tests/requirements.txt
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_engine_upgrade.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_kubernetes.py
manager/integration/tests/test_node.py
manager/integration/tests/test_provisioner.py
manager/integration/tests/test_recurring_job.py
manager/integration/tests/test_scheduling.py
manager/integration/tests/test_statefulset.py
manager/integration/tests/test_tagging.py
manager/integration/tests/test_toleration_setting.py

https://github.com/longhorn/longhorn/issues/641

Upgrade integration tests to python 3

---

manager/integration/tests/test_stress.py

upgrade stress test to python 3

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py
manager/test_containers/build_test_images.sh

Test cases for volume expansion feature

---

manager/test_containers/upgrade/generate_live_upgrade_image.sh

test_container: Update live upgrade image

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/46

Check rebuild status in rebuild tests

---

manager/integration/deploy/test.yaml
manager/integration/tests/common.py
manager/integration/tests/digitalocean.py
manager/integration/tests/test_infra.py
test_framework/scripts/longhorn-setup.sh

add node offline test

---

manager/integration/tests/common.py

fix cleanup_client call in clients fixture finalizer

---

manager/integration/tests/test_toleration_setting.py

wait longhorn node up in test toleration settings

---

manager/integration/tests/common.py
manager/integration/tests/test_zone.py

add k8s zone tag integration test

---

manager/integration/tests/common.py
manager/integration/tests/test_stress.py

Enhance stress test 

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

add auto-salvage integration test

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

separate auto salvage test cases

---

manager/integration/tests/common.py

Remove IM check for wait_for_engine_image_deletion()

---

manager/integration/deploy/test.yaml
manager/integration/pytest.ini
manager/integration/scripts/upgrade-longhorn.sh
manager/integration/tests/conftest.py
manager/integration/tests/test_upgrade.py
test_framework/Jenkinsfile
test_framework/scripts/longhorn-setup.sh

Add integration test case for upgrade

---

test_framework/scripts/longhorn-setup.sh

run all integration tests after upgrade test

---

test_framework/scripts/longhorn-setup.sh

move backupstore creation after longhorn setup

---

manager/integration/tests/conftest.py

fix upgrade conftest.py

---

test_framework/Jenkinsfile

fix missing braces in Jenkinsfile

---

manager/integration/Dockerfile

manager: Update kubectl to v1.17

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

add wait for remount check for auto salvage tests

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1040

Fix test cases for volume expansion

---

manager/integration/tests/test_kubernetes.py

Need to check and wait for `volume.Status.KubernetesStatus` update.

Fix test_pvc_creation_with_default_sc_set()

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

longhorn/longhorn#991
longhorn/longhorn#1053

Add test case for default disks and node tags setup

---

manager/integration/deploy/test.yaml

manager: deploy: Change tag to master

---

manager/integration/Dockerfile
manager/integration/tests/common.py
manager/integration/tests/test_csi.py

Integration test for PV with XFS  filesystem

---

manager/integration/tests/common.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py

Add test case test_replica_rebuild_with_intensive_data() 

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

Add tests for no annotation and invalid node annotations

---

manager/integration/tests/test_recurring_job.py

add max recurring jobs test

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

Add test case test_engine_image_daemonset_restart()

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py
manager/integration/tests/test_tagging.py

https://github.com/longhorn/longhorn/issues/972

Update with new diskUpdate API

---

manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/1119
https://github.com/longhorn/longhorn/issues/673

manager: add test_replica_scheduler_rebuild_restore_is_too_big

---

manager/integration/tests/test_node.py

manager: Fix tests failures due to round up to 2MiB change in the manager

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/1186

manager: Fix test_volume_basic

---

manager/integration/tests/test_ha.py

The test may still fail if the recovery is very quick, but this should
reduce the chances.
https://github.com/longhorn/longhorn/issues/1144

manager: Workaround test_salvage_auto_crash_all_replicas

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py

Add a new test test_csi_expansion_canceling()

---

manager/integration/tests/test_csi.py
manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/1184

Fix test_replica_scheduler_rebuild_restore_is_too_big

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1141
https://github.com/longhorn/longhorn/issues/1144
https://github.com/longhorn/longhorn/issues/1169

Improve test_salvage_auto_crash

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/1185
https://github.com/longhorn/longhorn/issues/1169
https://github.com/longhorn/longhorn/issues/1144
https://github.com/longhorn/longhorn/issues/1141

Fix nightly tests

---

test_framework/Jenkinsfile
test_framework/scripts/longhorn-setup.sh

Signed-off-by: meldafrawi <mohamed.eldafrawi@rancher.com>

add option to include infra tests

---

test_framework/scripts/longhorn-setup.sh

fix infra test condition check

---

manager/integration/tests/test_ha.py

longhorn/longhorn#1167
longhorn/longhorn#1220

Add test for the corner case that the from-replica and the rebuilding replica are on the same node

---

manager/integration/tests/common.py
manager/integration/tests/test_engine_upgrade.py

https://github.com/longhorn/longhorn/issues/1137
https://github.com/longhorn/longhorn/issues/1225
https://github.com/longhorn/longhorn/issues/1235

Improve live upgrade tests

---

test_framework/scripts/longhorn-setup.sh
test_framework/terraform/digitalocean/do.tf

Nightly test increase instance size and fix upgarde check

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1244
longhorn/longhorn#1270

Add tests for rebuild with restoration/DR volume

---

manager/integration/tests/test_node.py

This test case is to cover no duplicate disk names in node default disk
config annotation
https://github.com/longhorn/longhorn/issues/1219
Add another test case for multiple paths in the same filesystem
https://github.com/longhorn/longhorn/issues/1293

manager: Add a test case in test_node_config_annotation_invalid() for duplicate disk name

---

manager/integration/tests/test_recurring_job.py

longhorn/longhorn#1267
longhorn/longhorn-manager#563

Update recurring jobs test to add labels mid test

---

manager/integration/tests/common.py

ensure snapshot purge progress will not exceed 100%

---

manager/integration/tests/test_ha.py

Add test_single_replica_failed_during_engine_start() skeleton

---

manager/integration/tests/test_ha.py

Add test skeletons for restore failures

---

manager/integration/tests/test_ha.py

Add test_volume_reattach_after_engine_sigkill skeleton

---

manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/307

manager: Add rebuild concurrent limit test skeleton

---

manager/integration/tests/test_node.py
manager/integration/tests/test_zone.py

longhorn/longhorn#1052
Note:
- I've moved `test_replica_zone_anti_affinity` to `test_zone.py`

add test_replica_zone_anti_affinity

---

manager/integration/tests/test_node.py

fix test_replica_datapath_cleanup

---

manager/integration/tests/test_provisioner.py

fix test_provisioner_tags

---

manager/integration/tests/test_scheduling.py
manager/integration/tests/test_settings.py

https://github.com/longhorn/longhorn/issues/1318
Also remove test skeleton for test_replica_rebuild_concurrent_limit.
https://github.com/longhorn/longhorn/issues/307

Add test skeleton for test_setting_guaranteed_engine_cpu 

---

manager/integration/tests/test_ha.py

Add test_engine_crash_during_restore() skeleton

---

manager/integration/tests/test_ha.py
manager/integration/tests/test_settings.py

test: Fix test_settings.py and test_ha.py

---

manager/integration/tests/test_node.py

This test case is to cover adding default disk back when the extra disk is unmounted
Since the extra disk will show the same filesystem ID as the default disk
when it is unmounted.
https://github.com/longhorn/longhorn/issues/1291

controller: Test case for adding default disk back when extra disk is unmounted

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

This test covers the replica scheduler should be able to schedule replica on
cordoned node when this setting is set to false.
And the replica scheduler should not schedule replica on cordoned node when
this setting is set to true.
https://github.com/longhorn/longhorn/issues/1287

test: Add test case for "Disable Scheduling On Cordoned Node" setting

---

manager/integration/tests/test_basic.py

longhorn/longhorn#1360
longhorn/longhorn#1373

Add and update test for the scheduling failed volume

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

Fix the nightly test failures

---

manager/integration/tests/test_ha.py

add test_single_replica_failed_during_engine_start

---

manager/integration/tests/common.py
manager/integration/tests/test_upgrade.py

Improve upgrade test to run multiple pods

---

manager/integration/tests/common.py
manager/integration/tests/requirements.txt
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1260

add integration tests for State transitions for a failure in backup restore

---

test_framework/scripts/provision.sh

test framework: upgrade docker to v19.03

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

Add test_dr_volume_with_last_backup_deletion() skeleton

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

add test_volume_reattach_after_engine_sigkill

---

manager/integration/tests/common.py
manager/integration/tests/test_settings.py

This test case covers guarantted engine cpu setting with both valid and
invalid settings, also verifies the requests cpu value.
https://github.com/longhorn/longhorn/issues/1318

setting: Test case for Guaranteed Engine CPU setting

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

fix prepare_host_disk to allow custom mkfs.ext4 options

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py

longhorn/longhorn#1380
longhorn/longhorn#1270

Fix wait_for_volume_restoration_start() and the related tests

---

manager/integration/tests/common.py

Added deletion of PV/PVC in pod_make fixture.
https://github.com/longhorn/longhorn/issues/1413

Cleanup  PV/PVC after test completion - test_ha.py

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

add test_backup_block_deletion

---

manager/integration/tests/common.py
manager/integration/tests/test_settings.py

This PR adds tests for the `Priority Class` setting feature that was requested in longhorn/longhorn#1487. This test attempts to test the following cases:
1. The user specifies a `Priority Class` that doesn't exist. The `longhorn-manager` should prevent this change.
2. The user specifies a valid `Priority Class`. The `longhorn-manager` should update the `Setting` and update all the `Longhorn` workloads to use this `Priority Class`.
3. The user does not specify a `Priority Class`. The `longhorn-manager` should update the `Longhorn` workloads to use no `Priority Class`.

Add tests for Priority Class setting

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

Add test test_dr_volume_with_restore_command_error()

---

manager/integration/tests/backupstore.py
manager/integration/tests/test_basic.py

test_backup_volume_list() make sure that instead of erroring the backup list should ignore the badly named files in backups folder.
longhorn/longhorn#1410

tests: add test_backup_volume_list to make sure that listing volume does not fail even there are bad names in backups folder

---

website/content/manual/release-specific/v1.0.1/test-s3-access-style.md

doc: Add manual test 'Test access style for S3 compatible backupstore'

---

manager/integration/tests/backupstore.py
manager/integration/tests/common.py

Implement NFS helper functions

---

manager/integration/tests/test_rwx.py

https://github.com/longhorn/longhorn/issues/1606
I've added a new file test_rwx.py and added a few test skeletons for rwx volumes.

Test skeleton for rwx volumes

---

test_framework/Jenkinsfile

add test report summary to slack notification message

---

test_framework/Jenkinsfile

test framework: fix duplicate definition of summary variable

---

test_framework/Jenkinsfile

Reverts longhorn/longhorn-tests#377

Revert "test framework: fix duplicate definition of summary variable"

---

test_framework/Jenkinsfile

Reverts longhorn/longhorn-tests#374

Revert "add test report summary to slack notification message"

---

test_framework/Jenkinsfile

test framework: add failure test count to slack notifications

---

secscan/Dockerfile.setup
secscan/Jenkinsfile
secscan/scripts/build.sh
secscan/scripts/cleanup.sh
secscan/scripts/provision.sh
secscan/scripts/secscan.sh
secscan/scripts/terraform-setup.sh
secscan/templates/junit.tpl
secscan/terraform/digitalocean/do.tf
secscan/terraform/digitalocean/do.tfvars

add longhorn security scan job

---

test_framework/Jenkinsfile

Fix wrong test count in longhorn upgrade test junit report

---

secscan/Jenkinsfile
secscan/scripts/secscan.sh
secscan/terraform/digitalocean/do.tf

add severity options to security scan job

---

docs/content/manual/pre-release/stability/_index.md
docs/content/manual/pre-release/stability/multiple-installation.md
docs/content/manual/pre-release/upgrade/upgrade-conflict-handling.md

Test case for longhorn multiple installations is added in pre-release tests under stability folder.

Add manual test for longhorn multiple installations

---

test_framework/scripts/longhorn-setup.sh

run nightly tests using v1.0.x branch instead of master

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py
manager/test_containers/build_test_images.sh

Update and add new tests for the refactored restore feature

---

manager/test_containers/upgrade/generate_live_upgrade_image.sh

test container: Update live upgrade test image to version 4-3-1

---

docs/content/manual/pre-release/node/improve-node-failure-handling.md

This tests the fix for improve node failure handling enhancement
longhorn/longhorn#1105

docs: add manual test for feature: improve node failure handling

---

docs/content/manual/pre-release/backup-and-restore/dr-volume-live-upgrade-and-rebuild.md

doc: Add manual test 'DR volume live upgrade and rebuild'

---

manager/integration/tests/test_ha.py

add test_rebuild_after_replica_file_crash

---

manager/integration/tests/test_engine_upgrade.py
manager/test_containers/build_test_images.sh

Fix test_engine_image_incompatible after modifying the compatibility check logic

---

manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/298

Add test skeleton for node eviction

---

manager/integration/tests/test_scheduling.py

manager/integration/tests: add test skeleton to test data locality feature

---

manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1679

Add test skeleton for extra replica cleanup

---

manager/integration/tests/test_node.py

After Longhorn #1704 adding eviction support for detached volume. Adding
test steps for detached volumes case.
https://github.com/longhorn/longhorn/issues/1704

Update test skeleton for node eviction

---

manager/integration/tests/test_csi.py

Add csi snapshot test skeleton

---

manager/integration/deploy/rwx_requirements.yaml
manager/integration/tests/common.py
manager/integration/tests/test_rwx.py
test_framework/scripts/longhorn-setup.sh

https://github.com/longhorn/longhorn/issues/1606

Add rwx test cases

---

manager/integration/tests/common.py
manager/integration/tests/test_scheduling.py

add data locality integration test

---

docs/content/manual/release-specific/v1.1.0/additional-printer-columns.md

Add manual test plan to test Longhorn CRDs after adding additional printer columns

---

manager/integration/tests/test_ha.py
manager/integration/tests/test_upgrade.py

https://github.com/longhorn/longhorn/issues/508

Add auto salvage with revision counter disabled test skeleton

---

manager/integration/tests/test_ha.py

add test_extra_replica_cleanup

---

docs/content/manual/release-specific/v1.1.0/prometheus_support.md

https://github.com/longhorn/longhorn/issues/1180
Doc link will be updated once the doc PR is merged. https://github.com/longhorn/website/pull/195

Add manual test steps for Prometheus Support.

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/612

Add test skeleton for locks

---

manager/integration/tests/test_node.py

longhorn/longhorn/issues/298
longhorn/longhorn/issues/1704

add test_node_eviction

---

manager/integration/tests/test_recurring_job.py

Test skeleton for feature allow-recurring-job-while-volume-detached

---

manager/integration/tests/test_node.py

fix test_node_eviction

---

.drone.yml
manager/integration/Dockerfile
manager/integration/build-image.sh

https://github.com/longhorn/longhorn/issues/6

ARM64 support for tests

---

manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/307

Disable replica rebuild test skeleton

---

docs/content/manual/pre-release/node/node-drain-deletion.md

https://github.com/longhorn/longhorn/issues/1286

Add manual test case for node drain.

---

manager/integration/deploy/backupstores/nfs-backupstore.yaml

https://github.com/longhorn/longhorn/issues/6

Update nfs backupstore image

---

docs/content/manual/pre-release/node/node-deletion.md

doc: Add a manual test for the node cleanup feature

---

manager/integration/deploy/backupstores/minio-backupstore.yaml

https://github.com/longhorn/longhorn/issues/6

Update minio backupstore image to support amd64 and arm64

---

docs/content/manual/pre-release/node/degraded-availability.md
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py

https://github.com/longhorn/longhorn/issues/1701

test plan: Allow volume creation with degraded availability

---

manager/integration/tests/test_ha.py

Add automation skeleton for feture `handling volume remount by killing the consuming pod

---

manager/integration/deploy/test.yaml

change test image to use v1.0.x

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/1669

Add cleanup system generated snapshots test skeleton

---

manager/integration/tests/test_csi.py

https://github.com/longhorn/longhorn/issues/357

Add test skeleton for csi minimal volume size

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/1669

Add system created snapshot cleanup test

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

Add test skeleton 'test_reuse_failed_replica'

---

manager/integration/tests/test_engine_upgrade.py

* Add checks for volume replica rebuild.
* Fix exception while cleaning up engine image.

Enhance test_engine_live_upgrade_with_intensive_data_writing

---

docs/content/manual/release-specific/v1.1.0/instance-manager-ip-sync.md

doc: Add a manual test for the InstanceManager IP sync issue

---

secscan/Jenkinsfile

ignore empty results for secscan nightly tests

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/496

Add test skeleton for volume 'TooManySnapshots' condition

---

docs/content/manual/pre-release/upgrade/engine-crash-during-live-upgrade.md

doc: Add a manual test 'engine-crash-during-live-upgrade'

---

manager/integration/tests/test_recurring_job.py

Update test skeleton to check backup cronjob that runs on node with taint

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

The handlePodDeletionIfVolumeRequestRemount only handles pod with controller. And the livenessProbe only restarts the container inside of the pod, therefore volume doesn't get re-mounted as expected. Use StatefulSet to fix test failures caused by "pod with crashed replicas never gets deleted for auto salvage".
Also, removed rebuild since it's no longer required with reusable replicas.
https://github.com/longhorn/longhorn/issues/1914

Fix auto salvage replicas addressing remount logic

---

docs/content/manual/release-specific/v1.1.0/upgrade_with_modified_storageclass.md

https://github.com/longhorn/longhorn/issues/1527

Add manual test for upgrade longhorn with modified storage class

---

manager/integration/tests/test_basic.py

Fix scheduled failure assertion message

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1918

Fix rebuild related tests

---

docs/content/manual/release-specific/v1.1.0/iscsi_installation.md

https://github.com/longhorn/longhorn/issues/1741

Add ISCSI Installation Manual Test

---

docs/content/manual/pre-release/ha/replica-rebuilding.md

longhorn/longhorn#1304
longhorn/longhorn#1936

doc: Add a pre-release test for replica rebuilding

---

manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/1951
Signed-off-by: khushboo <khushboo@rancher.com>

Fix data_locality_test failure

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

Update tests for disk migration

---

docs/content/manual/pre-release/ha/disk-migration-in-aws-asg.md
docs/content/manual/release-specific/v1.1.0/longhorn-upgrade-with-node-down-and-removal.md

Add manual tests for disk migration feature 

---

manager/integration/tests/common.py
manager/integration/tests/test_csi.py

https://github.com/longhorn/longhorn/issues/357

Implement test_csi_minimal_volume_size

---

docs/content/manual/release-specific/v1.1.0/reusing-failed-replica-for-rebuilding.md

Update manual test for disk migration

---

test_framework/terraform/aws/main.tf

fix terraform aws instance root device size

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/496

Implement test_volume_toomanysnapshots_condition

---

docs/content/manual/release-specific/v1.1.0/recurring-backup-job-interruptions.md

https://github.com/longhorn/longhorn/issues/1882

Add manual test cases for recurring backup job interruptions

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

Split original into two scenarios.
https://github.com/longhorn/longhorn/issues/1701

Implement test_allow_volume_creation_with_degraded_availability_api

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1719

Implement test_auto_remount_with_subpath

---

docs/content/manual/pre-release/ha/disk-migration-in-aws-asg.md

Manual test cases for disk migration in AWS in a set up of ASG.

Modify the disk migration test with ASG

---

docs/content/manual/release-specific/v1.1.0/uninstallation.md

https://github.com/longhorn/longhorn/issues/1653

Add manual test for performance improvement of uninstallation

---

manager/integration/tests/common.py
manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/307

Implement test_replica_rebuild_per_volume_limit

---

manager/integration/tests/test_ha.py

integration: Add skeleton test_replica_failure_during_attaching

---

manager/integration/tests/test_settings.py

https://github.com/longhorn/longhorn/issues/1977

Implement test_setting_toleration_extra

---

manager/integration/tests/common.py
manager/integration/tests/test_csi.py

https://github.com/longhorn/longhorn/issues/1701

Implement test_allow_volume_creation_with_degraded_availability_csi

---

docs/content/manual/pre-release/upgrade/update_csi_components_when_images_change.md

Add manual test plan to verify that CSI components' images are updated

---

manager/integration/tests/common.py

longhorn/longhorn#2055
The api returns 500 when trying to set the priority class setting, while there are volumes that are non detached.
Therefore I only clear the priority setting when it's not empty already, to prevent misleading error messages in the log.
There seems to be some timing issues here, that there are some volumes still not detached (might be in detaching) state during cleanup.

Ensure priority class setting gets reset irregardless of test failure

---

manager/integration/tests/common.py
manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/1509

implement test_recurring_jobs_for_detached_volume

---

manager/integration/tests/common.py
manager/integration/tests/test_ha.py

Implement test_reuse_failed_replica test and test_reuse_failed_replica_with_scheduling_check

---

manager/integration/tests/test_basic.py

Add skeleton test for test_multiple_volumes_creation_with_degraded_availability

---

docs/content/manual/release-specific/v1.1.0/rwx_feature.md

https://github.com/longhorn/longhorn/issues/1470

Add manual test for RWX feature

---

docs/content/manual/pre-release/backup-and-restore/concurrent-backup-creation-deletion.md
docs/content/manual/pre-release/node/auto-detach/deployment.md
docs/content/manual/pre-release/node/auto-detach/statefulset.md
docs/content/manual/release-specific/v1.1.0/prometheus_support.md
docs/content/manual/release-specific/v1.1.0/recurring-backup-job-interruptions.md

Modify the Prerelease tests according to the latest behavior of the product.
Signed-off-by: khushboo <khushboo@rancher.com>

Modify the pre-release test

---

manager/integration/tests/common.py

Move SETTING_* together and in alphabetic order.

Clean SETTING_*

---

manager/integration/tests/test_scheduling.py

Fixed some timing issues. More explanation in comments below

Fix: test_data_locality_basic sometimes fails

---

manager/integration/Dockerfile
manager/integration/build-image.sh
manager/integration/tests/backupstore.py
manager/integration/tests/common.py
manager/integration/tests/requirements.txt
manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_kubernetes.py
manager/integration/tests/test_recurring_job.py
manager/integration/tests/test_stress.py

This PR will fix
https://github.com/longhorn/longhorn/issues/1802
https://github.com/longhorn/longhorn/issues/1803

Run tests against both S3 and NFS backupstores.

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_node.py
manager/integration/tests/test_recurring_job.py

fix set_random_backupstore fixture direct call

---

manager/integration/deploy/backupstores/nfs-backupstore.yaml

REF: https://github.com/longhorn/docker-nfs-ganesha#nfs_disk_image_size_mb

increase NFS server pod internal disk size to 4GB

---

manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/2158

Fix recurring_job_label test

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py

fix failing tests

---

manager/integration/tests/common.py
manager/integration/tests/test_rwx.py

https://github.com/longhorn/longhorn/issues/2110

Add rwx tests

---

test_framework/Dockerfile.setup
test_framework/scripts/cleanup.sh
test_framework/scripts/longhorn-setup.sh
test_framework/scripts/rke-setup.sh
test_framework/scripts/terraform-setup.sh

use bash instead of ash

---

manager/integration/tests/test_rwx.py

https://github.com/longhorn/longhorn/issues/2110

Fix missed backupstore fixture

---

docs/content/manual/release-specific/v1.1.1/disable_ipv6.md
secscan/scripts/secscan.sh

https://github.com/longhorn/longhorn/issues/2111
https://github.com/longhorn/longhorn/issues/2136

Add ipv6 disable test and add share manager to the image scan list

---

manager/integration/tests/test_engine_upgrade.py

add test skeleton for feature `Automatically upgrade volumes' engine to the default engine image after upgrading Longhorn`

---

test_framework/Jenkinsfile

test framework: fix docker image name in run command

---

docs/content/manual/pre-release/upgrade/auto-upgrade-engine.md

Add manual test for `Automatically Upgrading Longhorn Engine` feature

---

test_framework/terraform/aws/rhel/user-data-scripts/provision_amd64.sh
test_framework/terraform/aws/rhel/user-data-scripts/provision_arm64_agent.sh.tpl
test_framework/terraform/aws/rhel/user-data-scripts/provision_arm64_server.sh.tpl
test_framework/terraform/aws/rhel/variables.tf
test_framework/terraform/aws/sles/data.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/sles/output.tf
test_framework/terraform/aws/sles/user-data-scripts/provision_amd64.sh
test_framework/terraform/aws/sles/user-data-scripts/provision_arm64_agent.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_arm64_server.sh.tpl
test_framework/terraform/aws/sles/variables.tf

https://github.com/longhorn/longhorn/issues/2159

add SLES support to test framework

---

test_framework/Jenkinsfile
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/ubuntu/main.tf

update longhorn integration tests framework

---

test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/ubuntu/main.tf

https://github.com/longhorn/longhorn/issues/2159

fix k3s wait for running nodes

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_node.py

Split original into two scenarios.
https://github.com/longhorn/longhorn/issues/1701

Implement test_allow_volume_creation_with_degraded_availability_restore

---

manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1999
Author: khushboo-rancher <60111667+khushboo-rancher@users.noreply.github.com
Co-authored-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

Add test_replica_failure_during_attaching test

---

Dockerfile.dapper

update base image for dapper dockerfile

---

docs/content/manual/pre-release/upgrade/auto-upgrade-engine.md
docs/content/manual/release-specific/v1.1.1/disable_ipv6.md

Added corner test cases for the upgrade engine image verification

Anupama2501 longhorn

---

manager/integration/scripts/upgrade-longhorn.sh
manager/integration/tests/conftest.py
manager/integration/tests/test_upgrade.py
test_framework/Dockerfile.setup
test_framework/Jenkinsfile
test_framework/scripts/longhorn-setup.sh

REF:
https://github.com/longhorn/longhorn/issues/2159
https://github.com/longhorn/longhorn/issues/1718

refactor longhorn setup script and add custom image support

---

manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/1922

Add test case for test_recurring_jobs_when_volume_detached_unexpectedly

---

secscan/Jenkinsfile
test_framework/Jenkinsfile
test_framework/scripts/cleanup.sh
test_framework/scripts/longhorn-setup.sh
test_framework/scripts/terraform-setup.sh

REF: https://github.com/longhorn/infra/pull/36

fix test framework issues and add support for slack notification channel update

---

docs/content/manual/release-specific/v1.1.1/csi-sanity-check.md

https://github.com/longhorn/longhorn/issues/2076

Add manual test for CSI sanity check

---

manager/integration/tests/test_kubernetes.py

https://github.com/longhorn/longhorn/issues/1539

Test KubernetesStatus Label exists in volume.cfg

---

manager/integration/scripts/upgrade-longhorn.sh
manager/integration/tests/test_upgrade.py

* Fix upgrade script argument sequence.
* Fix upgrade script manifest's path.
* Fix typos.
https://github.com/longhorn/longhorn/issues/2300

Fix e2e Longhorn upgrade

---

manager/integration/tests/test_backing_image.py

Signed-off-by: Shuo Wu <shuo@rancher.com>

fix typo for function backing_image_basic_operation_test

---

docs/content/manual/pre-release/upgrade/upgrade-with-new-instance-manager.md
docs/content/manual/release-specific/v1.1.1/system-upgrade-with-deprecated-cpu-setting.md
manager/integration/tests/common.py
manager/integration/tests/test_settings.py

Update tests and add manual tests for the enhanced CPU reservation feature

---

manager/integration/tests/common.py

add check for backing image feature support

---

docs/content/manual/release-specific/v1.1.1/delete-node.md

https://github.com/longhorn/longhorn/issues/2186

Add manual test for node delete

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_engine_upgrade.py
manager/integration/tests/test_ha.py
manager/integration/tests/test_migration.py
manager/integration/tests/test_node.py
manager/integration/tests/test_recurring_job.py
manager/integration/tests/test_scheduling.py
manager/integration/tests/test_settings.py
manager/integration/tests/test_stress.py
manager/integration/tests/test_upgrade.py

longhorn/longhorn#2127
depends on https://github.com/longhorn/longhorn-manager/pull/822

E2E tests for volume live migration

---

manager/integration/tests/test_basic.py

Missing backupstore targets.
https://github.com/longhorn/longhorn/issues/2323

Fix test_deleting_backup_volume

---

manager/integration/tests/common.py
manager/integration/tests/test_engine_upgrade.py
manager/integration/tests/test_upgrade.py

Ref: https://github.com/longhorn/longhorn/issues/2321

fix nightly upgrade test

---

manager/integration/tests/test_settings.py

This test is not updated after changing the design of the cpu reservation feature: Right now the deprecated setting shouldn't work. And Longhorn will error out when users try to update it.
Sorry for that. Will be careful next time.

integration: Fix test_instance_manager_cpu_reservation

---

manager/integration/tests/test_basic.py

Missing backupstore target.
https://github.com/longhorn/longhorn/issues/2342

Fix test_storage_class_from_backup

---

manager/integration/tests/test_settings.py

Fix test_setting_toleration*.
https://github.com/longhorn/longhorn/issues/2345
Fix test_setting_priority_class.
https://github.com/longhorn/longhorn/issues/2346

Correct engine image state value

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_engine_upgrade.py

Correct engine image state.
- Fix test_engine
- Fix test_engine_image_incompatible
Also need to get https://github.com/longhorn/longhorn/issues/2351 fixed for regression tests to pass.

Fix test_engine_image*

---

manager/integration/tests/run.sh
test_framework/Jenkinsfile

Ref: https://github.com/longhorn/longhorn/issues/2334

Fix nightly tests framework

---

manager/integration/tests/test_ha.py

When a replica fails, the reuse failed replica feature kicks in first
and it reset replica.failedAt = "", so it takes time for the replica.failedAt
to be set again when the rebuilding of the replica fail.
longhorn/longhorn#2367

Fix test_single_replica_failed_during_engine_start

---

test_framework/terraform/aws/sles/user-data-scripts/provision_amd64.sh
test_framework/terraform/aws/sles/user-data-scripts/provision_arm64_agent.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_arm64_server.sh.tpl

updating all sles packages will exceed the terraform step timeout

refresh sles repo instead of update

---

manager/integration/tests/requirements.txt

Allows repeat runs for testing stable cases using the `--count` option.
https://github.com/longhorn/longhorn/issues/2379

Add pytest-repeat

---

docs/content/manual/pre-release/basic-operations-parallelism/_index.md
docs/content/manual/pre-release/basic-operations-parallelism/snapshot-while-writing-data.md

https://github.com/longhorn/longhorn/issues/2187

Add manual test for fsfreeze

---

docs/content/manual/pre-release/cluster-restore/_index.md
docs/content/manual/pre-release/cluster-restore/node-creation-deletion-with-restore.md
docs/content/manual/pre-release/cluster-restore/recover-volumes-after-restore.md
docs/content/manual/pre-release/cluster-restore/system-upgrade-with-restore.md

doc: Add manual test for the cluster restore issue

---

manager/integration/tests/run.sh
test_framework/scripts/longhorn-setup.sh

https://github.com/longhorn/longhorn/issues/2333

fix empty junit report

---

docs/content/manual/release-specific/v1.1.1/ws-traffic-flood.md

https://github.com/longhorn/longhorn/issues/2372

Add manual test for ws traffic

---

manager/integration/tests/test_settings.py

Modify test skeleton for test_setting_toleration_extra, test_setting_toleration, test_setting_priority_class

---

docs/content/manual/release-specific/v1.1.1/aws-iam-role-for-volume-backup-restore.md

https://github.com/longhorn/longhorn/issues/1526

doc: Add manual test for volume backup and restore by AWS IAM role

---

docs/content/manual/release-specific/v1.1.1/test-service-account-mount.md

Add manual test case: `Test Service Account Mounts On Host`

---

docs/content/manual/release-specific/v1.1.1/rwx-mount-ownership-reset.md

https://github.com/longhorn/longhorn/issues/2357

Add manual test for rwx mount ownership reset

---

docs/content/manual/release-specific/v1.1.1/tolerations_priorityclass_setting.md

Add manual test plan for the refactoring Set Tolerations For System Components and User-deployed Components Separately

---

docs/content/manual/pre-release/node/backing-image-on-a-down-node.md
docs/content/manual/pre-release/upgrade/backing-image-during-upgrade.md

docs: Update manual tests for enhanced backing image feature

---

docs/content/manual/pre-release/ha/single-replica-node-down.md

https://github.com/longhorn/longhorn/issues/2329
https://github.com/longhorn/longhorn/issues/2309
Signed-off-by: khushboo-rancher <fnu.khushboo@suse.com>

Add test case for volume having single node power down

---

docs/content/manual/pre-release/ha/partial-engine-deployment.md
docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md

https://github.com/longhorn/longhorn/issues/2081
Signed-off-by: khushboo-rancher <fnu.khushboo@suse.com>

Add test cases for engine not deployed fully

---

secscan/Dockerfile.setup
secscan/terraform/digitalocean/do.tf
secscan/terraform/digitalocean/versions.tf

secscan framework: upgrade terraform to v0.14.10

---

docs/content/manual/release-specific/v1.1.1/delete-node.md

https://github.com/longhorn/longhorn/issues/2462

Update Manual Test - Node Delete

---

manager/integration/tests/test_ha.py

Update to check the volume manager's response since we're now always [allowed api attach and detach calls](https://github.com/longhorn/longhorn-manager/blob/master/api/model.go#L965-L968).
https://github.com/longhorn/longhorn/issues/2499
https://github.com/longhorn/longhorn-manager/pull/859

Fix test_all_replica_restore_failure

---

docs/content/manual/release-specific/v1.1.1/test-node-selector.md

Add manual test for node selector feature

---

manager/integration/tests/test_settings.py

Check the toleration change for the managed components since we only watch and updated those.
https://github.com/longhorn/longhorn/issues/2500
https://github.com/longhorn/longhorn-manager/pull/842

Fix test_setting_toleration*

---

docs/content/manual/release-specific/v1.1.1/test-file-sync-cancellation.md

docs: Add manual test 'Test File Sync Cancellation'

---

manager/integration/tests/test_basic.py

The backup & restore should involve at least 2 blocks.

tests: Update test_restore_inc

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn-manager/commit/acd2cee029bfc63ffd3c81b1892521e700868da3
https://github.com/longhorn/longhorn/issues/2515

Fix test_allow_volume_creation_with_degraded_availability_error

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn-manager/commit/acd2cee029bfc63ffd3c81b1892521e700868da3
https://github.com/longhorn/longhorn/issues/2514

Fix test_volume_scheduling_failure

---

manager/integration/tests/test_ha.py

longhorn/longhorn#1236
Signed-off-by: Shuo Wu <shuo.wu@suse.com>

integration: Fix ha_salvage_test

---

docs/content/manual/pre-release/upgrade/kubernetes-upgrade-test.md

https://github.com/longhorn/longhorn/issues/2574

Add test cases for kubernetes upgrade

---

docs/content/manual/pre-release/stress/backup-listing.md

https://github.com/longhorn/longhorn/issues/2586

Add backup listing stress testing

---

manager/integration/deploy/stress.yml
manager/integration/deploy/test.yaml

Changing the image for longhorn-test

Change master tag to master head

---

manager/integration/tests/test_recurring_job.py

fix test recurring job with backup of 2 to resolve ticket '[BUG] Tests related to recurring job are failing in nightly integration test runs.' (#2589)
- tests.test_recurring_job.test_recurring_job[nfs]
- tests.test_recurring_job.test_recurring_job[s3]
as result of 
- [[ENHANCEMENT] automatic sucessful backups should only retain the last snapshot #2231](https://github.com/longhorn/longhorn/issues/2231)
- [Only keep upto 2 snapshots for recurring backup jobs #884](https://github.com/longhorn/longhorn-manager/pull/884)
Bug Fixing
Refs: # https://github.com/longhorn/longhorn/issues/2589
None

fix test recurring job with backup of 2 (#2589)

---

docs/content/manual/release-specific/v1.1.2/full-ws-data-tranfer-when-no-updates.md

https://github.com/longhorn/longhorn/issues/2672

Update manual test - [v1.1.2] ws data transfer when resource not updated

---

test_framework/scripts/longhorn-setup.sh

[v1.1.2-backport] fix nightly upgrade test

---

manager/integration/tests/common.py
manager/integration/tests/test_scheduling.py
manager/integration/tests/test_zone.py

https://github.com/longhorn/longhorn/issues/587

Add test for replica auto balance

---

docs/content/manual/release-specific/v1.1.2/instance-manager-streaming-connection-recovery.md

docs: Add manual test 'Test Instance Manager Streaming Connection Recovery

---

docs/content/manual/release-specific/v1.1.2/delete-cronjob-for-detached-volumes.md

Add manual test for CronJob of volumes that are detached for a long time

---

manager/integration/tests/test_upgrade.py

https://github.com/longhorn/longhorn/issues/2698

[v1.1.2-backport] fix nightly ugrade test

---

manager/integration/tests/test_upgrade.py

https://github.com/longhorn/longhorn/issues/2698
Nightly tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/285/

fix nightly ugrade test

---

docs/content/manual/pre-release/node/kubelet-restart-on-a-node.md

https://github.com/longhorn/longhorn/issues/2629

Add kubelet restart test cases

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py

add test for use pvc to expand volume to resolve ticket 'Application couldn't mount the volume after expanded the volume' (#2422)

add test for use pvc to expand volume (#2422)

---

manager/integration/tests/test_scheduling.py
manager/integration/tests/test_zone.py

Ensures the n1 dev is created at the test pod host.
https://github.com/longhorn/longhorn/issues/2716

Fix unstable test_replica_auto_balance_*

---

manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/2727

fix test_data_locality_basic

---

manager/integration/tests/test_scheduling.py

https://github.com/longhorn/longhorn/issues/2727

[v1.1.2-backport] fix test_data_locality_basic

---

manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/2729

fix test_rebuild_failure_with_intensive_data

---

manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/2729

[v1.1.2-backport] fix test_rebuild_failure_with_intensive_data

---

manager/integration/tests/common.py
manager/integration/tests/test_rwx.py
manager/integration/tests/test_statefulset.py

Fix rwx test case unstable issue to resolve issue '[TEST] fix rwx test case unstable issue'
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/314/testReport/tests/
Refs: Longhorn: https://github.com/longhorn/longhorn/issues/2748
None

Fix rwx test case unstable issue

---

manager/integration/tests/test_recurring_job.py

Backport timing issue for test recurring job to resolve issue '[BUG] Test: recurring_job related tests are failing in nightly tests run.'
Bug Fix
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/318/
Refs: #2158
None

Backport timing issue for test recurring job

---

manager/integration/deploy/backupstores/nfs-backupstore.yaml

https://github.com/longhorn/longhorn/issues/2699

Increase liveness timeout to 4 secs

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_csi.py
manager/integration/tests/test_ha.py

Use `set_random_backupstore` test fixture to simplifies configure set S3/NFS in each test case.
- test_basic.py::backup_status_for_unavailable_replicas_test
- test_basic.py::test_backup
- test_basic.py::test_backup_labels
- test_csi.py::test_csi_backup
- test_ha.py::test_ha_backup_deletion_recovery

Use set_random_backupstore to set S3/NFS

---

manager/integration/tests/test_csi.py

Remove extra parameter in backupstore_test

---

manager/integration/tests/test_csi_snapshotter.py

Fix the indentation, the total snapshot count is 2.

Fix: test_csi_volumesnapshot_basic flakiness

---

manager/integration/tests/test_ha.py

fix flake8

---

manager/integration/tests/common.py
manager/integration/tests/test_node.py

longhorn/longhorn#2730
This is to backport https://github.com/longhorn/longhorn-tests/pull/653

Fix available storage related tests

---

test_framework/scripts/longhorn-setup.sh

use default images by default if not customized

---

docs/content/manual/pre-release/ha/backing-image-error-reporting-and-retry.md
docs/content/manual/pre-release/node/backing-image-on-a-down-node.md
docs/content/manual/pre-release/upgrade/backing-image-during-upgrade.md
manager/integration/tests/common.py
manager/integration/tests/test_backing_image.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_recurring_job.py
manager/test_containers/build_test_images.sh

Update tests after backing image refactoring & enhancement

---

docs/content/manual/release-specific/v1.2.0/test-backing-image-upload.md

longhorn/longhorn#2404
Signed-off-by: Shuo Wu <shuo.wu@suse.com>

Update the integration tests and add a manual test for the backing image upload

---

manager/integration/deploy/stress.yml
manager/integration/deploy/test.yaml
manager/integration/tests/backupstore.py
manager/integration/tests/common.py
manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py

https://github.com/longhorn/longhorn/issues/1761

Backup refactoring

---

secscan/scripts/provision.sh
secscan/terraform/digitalocean/do.tf

update security scan framework

---

manager/integration/deploy/test.yaml

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/379/testReport/tests/test_recurring_job/test_recurring_job_groups_s3_/
https://github.com/longhorn/longhorn-tests/pull/658

Add RBAC to do recurring job pre-merge tests

---

secscan/Dockerfile.setup
secscan/scripts/cleanup.sh
secscan/scripts/terraform-setup.sh
secscan/terraform/digitalocean/do.tf
secscan/terraform/digitalocean/versions.tf

security scan: fix security scan apt lock at droplet startup

---

docs/content/manual/release-specific/v1.2.0/test-backing-image-upload.md

longhorn/longhorn#2899
longhorn/longhorn#2900

docs: Add more tests for backing image features

---

manager/integration/tests/test_cloning.py

Add test sketleton for volume cloning feature

---

docs/content/manual/release-specific/v1.2.0/label-driven-recurring-job.md
manager/integration/tests/common.py
manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/467

Automate and manual tests for label-driven recurring job

---

manager/integration/tests/test_recurring_job.py

comments
- https://github.com/longhorn/longhorn-tests/pull/658#discussion_r692802192
- https://github.com/longhorn/longhorn-tests/pull/658#discussion_r692806900
https://github.com/longhorn/longhorn/issues/467

Fix test skeleton test_recurring_job_multiple_volumes

---

docs/content/manual/pre-release/uninstallation/uninstallation-checks.md

This test case is to make sure the uninstallation is working fine.

Add uninstallation checks in manual test

---

docs/content/manual/release-specific/v1.2.0/test-instance-manager-cleanup-during-uninstall.md

docs: Add a manual test 'instance manager cleanup during uninstall'

---

secscan/scripts/secscan.sh

add csi images to security scan

---

docs/content/manual/release-specific/v1.2.0/test_version_bump.md

Add manual test for version bump in Longhorn v1.2.0

---

manager/integration/tests/common.py

https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-upgrade-tests-ubuntu-amd64/436/testReport/
https://github.com/longhorn/longhorn/issues/467

Fix test_upgrade fail at cleanup_client due to recurring job feature

---

docs/content/manual/release-specific/v1.2.0/test_version_bump.md

Signed-off-by: David Ko <dko@suse.com>
https://github.com/longhorn/longhorn/issues/2757

Fix invalid test case YAML format

---

manager/integration/tests/test_csi_snapshotter.py

Longhorn/longhorn#2951
This PR is not enough for fixing the issue

integration: Fix the restore check function for csi snapshotter related tests

---

docs/content/manual/release-specific/v1.2.0/backup-creation-with-old-engine-image.md

https://github.com/longhorn/longhorn/issues/2949

Revert the Backup CR Ready state

---

docs/content/manual/pre-release/environment/cluster-using-customized-kubelet-root-directory.md

docs: Add a manual test 'cluster-using-customized-kubelet-root-directory'

---

secscan/Jenkinsfile
test_framework/Jenkinsfile

Modify default slack notification channel

---

docs/content/manual/pre-release/upgrade/backing-image-during-upgrade.md

Add a manual test 'System upgrade with the same backing image manager image'

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/2486

Implement test_multiple_volumes_creation_with_degraded_availability

---

secscan/Jenkinsfile
test_framework/Jenkinsfile

Reverts longhorn/longhorn-tests#694

Revert "Modify default slack notification channel"

---

secscan/Jenkinsfile
test_framework/Jenkinsfile

Reverts longhorn/longhorn-tests#695

Revert "[v1.1.3-backport] Modify default slack notification channel"

---

secscan/scripts/provision.sh

fix secscan ubuntu update lock

---

manager/integration/tests/test_kubernetes.py

Fix test_backup_kubernetes_status flakiness

---

docs/content/manual/pre-release/upgrade/upgrade-conflict-handling.md

This is to test upgrade on a large cluster having 100 volumes.

Modify the test case for large cluster

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/2967
I've not included the check for `ls -l` as per test skeleton because writing operation and reading operation are already there in the steps. So just avoided extra line of code
Fixed some flake8 checks warnings.
Signed-off-by: Khushboo fnu.khushboo@suse.com

Add fsGroup test

---

manager/integration/tests/test_settings.py

docs: Add test skeleton 'test_setting_concurrent_rebuild_limit'

---

manager/test_containers/build_test_images.sh

Signed-off-by: David Ko <dko@suse.com>

Remove needless virt image build in build_test-images.sh

---

manager/integration/tests/test_migration.py

integration: Add test skeletons for degraded volume live migration

---

manager/integration/tests/common.py
manager/integration/tests/test_migration.py
manager/integration/tests/test_settings.py

longhorn/longhorn#2805
longhorn/longhorn#2460

[Backport][v1.2.x] Migration and concurrent rebuilding feature test skeletons

---

manager/integration/tests/common.py
manager/integration/tests/test_migration.py

[Backport][v1.1.3] Migration test skeleton & engine image wait function fix

---

test_framework/terraform/aws/rhel/variables.tf
test_framework/terraform/aws/sles/variables.tf

https://github.com/longhorn/longhorn/issues/3045

upgrade test framework OS disto versions

---

docs/content/manual/pre-release/node/node-drain-deletion.md

Add command example for force drain manual test to help us remember how to test it in the future.

Add command example for force drain manual test

---

docs/content/manual/pre-release/node/physical-node-down.md

Update hyper link

---

docs/content/manual/pre-release/node/physical-node-down.md

Correct hyper link

---

docs/content/manual/pre-release/node/node-disconnection.md

Update out of date test steps in case 2

Update manual test case "node disconnection"

---

manager/integration/deploy/test_nfs.yaml
manager/integration/deploy/test_s3.yaml
manager/integration/tests/backupstore.py
test_framework/Jenkinsfile
test_framework/scripts/longhorn-setup.sh

https://github.com/longhorn/longhorn/issues/2999

Separate s3 and nfs test

---

manager/integration/tests/run.sh
secscan/scripts/secscan.sh
test_framework/scripts/cleanup.sh
test_framework/scripts/longhorn-setup.sh

Signed-off-by: Shatakshi <shatakshi.gupta85@gmail.com>
Related to Bugbash. Fixed [errors](https://lift.sonatype.com/result/longhorn/longhorn-tests/01FHW2V4T8A6NDXB3MCV0CPHGP?t=CustomTool%20%22Shellcheck%22%7CShellCheck) reported by sonatype lift.

Fix shellcheck errors

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

[Backport-v1.2.x] Implement test_multiple_volumes_creation_with_degraded_availability

---

manager/integration/tests/test_ha.py

[backport -v1.2x]Add test cases skeleton for im deletion

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

[backport v1.2.x]Add a new test test_aws_iam_role_arn

---

manager/integration/tests/common.py
manager/integration/tests/test_basic.py

[Backport v1.2.x] Add basic backup restore test case

---

manager/integration/tests/test_basic.py
manager/integration/tests/test_ha.py

[Backport v1.2.x] Fix back_listing failure

---

manager/integration/tests/test_basic.py

[Backport v1.2.x] Fix test_allow_volume_creation_with_degraded_availability_restore

---

manager/integration/tests/common.py

Backport https://github.com/longhorn/longhorn-tests/pull/777

[Backport v1.2.x ]Make nfs and s3 selection Jenkins parameterized

---

secscan/Jenkinsfile
test_framework/Jenkinsfile

Signed-off-by: David Ko <dko@suse.com>
(cherry picked from commit 76acfdfe21e5f1a26ac5cac587dc07bb95f1eff3)

Update the slack channel to notify the build results

---

manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn/issues/3195

Fix the disk_migration test

---

manager/integration/tests/test_node.py

https://github.com/longhorn/longhorn-tests/pull/773

[Backport v1.2.x ] Fix the disk_migration test

---

manager/integration/tests/common.py
test_framework/scripts/longhorn-setup.sh

Backport of https://github.com/longhorn/longhorn-tests/pull/786

[Backport v1.2.x] Fix backup store type handaling

---

manager/integration/tests/test_migration.py

integration: Add a test skeleton for restore volume migration

---

test_framework/scripts/longhorn-setup.sh

Fix the variable name for upgrade jobs.

Fix the upgrade test job typo

---

test_framework/scripts/longhorn-setup.sh

Backport https://github.com/longhorn/longhorn-tests/pull/792

[backport v1.2.x] Fix the uprade test job typo

---

manager/integration/tests/test_rwx.py

Backport https://github.com/longhorn/longhorn-tests/pull/791 to v1.1.3

[Backport v1.1.3] Install longhorn-nfs before all rwx cases

---

manager/integration/tests/test_rwx.py

Backport https://github.com/longhorn/longhorn-tests/pull/791 to v1.2.x

[Backport v1.2.x] Install longhorn-nfs before all rwx cases

---

test_framework/scripts/terraform-setup.sh

fix terraform setup script for nightly tests

---

test_framework/terraform/aws/centos/data.tf
test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/centos/output.tf
test_framework/terraform/aws/centos/user-data-scripts/provision_amd64.sh
test_framework/terraform/aws/centos/user-data-scripts/provision_arm64_agent.sh.tpl
test_framework/terraform/aws/centos/user-data-scripts/provision_arm64_server.sh.tpl
test_framework/terraform/aws/centos/variables.tf
test_framework/terraform/aws/oracle/data.tf
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/oracle/output.tf
test_framework/terraform/aws/oracle/user-data-scripts/provision_amd64.sh
test_framework/terraform/aws/oracle/user-data-scripts/provision_arm64_agent.sh.tpl
test_framework/terraform/aws/oracle/user-data-scripts/provision_arm64_server.sh.tpl
test_framework/terraform/aws/oracle/variables.tf
test_framework/terraform/aws/rockylinux/.terraform.lock.hcl
test_framework/terraform/aws/rockylinux/data.tf
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/rockylinux/output.tf
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_amd64.sh
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_arm64_agent.sh.tpl
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_arm64_server.sh.tpl
test_framework/terraform/aws/rockylinux/variables.tf

ref: https://github.com/longhorn/longhorn/issues/3085

Extend OS support matrix 

---

test_framework/scripts/cleanup.sh

fix terraform cleanup script

---

manager/integration/tests/common.py
manager/integration/tests/test_recurring_job.py

Backport https://github.com/longhorn/longhorn-tests/pull/794 to v1.2.x

[Backport 1.2.x] Recurring job start just after minute start

---

manager/integration/tests/test_node.py

Add test skeleton for test_disk_eviction_with_node_level_soft_anti_affinity_disabled

---

test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/ubuntu/main.tf

fix aws internet gateway dependency issue in terraform

---

manager/integration/tests/test_rwx.py

Backport https://github.com/longhorn/longhorn-tests/pull/807 to v1.2.x

[Backport 1.2.x] Check ds longhorn-nfs installed

---

manager/integration/tests/test_rwx.py

[Backport 1.1.3] Check ds longhorn-nfs installed

---

test_framework/scripts/longhorn-setup.sh

fix arm64 nightly tests

---

docs/content/manual/pre-release/ha/ha-volume-migration.md

docs: Add HA volume migration tests

---

manager/integration/tests/common.py

- Change from `complete` to `Completed`.
- Change from `in_progress` to `InProgress`.
https://github.com/longhorn/longhorn/issues/3309

The longhorn manager backend responses Backup CR state directly

---

manager/integration/tests/common.py

- Change from `complete` to `Completed`.
- Change from `in_progress` to `InProgress`.
https://github.com/longhorn/longhorn/issues/3312

[BACKPORT] The longhorn manager backend responses Backup CR state directly

---

manager/integration/tests/test_basic.py

The behavior changes after longhorn 3035.
Previous, the volume's backupStatus reflects the engine's backup status directly.
So, even the backup is completed, if we delete the corresponding replica, the
volume's backupStatus shows the engine's backup status with an error message.
Now, after longhorn 3035 was introduced, the volume's backupStatus reflects
the Backup CR status, not the engine's backup status anymore.
So, after the backup is completed, even we delete the corresponding replica,
the volume's backupStatus shows the Backup state is Completed.
We change the test case to during the backup creation in progress,
deletes the responsible replica to make the backup falls into Error
state and with an error message.
https://github.com/longhorn/longhorn/issues/3035

Fix test_backup_status_for_unavailable_replicas

---

manager/integration/tests/test_basic.py

The behavior changes after longhorn 3298.
Previous, the volume's backupStatus reflects the engine's backup status directly.
So, even the backup is completed, if we delete the corresponding replica, the
volume's backupStatus shows the engine's backup status with an error message.
Now, after longhorn 3298 was introduced, the volume's backupStatus reflects
the Backup CR status, not the engine's backup status anymore.
So, after the backup is completed, even we delete the corresponding replica,
the volume's backupStatus shows the Backup state is Completed.
We change the test case to during the backup creation in progress,
deletes the responsible replica to make the backup falls into Error
state and with an error message.
https://github.com/longhorn/longhorn/issues/3298

[BACKPORT] Fix test_backup_status_for_unavailable_replicas

---

test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/ubuntu/main.tf

[v1.1.3-backport] change aws key pair name to avoid potential naming conflict

---

docs/content/manual/release-specific/v1.2.3/test-scalability-with-backing-image.md

Longhorn/longhorn#3242
ref: https://github.com/longhorn/longhorn/issues/3242#issuecomment-984409310

docs: Add backing image related scalability test

---

manager/integration/tests/common.py

https://github.com/longhorn/longhorn/issues/3462
As the CRDs structure changed, the test condition needs be changed accordingly.
https://github.com/longhorn/longhorn/issues/2955

Change the condition check of engine

---

manager/integration/deploy/test.yaml

Update the test container image tag

Update the test container image tag

---

docs/content/manual/release-specific/v1.3.0/test-longhorn-manager-npe.md

doc: Add a test for the longhorn manager NPE issue

---

test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/ubuntu/main.tf

modify security group to allow udp connection for longhorn webhooks

---

test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/ubuntu/main.tf

 [fix] security group udp range 

---

manager/integration/tests/aws.py
manager/integration/tests/test_infra.py

[Backport v1.2.x]Let test_offline_node support k3s

[Backport v1.2.x]Let test_offline_node support k3s

---

docs/content/manual/pre-release/node/kubelet-restart-on-a-node.md
docs/content/manual/pre-release/node/node-drain-deletion.md

https://github.com/longhorn/longhorn/issues/2650
https://github.com/longhorn/longhorn/issues/3459

Update test docs after refactoring the instance manager lifecycle

---

test_framework/scripts/terraform-setup.sh

fix rke run command when k8s_distro_name is not rke

---

test_framework/scripts/longhorn-setup.sh

fix create_aws_secret in longhorn-setup script

---

test_framework/scripts/longhorn-setup.sh

[v1.2.x-backport] fix create_aws_secret in longhorn-setup script

---

test_framework/scripts/longhorn-setup.sh

[v1.1.3-backport]  fix create_aws_secret in longhorn-setup script

---

test_framework/scripts/longhorn-setup.sh

[v1.1.x-backport] fix create_aws_secret in longhorn-setup script

---

test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/ubuntu/main.tf
test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl

fix k3s node count ready condition

---

test_framework/terraform/aws/centos/main.tf
test_framework/terraform/aws/oracle/main.tf
test_framework/terraform/aws/rhel/main.tf
test_framework/terraform/aws/rockylinux/main.tf
test_framework/terraform/aws/sles/main.tf
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/ubuntu/main.tf

[v1.1.x-backport] fix nightly tests cluster not ready failures

---

scalability_test/README.md
scalability_test/script/monitor.py
scalability_test/script/scale-test.py
scalability_test/script/statefulset.yaml
scalability_test/terraform/data.tf
scalability_test/terraform/main.tf
scalability_test/terraform/user-data-scripts/provision_rke2_additional_server.sh.tpl
scalability_test/terraform/user-data-scripts/provision_rke2_agent.sh.tpl
scalability_test/terraform/user-data-scripts/provision_rke2_first_server.sh.tpl
scalability_test/terraform/variables.tf

Add script for scalability test

---

manager/integration/tests/common.py

Added print statement in case assertion failures identify the problems in our integration tests.

Add print statement with assert

---

docs/content/manual/release-specific/v1.3.0/test-longhorn-manager-starting-scalability.md

doc: Add a test for the longhorn manager starting and upgrade scalability issue

---

manager/integration/tests/test_rwx.py

Skipping the installation of the nfs in the test

Skip the nfs installation in the test

---

manager/integration/tests/common.py
manager/integration/tests/test_cloning.py

https://github.com/longhorn/longhorn/issues/2941
This is implementation of tests in the volume cloning module..
I did below modifications in the test skeleton:
1. Renamed test case name.
2. Previously cloning from attached and detached volume was part one test, now divided them in two.

Add volume cloning test

---

test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl

fix nightly tests issues

---

test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl

[v1.1.x-backport]  fix nightly tests issues

---

test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl
test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl
test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl

[v1.2.x-backport] fix nightly tests issues

---

manager/integration/deploy/backupstores/minio-backupstore.yaml

update minio version for backupstore

---

manager/integration/deploy/backupstores/minio-backupstore.yaml
manager/integration/deploy/stress.yml
manager/integration/deploy/test.yaml
manager/integration/tests/backupstore.py
manager/integration/tests/common.py

[v1.1.x-fix] update minio version and fix nightly tests choose backupstore type

---

manager/integration/deploy/backupstores/minio-backupstore.yaml

[v1.2.x-backport] update minio version for backupstore

---

manager/integration/tests/test_rwx.py

https://github.com/longhorn/longhorn-tests/pull/885

[Backport-v1.2.x] remove nfs installation

---

manager/integration/tests/test_rwx.py

https://github.com/longhorn/longhorn-tests/pull/885

[backport-v1.1.x] remove nfs-installation from test

---

manager/integration/tests/test_zone.py

https://github.com/longhorn/longhorn/issues/3663

[BACKPORT] Fix flaky test result for test_replica_auto_balance_zone_best_effort

---

manager/integration/tests/common.py
manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/3517
https://github.com/longhorn/longhorn/issues/3470

Fix test_recurring_jobs_allow_detached_volume & add more recurring job test cases

---

manager/integration/tests/common.py
manager/integration/tests/test_csi_snapshotter.py

From https://github.com/longhorn/longhorn/issues/3639
Add skeleton of CSI snapshot test cases

Add skeleton of CSI snapshot test case

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/3727

[BACKPORT][v1.1.x] Fix test_allow_volume_creation_with_degraded_availability_restore

---

manager/integration/tests/test_basic.py

https://github.com/longhorn/longhorn/issues/3728

[BACKPORT][v1.2.x] Fix test_allow_volume_creation_with_degraded_availability_restore

---

docs/content/manual/release-specific/v1.3.0/extend_CSI_snapshot_support.md

From https://github.com/longhorn/longhorn/issues/3639
Transfer CSI snapshot test steps from github [comment](https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714) to manual test doc
cc @PhanLe1010

Transfer CSI snapshot test steps from github comment to test doc

---

manager/integration/tests/common.py
manager/integration/tests/test_recurring_job.py

https://github.com/longhorn/longhorn/issues/3732

[BACKPORT][v1.2.x] Recurring job test case fixes

---

test_framework/Jenkinsfile

remove Jenkinsfile extra qoute typo

---

test_framework/scripts/download-support-bundle.sh

fix missing kubeconfig env setup

---

test_framework/Jenkinsfile

fix support bundle location
