- environment-setup/Dockerfile
- environment-setup/Makefile
- environment-setup/README.md
- environment-setup/common.py
- environment-setup/packet-cloud-config
- environment-setup/setupRancher.py
- environment-setup/startup-nfs-script.sh
- environment-setup/startup-script.sh
- environment-setup/teardownRancher.py
@yasker @sangeethah
python scripts for setting up GCE VMs and Packet hosts: setupRancher.py and teardownRancher.py running in a container from docker image jimeng/longhorn-test:01
Jenkins jobs using the scripts: http://jenkins-poc.rancher.io:8080/job/test_longhorn_driver/
and also a quick cleanup job: http://jenkins-poc.rancher.io:8080/view/storage/job/test_longhorn_teardown/
> setup rancher and NFS GCE servers and register 3 Packet hosts

- manager/integration/tests/common.py
- manager/integration/tests/conftest.py
- manager/integration/tests/test_engine_upgrade.py
Use `--engine-upgrade-image` option to enable the test. Must prepare one
additional image beforehand.
> manager: Add offline engine upgrade test

- manager/integration/tests/conftest.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_recurring_job.py
Use `--enable-recurring-job-test` to enable the test.
It will take more than 10 minutes, so it's disabled by default.
> manager: Add back recurring job test

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
If volume/engine image already gone, don't error out.
> manager: Fix test cleanup engine image and volume

- manager/integration/deploy/test.yaml
Match longhorn-manager 885b53acb7518935546587bfcf3fc7a077fde415
Notice that the deployment method changed. See README.md for details.
> manager: update image to rancher/longhorn-manager-test:1d5584f

- manager/integration/deploy/test.yaml
- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Issue: https://github.com/rancher/longhorn-tests/issues/21
Positive case :
```
ubuntu@ip-172-31-7-79:~/langs/golang/src/github.com/rancher/longhorn-tests/manager/integration$ kubectl logs -f longhorn-test
+ flake8 .
+ py.test -v -s -k test_basic .
============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-2.9.2, py-1.5.3, pluggy-0.3.1 -- /usr/local/bin/python
cachedir: .cache
rootdir: /integration/tests, inifile:
collecting ... collected 17 items
test_basic.py::test_hosts_and_settings PASSED
test_basic.py::test_volume_basic PASSED
test_basic.py::test_volume_iscsi_basic PASSED
test_basic.py::test_snapshot PASSED
test_basic.py::test_backup PASSED
test_basic.py::test_volume_multinode PASSED
==================== 11 tests …
```
> manager: Pump in data for the integration test

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_ha.py
This PR modifies tests to write data into the volume blockdevice for the remaining integration tests that have not implemented this yet (`test_engine_upgrade.py` and `test_ha.py`). Additionally, the `write_random_data` and `check_data` functions have been added to `common.py` to use for these tests.
This PR resolves #21.
> Write data to volumes in integration tests

- manager/integration/deploy/test.yaml
Matching longhorn-manager: rancher/longhorn-manager:d5227ec
From:
commit 98dd3f8fb20ad86e95fbd0429932f015c8c0b7c6
Date:   Fri Jul 6 19:27:42 2018 -0700
Update images
Manager: rancher/longhorn-manager:d5227ec
UI: rancher/longhorn-ui:436d961
Flexvolume driver has been updated. Need to redeploy for the testing.
> manager: Update image to rancher/longhorn-manager-test:3810afb

- manager/integration/tests/test_csi.py
Should use the right storageclass name.
```
+ flake8 .
+ py.test -v . -x -s -k test_csi --enable-csi-test
============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-2.9.2, py-1.5.4, pluggy-0.3.1 -- /usr/local/bin/python
cachedir: .cache
rootdir: /integration/tests, inifile:
collecting ... collected 22 items
test_csi.py::test_csi_volume_mount PASSED
test_csi.py::test_csi_volume_io PASSED
===================== 20 tests deselected by '-ktest_csi' ======================
================== 2 passed, 20 deselected in 280.69 seconds ===================
```
> Fix csi test bug

- manager/integration/tests/conftest.py
- manager/integration/tests/test_flexvolume.py
Wait for https://github.com/rancher/longhorn-tests/issues/61 to be resolved.
For now we can only run test on Kubernetes v1.10
> manager: Disable flexvolume test temporaily

- manager/integration/tests/common.py
- manager/integration/tests/test_csi.py
- manager/integration/tests/test_flexvolume.py
- manager/integration/tests/test_provisioner.py
The volume will only be detached after pod is gone. So we don't want to count
the time of pod shutting down into the volume detaching.
> manager: Update delete_pod to delete_and_wait_pod()

- manager/integration/deploy/test.yaml
- manager/integration/tests/common.py
- manager/integration/tests/test_provisioner.py
- manager/integration/tests/test_statefulset.py
This PR adds very basic tests to make sure that Longhorn properly integrates with StatefulSets in Kubernetes. The tests make sure that Longhorn volumes used in StatefulSets:
- Mount properly and scale to the correct amount
- Can be scaled up to provision more volumes
- Can be properly backed up and can run recurring backups through Longhorn
This PR implements the first three tests requested in #55. However, the fourth point (restoring into a PVC to be used in a StatefulSet) still needs to be resolved in a separate commit.
> Add basic StatefulSet tests

- manager/integration/tests/common.py
- manager/integration/tests/test_csi.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_flexvolume.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_provisioner.py
- manager/integration/tests/test_statefulset.py
This PR introduces a new fixture called `client` that returns a single client instance rather than multiple of them. This solves the issue of many of the tests using `clients` but only requiring one `client` and needing to use the same `for` block to remedy for it.
Tests that use one `client` now use this fixture and have had the associated `for` statements removed. `clients` has been renamed to `clis` to prevent confusion, and the tests still using this fixture have been modified accordingly. Some tests require a host_id despite using one client, and since `client` doesn't return a host_id, those tests will still be using `clis`.
This PR resolves #75.
> Add single client fixture

- manager/integration/tests/common.py
- manager/integration/tests/test_statefulset.py
This PR implements the last test requested in #55, which backs up a StatefulSet, creates a new set of volumes to be used for the StatefulSet, and then confirms that the volumes hold their existing data in a new StatefulSet.
To support this new test, part of the common functions have been rewritten:
- `delete_and_wait_pod` now calls a separate `wait_pod` function that is also used by the `statefulset` fixture teardown procedure.
- The `statefulset` fixture teardown now waits on the `PersistentVolume` to see if it will enter a `Failed` state (expected of manually created volumes) and tear those volumes down manually rather than timing out and causing an error.
- The `statefulset` fixture teardown now calls `delete_and_wait_statefulset`, a function that is also used by the …
> Add StatefulSet restore test

- manager/integration/tests/conftest.py
- manager/integration/tests/test_node.py
It has high failure rate right now due to API server issues.
Use `--enable-node-test` option to enable the test.
> manager: disable node test by default

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_ha.py
This PR adds four new functions in order to verify volume checksums in tests:
- `write_device_rdata`
- `check_device_data`
- `write_volume_rdata`
- `check_volume_data`
These functions will check both write data at a specific position (which we were already checking) and verify the checksum of the volume. This allows us to confirm that data is properly written to the volume (write data) and that the volume properly maintains its state in its entirety (checksum).
The tests that rely on this data verification right now (`test_basic.py`, `test_engine_upgrade.py`, and `test_ha.py`) have been modified to use these new functions.
The old `write_random_data` and `check_data` methods have been removed in favor of these new methods.
This PR resolves rancher/longhorn#147.
> Verify volume checksums in tests

- manager/integration/deploy/test.yaml
Matches manager:
commit 04de3c050450e969486119943349eb1a01fc1f52
Date:   Fri Aug 3 17:11:20 2018 -0700
Update images
Manager to rancher/longhorn-manager:bdc22c1
Engine to rancher/longhorn-engine:74ac39a
Backup/restore with base image support added
> Update image to rancher/longhorn-manager-test:1b8c791

- manager/integration/tests/common.py
- manager/integration/tests/test_csi.py
This PR adds a `StorageClass` reference to the `PersistentVolumes` and `PersistentVolumeClaims` in `test_csi.py`. This helps work around issues on some platforms such as GKE where a `StorageClass` name is expected or it attempts to use the default, causing the test to fail.
As a result of this, checking for provisioned volumes using the `storageClassName` field no longer works in `PersistentVolumeClaims`. The `pvc` finalizer has been modified to instead check for the `volume.beta.kubernetes.io/storage-provisioner` annotation to check for provisioned volumes.
This PR resolves rancher/longhorn#165.
> Add StorageClass references to CSI tests

- manager/integration/tests/test_node.py
Fixed finalizer error log after running umount disk test case
```
---------------------------- Captured stdout setup -----------------------------
Exception when cleanup host disk vol-disk-1 Command '['umount', '/tmp/longhorn-test/vol-disk-1']' returned non-zero exit status 32
```
> add clean disk after test umount case

- manager/integration/tests/common.py
- manager/integration/tests/test_node.py
- After delete replica, still need some time to wait for storageScheduled value update.
- By default, longhorn reserved 30% space for root disks, test finalizer also need to reset reserved value for each root disk.
> update tests with backend

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_scheduling.py
This PR adds tests for longhorn/longhorn-manager#308, which implements a "Replica Hard Anti-Affinity" setting for `Longhorn`. Both tests will attempt to spin up a typical `volume` with 3 `replicas` before disabling scheduling on the test pod's node and removing the replica on that node. 
In the first case, `test_soft_anti_affinity`, `Longhorn` should be able to schedule a new `replica` and get the `volume` status to `Healthy` again. In the second case `test_hard_anti_affinity`, the `replica` should not be scheduled, and the `volume` status should remain at `Degraded`.
> Add tests for "Replica Hard Anti-Affinity" setting

- manager/integration/tests/common.py
- manager/integration/tests/test_flexvolume.py
- manager/integration/tests/test_provisioner.py
- manager/integration/tests/test_scheduling.py
- manager/integration/tests/test_tagging.py
This PR adds integration tests for the `Disk` and `Node` tagging functionality introduced in longhorn/longhorn-manager#315. The tests do a number of things:
1. Ensure `Tags` are properly sent to the server.
2. Ensure `Tags` are properly validated and reordered when updated.
3. Ensure that new `Volumes` are scheduled properly based on the `Tag` rules.
4. Ensure that `Volumes` can be scheduled after a failure once a `Node` or `Disk` receives the appropriate tags.
5. Ensure that the `nodeSelector` and `diskSelector` parameters are usable through a Kubernetes provisioned `Volume`.
These tests depend on a default set of `Tags` titled `DEFAULT_TAGS` that is set up as a fixture before some of the tests are run due how specific some of the tests are to make sure scheduling is working properly. …
> Add tests for Disk and Node tagging

- manager/integration/deploy/test.yaml
I think it's better to use `master` tag to deploy `longhorn-manager-test` image, since it will be updated on every merge, and it will be ideal for test_framework to use.
> manager: Update deployment to longhornio/longhorn-manager-test:master

- manager/integration/tests/test_scheduling.py
This PR handles the naming change to the now `Replica Soft Anti-Affinity Setting` and changes the values of this `Setting` set in the tests to make sure the tests still function properly in response to longhorn/longhorn-manager#327.
> Flip Anti-Affinity Setting in scheduler tests

- manager/integration/deploy/test.yaml
- manager/integration/tests/test_node.py
This PR adds a test for the `Setting: Create Default Disk on Labeled Nodes` that was implemented in longhorn/longhorn-manager#331. The test will check three different cases for when this `Setting` is enabled:
1. A `Disk` already exists on the `Node`. No additional `Disk` should be created.
2. A `Disk` doesn't exist on the `Node`, and the `Node` is labeled properly. The default `Disk` should be created at the path specified in `Setting: Default Data Path`.
3. A `Disk` doesn't exist on the `Node`, but the `Node` doesn't have the appropriate label. The default `Disk` should not be created.
Note that since additional permissions are needed to label the `Nodes` in this test, the `ClusterRole` created for the test has been modified accordingly.
This PR also contains a commit to set the …
> Add test for CreateDefaultDisk Setting

- manager/integration/tests/common.py
- manager/integration/tests/test_base_image.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_kubernetes.py
- manager/integration/tests/test_recurring_job.py
This PR adds tests for the ability to add `Labels` to `Backups`, a feature that was requested in longhorn/longhorn#563 and implemented in longhorn/longhorn-manager#335. There are a total of six tests implemented by this PR. These are the base four:
- `test_backup_labels`: Tests that creating a `Backup` applies the `Labels` specified by the user.
- `test_backup_kubernetes_status`: Tests that the `KubernetesStatus` is set and restored properly when a user creates a `Backup`.
- `test_recurring_job_labels`: Tests that a `RecurringJob` applies user specified `Labels` and the appropriate `Label: RecurringJob`.
- `test_recurring_job_kubernetes_status`: Tests that a `RecurringJob` properly stores the latest `KubernetesStatus`.
Additionally, two tests have `BaseImage` variants to ensure that the …
> Add tests for labeling Backups

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
The following code changes adds two things:
1. Adds a way to check the restoration progress percentage
2. Fixes the issue where snapshot revert was getting executed when the volume frontend is attached
> Restore Progress and Snapshot revert

- manager/integration/tests/test_node.py
This PR modifies the `test_node_default_disk_labeled` test to delete the created custom `Disk` during the test so that the `Node` can have the `Default Disk` restored to the `Node` as part of the test cleanup. Previously, this `Disk` would persist after the test and would be used in all later tests.
> Cleanup custom Disk path after default Disk test

- manager/integration/tests/common.py
- manager/integration/tests/test_node.py
After the longhorn refactor, this case was failing as Linux throws error
when the test case was trying to unmount the mount path when an active
volume has a replica running and storing meta files in this mount path.
The following code changes fixes it using -l flag to accomplish the
motive that the test case was trying to achieve.
> Fixing unmount delete test failure

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
This PR modifies the logic of the `snapshotPurge` calls in the `integration tests` to wait for the `SnapshotPurge` operation on the `SyncAgentServer` to complete before attempting to proceed and running the rest of the test's operations.
This PR modifies the tests to handle the new `asynchronous` version of the `SnapshotPurge` operation as described in longhorn/longhorn#665.
> Wait for Snapshot purge completion in tests

- manager/integration/deploy/test.yaml
- manager/integration/tests/test_basic.py
longhorn/longhorn#680
- allow test pod to get pvc status
- fix missing fixtures imports
- remove delete_and_wait_pvc & delete_and_wait_pv
since it will not be deleted before pods get deleted first
> fix fromBackup StorageClass & PV creation test

- manager/integration/tests/test_toleration_setting.py
Now semicolon rather than comma is used as the separator.
> Update setting values for test_toleration_setting()

- manager/integration/Dockerfile
- manager/integration/deploy/stress.yml
- manager/integration/tests/common.py
- manager/integration/tests/conftest.py
- manager/integration/tests/test_stress.py
**Updated**
longhorn/longhorn#679
Stress test actions:
1 - Create Longhorn volume, pv, pvc and a pod.
2- Write random data with size **1 GB** to the volume, Validate the data and Make a snapshot (x2)
3- Overwrite written data and Make a snapshot.
4- Delete/purge snapshot (random)
5- Choose 3 random actions from:
- Write random data with size 1 GB
- Delete data
- Create a snapshot
- Delete random snapshot / purge the snapshot randomly.
> Add stress test

- manager/integration/deploy/stress.yml
- manager/integration/deploy/test.yaml
- manager/integration/tests/common.py
Sometimes the endpoint is empty when the volume is healthy. We think
it's due to the delay caused by etcd while fetching the engine object in
the backend.
Workaround the issue by checking to make sure the endpoint is not empty
before proceed.
See the issue for details.
https://github.com/longhorn/longhorn/issues/707
> manager: waiting for the volume endpoint

- manager/integration/tests/test_stress.py
Stress test job pods gets evicted due to
`The node was low on resource: ephemeral-storage.`
This error is due to datafiles generated with random data used in stress test was consuming the node disk space.
> remove random datafile at stress test pod exit

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
There is no assertion after waiting for the endpoint of dr volumes hence the test won't error out. But we need to fix it to avoid meaningless waiting.
> Avoid checking endpoint for disaster recovery volumes

- manager/integration/tests/common.py
Error message from integration test:
```
Error Message
test setup failure
Stacktrace
>   request.addfinalizer(lambda: cleanup_client(client))
common.py:950: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:1004: in cleanup_client
reset_engine_image(client)
common.py:1986: in reset_engine_image
wait_for_engine_image_deletion(ei['name'], core_api, client)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
client = 'ei-a126797d'
core_api = <function get_core_api_client at 0x7f06e4e52320>
engine_image_name = <longhorn.Client object at 0x7f06e4536f10>
def wait_for_engine_image_deletion(client, core_api, engine_image_name):
deleted = False
for i in range(RETRY_COUNTS):
time.sleep(RETRY_INTERVAL)
deleted = True
> …
```
> manager: Fix the wrong usage of wait_for_engine_image_deletion()

- manager/integration/tests/test_basic.py
`initialRestorationRequired` is unset after the `lastBackup` changed, so
only watch for `lastBackup` may result in premature exit from the check
loop.
> manager: Fix test_restore_inc

- manager/integration/tests/longhorn.py
Somehow python 3 doesn't use __len__() for len(obj) call. It might
failed to register the function due to invoking __getattr__().
> longhorn.py: Update __len__()

- manager/integration/tests/test_toleration_setting.py
Check engine image state ready before attaching volume to node.
> fix toleration settings test

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
Right now there is a simpler way to trigger replica rebuild failure
without retry, since we can directly find out the replica which
sends data to the rebuilding replica and crash it.
https://github.com/longhorn/longhorn/issues/1167
> Improve test_rebuild_failure_with_intensive_data()

- test_framework/Jenkinsfile
- test_framework/scripts/longhorn-setup.sh
Reverts longhorn/longhorn-tests#294
Due to build failure.
> Revert "add option to include infra tests"

- test_framework/scripts/longhorn-setup.sh
Upgrade test console log:
```
+ '[[' true '=~' '[Tt]rue' ]]
ash: =~: unknown operand
```
> use explicit check instead of regex match

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
This test is used to make sure that we do not try to get the backup 
status from unavailable replicas. This could lead to the engine backup 
status retrieval process exceeding the maximum allowed time, after which
the manager would terminate that process. Since we wouldn't be able to
retrieve updated backup statuses we could no longer show new backups in
the frontend.
longhorn/longhorn#1230
> Add backup status test for unavailable replicas

- test_framework/Jenkinsfile
- test_framework/scripts/rke-setup.sh
- test_framework/terraform/digitalocean/do.tf
Offline node test cases using instance name to identify instance ID
on cloud provider, using same instance names in both nightly test jobs
w/o upgrade caused offline node test to accidentally shut down other job
instances causing unexpected job failure.
> test framework: use job name as instance name

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
This verifies that we can list other backups and also return error
messages for missing or corrupted backups.
longhorn/longhorn#1212
> Add integration test for corrupted S3 backup configs

- manager/integration/tests/test_node.py
This test case is to cover zone anti-affinity.
zone hard anti-affinity means the scheduler should not schedule replica on the same zone
zone soft anti-affinity means the scheduler can schedule replica on the same zone
https://github.com/longhorn/longhorn/issues/1052
> scheduler: Test case for zone anti-affinity

- manager/integration/tests/test_node.py
This test covers the replica scheduler should be able to schedule replica on cordoned node when this setting is set to false.
And the replica scheduler should not schedule replica on cordoned node when this setting is set to true.
> test: Add test case description for "Disable Scheduling On Cordoned Node" setting

- manager/integration/tests/test_node.py
This test case is to cover adding default disk back when the extra disk is unmounted
Since the extra disk will show the same filesystem ID as the default disk
when it is unmounted.
https://github.com/longhorn/longhorn/issues/1291
> controller: Test case skeleton for adding default disk back when extra disk is unmounted

- manager/integration/tests/test_csi.py
The backup completion check has a longer timeout and is actually the
intended behavior since it doesn't make sense to proceed with
restoration of a in progress backup.
longhorn/longhorn#820
> Wait for csi backup completion before trying to find the backup

- manager/integration/tests/common.py
- manager/integration/tests/test_statefulset.py
This is to update the csi driver name to 'driver.longhorn.io'.
We introduce this driver name in the following issue number:
https://github.com/longhorn/longhorn/issues/347
And we are going to remove the old csi driver name in the following issue number:
https://github.com/longhorn/longhorn/issues/1365
> csi: Change driver name to 'driver.longhorn.io'

- manager/integration/tests/test_ha.py
Longhorn/Longhorn#1260
Restored volume replica rebuild might happen while we wait for pod to be running, the fix is to check for volume transition state (degraded) before check pod permanent state (running)  
> fix test_single_replica_restore_failure

- manager/integration/tests/test_basic.py
We want to make sure that we only delete non referenced backup blocks,
we also don't want to delete blocks while there other backups in progress.
The reason for this is that we don't yet know which blocks are required by
the in progress backup, so blocks deletion could lead to a faulty backup.
> Add skeleton for backup block deletion test

- manager/integration/tests/test_basic.py
We want to make sure that an error when listing a single backup volume
does not stop us from listing all the other backup volumes. Otherwise a
single faulty backup can block the retrieval of all known backup volumes.
longhorn/longhorn#1410
> Add skeleton for backup volume list test

- manager/integration/tests/test_basic.py
We want to be able to delete the metadata (.cfg) files, even if they are
corrupt or in a bad state (missing volume.cfg).
Longhorn #1213
> Add skeleton for backup metadata deletion

- manager/integration/tests/test_basic.py
Instead of erroring the backup list should ignore the badly named files.
And return all the good files.
longhorn/longhorn#1410
depends on longhorn/backupstore#42
> Update skeleton for backup list test

- manager/integration/deploy/test.yaml
This PR adds `Priority Classes` to the set of resources accessible by the `longhorn-manager` integration tests via the `Cluster Role` that it uses. This fixes the issue where the `Priority Class` tests would fail due to not having the correct permissions for creating and deleting `Priority Classes`.
> Add Priority Class to test deploy

- manager/integration/tests/test_basic.py
This test case is to cover creating DRV option is valid
when the latest backup of a volume is deleted
https://github.com/longhorn/longhorn/issues/1381
> backupstore: Test case skeleton for validation creating DRV option

- manager/integration/tests/test_kubernetes.py
This PR adds tests for special `Volume` deletion cases that involve deletion of `Kubernetes` resources such as `Persistent Volumes` and `Persistent Volume Claims` as described in longhorn/longhorn#520. Specifically, the following deletion cases are tested and should work:
- A `Volume` has a static `Persistent Volume` (and possibly `Persistent Volume Claim`) associated with it.
- A `Volume` has a dynamically provisioned `Persistent Volume` and `Persistent Volume Claim` associated with it.
- A `Volume` is deleted as a result of deletion of a dynamically provisioned `Persistent Volume` and `Persistent Volume Claim`.
The standard deletion case without cleanup should already be handled by `test_volume_basic`.
> Add tests for Volume deletion handling

- manager/integration/tests/test_basic.py
Due to fix in #1381, after deleting the last backup, if there is any
backup for the volume, it will update the last backup with the latest
one.
In this test case, after deleting backup number 2, the last backup will be
backup number 1
The last backup is empty case covers the fix for issue [1381](https://github.com/longhorn/longhorn/issues/1381)
https://github.com/longhorn/longhorn/issues/1381
https://github.com/longhorn/longhorn/issues/1572
> tests: fix test case test_dr_volume_with_last_backup_deletion failure

- README.md
This PR updates the `README.md` such that it now contains instructions regarding how to edit the manual test cases that are stored under `website/content/manual/` and accessible [here](https://longhorn.github.io/longhorn-tests).
Note that these instructions only contain information on editing and previewing the manual tests. I've left out the instructions on how to rebuild the website since we plan on automatically building the docs via GitHub Actions.
> Add instructions for manual test cases

- .github/workflows/publish.yml
This PR adds a GitHub Actions workflow that will run on every push to the `master` branch in order to generate the `pdoc` documentation for the `longhorn-manager` integration tests and rebuild the Hugo website for deployment under `docs/` as requested in longhorn/longhorn#1588.
> Add workflow for publishing test docs

- manager/integration/tests/backupstore.py
- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_csi.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_kubernetes.py
Since both deletion operations are async we need to always wait for
completion of the requested operation before proceeding with our tests.
longhorn/longhorn#710
longhorn/longhorn#1603
longhorn/longhorn#1604
> Refactor test to always use backup_delete / backup_volume_delete

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_upgrade.py
Replaced the create_pv_for_volume and create_pvc_for_volume in method 'prepare_pod_with_data_in_mb'.
Identified few more cases where 'create_pv_for_volume' and 'create_pvc_for_volume' are used(not straight though). Will change them too if this approach is right.
https://github.com/longhorn/longhorn/issues/1462
> Replace create_pv_for_volume and create_pvc_for_volume with fixture

- secscan/Jenkinsfile
- test_framework/Jenkinsfile
Migrating Jenkins jobs to folders caused test docker images build to fail.
> Use JOB_BASE_NAME instead of JOB_NAME in Jenkins jobs

- secscan/scripts/build.sh
- test_framework/scripts/build.sh
> Use JOB_BASE_NAME instead of JOB_NAME in build scripts

- docs/content/manual/pre-release/upgrade/upgrade-conflict-handling.md
This tests the fix for upgrade failing due to conflict as described in
longhorn/longhorn#1646
> docs: add manual test for upgrade failing due to conflict

- manager/integration/tests/test_ha.py
This test case is to cover replic rebuild should be triggered if replica
has any crashes
https://github.com/longhorn/longhorn/issues/1615
> Add replica rebuild test skeleton for replica crashes

- manager/integration/deploy/test.yaml
Longhorn test pod doesn't have access to the following resources (rolebindings, roles, podsecuritypolicies) which affects `test_upgrade`
```
Resource: "policy/v1beta1, Resource=podsecuritypolicies", GroupVersionKind: "policy/v1beta1, Kind=PodSecurityPolicy"
Name: "longhorn-psp", Namespace: ""
Object: &{map["apiVersion":"policy/v1beta1" "kind":"PodSecurityPolicy" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":"longhorn-psp"] "spec":map["allowPrivilegeEscalation":%!q(bool=true) "allowedCapabilities":["SYS_ADMIN"] "fsGroup":map["rule":"RunAsAny"] "hostIPC":%!q(bool=false) "hostNetwork":%!q(bool=false) "hostPID":%!q(bool=true) "privileged":%!q(bool=true) "requiredDropCapabilities":["NET_RAW"] "runAsUser":map["rule":"RunAsAny"] …
```
> update test pod clusterrole resources

- manager/integration/tests/test_ha.py
need to wait for pod restart before checking for Longhorn volume re-mounted
fix affect the following tests
- test_salvage_auto_crash_replicas_short_wait
- test_salvage_auto_crash_replicas_long_wait
[failed test log](https://ci.longhorn.io/job/public/job/longhorn-upgrade-tests/66/testReport/junit/tests/test_ha/test_salvage_auto_crash_replicas_short_wait/)
> fix race condition for autosalvage tests

- manager/integration/tests/test_node.py
After [Longhorn #1679](https://github.com/longhorn/longhorn/issues/1679) cleanup replicas fix, the failed to scheduled
replica will be cleaned up automatically, no need for manually cleanup.
https://github.com/longhorn/longhorn/issues/298
> Update test skeleton for node eviction

- test_framework/Jenkinsfile
- test_framework/scripts/longhorn-setup.sh
This change introduce the ability to specify different images for Longhorn components for running integration tests.
This change is introduced to be able to verify changes that likely to cause regressions in integration tests.
> test framework: add ability to customize deployment images

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
https://github.com/longhorn/longhorn/issues/1721
The timeout for waiting for backup to be created successfully is increased to 10 mins from 5 mins as backup creation takes ~8 mins to complete if the data size is about 800 Mi.
> Increase timeout for big backup creation

- manager/integration/tests/backupstore.py
- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_kubernetes.py
There where issues in the test code
- we where not waiting for the backup deletion during the backup_list test
- we where trying to find the backup before waiting for the backup completion in the create_backup function
- there is a couple of spots where we call find_backup but where not waiting for backup completion, since the backup.cfg only shows up once the backup is completed this would not work correctly all the time and introduce timing dependent flaky test behavior.
Since backup operations needs to be thought of as async, we always need to wait for completion of the backup operation. We do this in the utility functions delete_backup, create_backup, etc.
This is only tangentially related to the backup locks longhorn/longhorn#612
> Cleanup backup related test code

- manager/integration/tests/backupstore.py
- manager/integration/tests/test_ha.py
since we crash the replica that initiated the restore it's backupstore
lock will still be present, so we need to wait till the lock is expired,
before we can delete the backups.
longhorn/longhorn#612
> Wait for lock expiration in the restore crash tests

- manager/integration/tests/common.py
The PV may be already deleted before calling the finalizer, hence
we cannot use the wait function to find out the PV.
> Fix a BUG related to the PV cleanup in pod_make()

- manager/integration/tests/test_recurring_job.py
- manager/integration/tests/test_statefulset.py
We changed the recurring jobs' logic: recurring jobs only take backup/snapshot when the volume has new data since the last backup/snapshot. Therefore, we need to update recurring job integration tests.
Now we can control precisely when recurring snapshot/backup will happen . As the result, this PR fixes longhorn/longhorn#1354 as a side affect
Related issues:
longhorn/longhorn#1858
longhorn/longhorn#1354
> Fix recurring job integration tests

- manager/integration/tests/common.py
Missing wait times between retries.
> Add wait time between retries

- manager/integration/tests/test_node.py
There is no guaranty the testing cluster OS has the root and home directories setup to the same filesystem, for example, when OS has both as btrfs subvolumes.
To avoid test failure in such a case, it would be reasonable to stick to paths created by Longhorn.
> Fix for test failure when root and home directory are on different filesystem

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn/issues/612
Added tests for backup locks and fixed a few flake8 errors in the test_basic.py file.
> Add tests for backup-lock

- manager/integration/README.md
In case forget, this seems required by test_rwx_*.
> Add step to deploy NFS provisioner setup dependencies in README

- manager/integration/tests/test_basic.py
This is a fix for https://ci.longhorn.io/job/public/job/longhorn-tests/127/testReport/tests/test_basic/test_backup_lock_deletion_during_restoration/
It looks like in the nightly test environment the restore from a back got completed quickly even before the deletion of the same backup could initiate. So, increased the data backup size from 100 MB to 300 MB and deleted extra wait.
> Fix the test failure for backup lock

- manager/integration/tests/common.py
Otherwise it will cause multiple test failures.
> manager: Disable allow-volume-creation-with-degraded-availability by default

- manager/integration/tests/test_engine_upgrade.py
This change was introduced for the purpose to detect fault at an earlier stage. However, seems replica will be reused and if missed to detect the state change fails the test unwantedly. Remove to ensure not to interfere with the CI tests.
https://github.com/longhorn/longhorn-tests/pull/446#discussion_r512307176
https://ci.longhorn.io/job/public/job/longhorn-tests/141/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade_with_intensive_data_writing/
> Remove degrade and rebuild checks in test_engine_live_upgrade_with_intensive_data_writing

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
* Add check for engine image ref count since replicas might take time to delete.
* remove duplicated engine-image removal that is already handled in reset_engine_image.
* remove redundant cleanup for test_engine_live_upgrade_with_intensive_data_writing.
> Fix engine-image cleanup

- manager/integration/tests/test_ha.py
It is hard to capture the pending state of the workload pod. Moreover, we only need to make sure that the pod is in `running` state and `wait_for_pod_remount()` returns true. That is enough to conclude that the pod was restarted and the volume was remount. Therefore, we removed the `wait_for_pod_phase(core_api, pod_name, pod_phase="Pending")`
After this PR is merged, this test case sometimes still fails because of the issue https://github.com/longhorn/longhorn/issues/1942
longhorn/longhorn#1914
> Fix test_salvage_auto_crash_all_replicas test case

- manager/integration/tests/test_ha.py
Without checking for the intermediate phase could potentially miss the pod restart, try-except to allow enough time for K8s to handle the pod deletion.
https://github.com/longhorn/longhorn-tests/pull/464
> Try except the pod restart intermediate phase

- manager/integration/tests/common.py
- manager/integration/tests/test_node.py
* Split test case into different scenarios.
* Removed intermediate state check. 
* Fix test failure when k8s decided to relocate replicas one time only during anti-affinity node eviction.
* Fix test fails when relocated to the wrong node due to a missing node eviction.
> Enhance and fix unstable test result from test_node_eviction

- manager/integration/tests/test_engine_upgrade.py
~Refresh volume object and clean before detached by pod.~
Remove cleanups since already handled by the finalizer.
https://ci.longhorn.io/job/public/job/longhorn-tests/148/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade_with_intensive_data_writing/
> Fix test_engine_live_upgrade_with_intensive_data_writing

- manager/integration/tests/test_ha.py
Use StatefulSet instead to address the remount logic.
Also renamed wait_pod_for_auto_salvage to better reflect on the underlying logic.
https://github.com/longhorn/longhorn/issues/1914
> Fix test_volume_reattach_after_engine_sigkill

- manager/integration/tests/test_recurring_job.py
> Add test skeleton for: volume remains attaching to the wrong node during a recurring backup

- manager/integration/tests/test_settings.py
Remove the check for toleration with key contains `kubernetes.io` since we allow user to set this tolerations now
longhorn/longhorn#1874
> Fix test_setting_toleration to allow user to set any toleration

- manager/integration/tests/test_settings.py
The special toleration `:` makes Longhorn deploy manager pods on control/etcd nodes and when the test clears the toleration the control/etcd nodes become "down" in the Longhorn system. The result is that Longhorn has 4 nodes with 1 failed node. This breaks other test cases.
We will re-enable this special toleration once we implement the logic for deleting failed nodes
longhorn/longhorn#2024
> Remove the special toleration that tolerates everything from the test case test_setting_toleration_extra

- test_framework/terraform/aws/user-data-scripts/provision_amd64.sh
- test_framework/terraform/aws/user-data-scripts/provision_arm64_agent.sh.tpl
- test_framework/terraform/aws/user-data-scripts/provision_arm64_server.sh.tpl
RWX tests requires nfs-common package to be installed on the instance
> test framework: install nfs-common package

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_kubernetes.py
The `test_auto_remount_with_subpath` sometime fails. Make some modifications:
1. I think we don't need data locality in this test since it doesn't make any impact. 
1. Fixed some timing issues.
longhorn/longhorn#1719
> Fix: test_auto_remount_with_subpath test case

- manager/integration/tests/test_recurring_job.py
https://github.com/longhorn/longhorn/issues/2158
The `client` fixture should be used for these tests.
Fixed some flake8 checks also.
> Fix test_recurring_job tests failures

- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_kubernetes.py
- manager/integration/tests/test_node.py
- manager/integration/tests/test_recurring_job.py
- manager/integration/tests/test_statefulset.py
- `pytest` fixtures are called in the order provided, and teardown is happens in reverse of that specific order, 
Calling set_random_backpustore first, will ensure backupstore_cleanup happens after every volume gets deleted at test teardown.
- some `statefulset` tests was lacking `set_random_backupstore` fixture.
> Fix failing Nightly tests

- manager/integration/tests/test_csi.py
Set replica-replenishment-wait-interval = 600 so Longhorn reuses the failed replica
longhorn/longhorn#2167
> Fix: test_csi_expansion_with_replica_failure

- manager/integration/tests/test_recurring_job.py
Adjusted some sleep time in the test 'test_recurring_job` according to the time of recurring jobs getting triggered.
https://github.com/longhorn/longhorn/issues/2158
> Fix timing issue of the recurring job

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_ha.py
> Add test skeleton for the case when engine image DaemonSet is not fully deployed

- manager/integration/tests/common.py
The schema actions could return empty dict even if schema not exist, should look for an attribute instead.
https://ci.longhorn.io/job/public/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/285/testReport/tests/test_backing_image/
https://github.com/longhorn/longhorn/issues/2318
> Fix backing image tests (w/upgrade disabled)

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
* Replace inconsistent setting of backupstore with set_random_backupstore to ensure both s3 and nfs are tested.
* Remove resource cleanup as already handled by cleanup_client and set_random_backupstore.
https://github.com/longhorn/longhorn/issues/2305
> Fix test_restore_inc_*

- manager/integration/tests/test_backing_image.py
Missing backupstore targets.
https://github.com/longhorn/longhorn/issues/
> Fix test_recurring_job_labels_with_backing_image

- manager/integration/tests/test_ha.py
Volume does not get created with an invalid backupstore URL.
Update test to address to change from https://github.com/longhorn/longhorn/issues/2006.
https://github.com/longhorn/longhorn/issues/2343
> Fix test_restore_volume_with_invalid_backupstore

- manager/integration/tests/test_basic.py
Correct engine image state value.
https://github.com/longhorn/longhorn/issues/2344
> Fix test_engine_image_daemonset_restart

- manager/integration/tests/test_zone.py
Remove checking volume condition because allow-volume-creation-with-degraded-availability set to true by default.
https://github.com/longhorn/longhorn/issues/2352
> Fix test_replica_zone_anti_affinity

- manager/integration/tests/test_node.py
Remove checking volume condition because allow-volume-creation-with-degraded-availability set to true by default.
https://github.com/longhorn/longhorn/issues/2354
> Fix test_disable_scheduling_on_cordoned_node

- manager/integration/tests/test_basic.py
set `replica-replenishment-wait-interval` to trigger replica scheduling fail immediately
longhorn/longhorn#2350
> Fix test_running_volume_with_scheduling_failure

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_recurring_job.py
* Remove the intermediate status check after backup resume.
* Add wait for lock expiration before backupstore cleanup.
https://github.com/longhorn/longhorn/issues/2369
> Fix test_recurring_jobs_when_volume_detached_unexpectedly

- test_framework/Jenkinsfile
Increase timeout to insure RHEL & SLES pass without issues.
> nightly tests: increase terraform step timeout to 30 min

- manager/integration/tests/run.sh
Ref: https://github.com/longhorn/longhorn/issues/2333
pytest output/errors need to be directed to a file, so  pod out put will be only the content of 
`cat ${LONGHORN_JUNIT_REPORT_PATH}` command which is the Junit report.
> test framework: redirect pytest output/error to a file in run.sh

- test_framework/scripts/terraform-setup.sh
Ref: https://github.com/longhorn/longhorn/issues/2375
RKE somtimes fails to run on worker nodes because the delayed start of docker service.
> wait 30 seconds for docker to completetly start

- secscan/scripts/secscan.sh
https://github.com/longhorn/longhorn/issues/2006
> add backing-image-manager to security scan framework

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
We want to make sure that when the block deletion for the last backup is aborted by operations such as backups in progress, the DR volume will still pick up the correct last backup.
https://github.com/longhorn/longhorn/issues/2339
> Add and split DR tests regards to backup

- manager/integration/tests/test_basic.py
The DR last backup should be empty when GC delta block delete is aborted.
https://github.com/longhorn/longhorn-tests/pull/592
> Fix test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress

- docs/content/manual/pre-release/node/node-drain-deletion.md
Add manual test for kubectl drain nodes get stock forever to resolve issue '[BUG] kubectl drain node gets stuck forever'
Longhorn: #2673
> Add manual test for kubectl drain nodes get stock forever

- manager/integration/tests/test_statefulset.py
Fix test statefulset recurring backup as only keep one backup snapshot to resolve issue '[BUG] Nightly Test: test_statefulset_recurring_backup sometimes failed'
TEST_FILE=test_statefulset.py
TEST_CASE=test_statefulset_recurring_backup
Test case update in 
Refs: https://github.com/longhorn/longhorn/issues/1238
Refs: https://github.com/longhorn/longhorn-manager/pull/904
None
> Fix test statefulset recurring backup

- docs/content/manual/pre-release/resiliency/_index.md
- docs/content/manual/pre-release/resiliency/simulated-slow-disk.md
- docs/content/manual/pre-release/resiliency/timeout.md
I added a manual test for a simulated slow disk because I couldn't get dmsetup to work in the docker environment that the python longhorn-engine tests are run in.
https://github.com/longhorn/longhorn/issues/2206
Signed-off-by: Keith Lucas <keith.lucas@suse.com>
> Add a manual test for a simulated slow disk.

- manager/integration/tests/test_csi.py
https://github.com/longhorn/longhorn/issues/2766
**Cause of failure** : 
The rebuilding for 100MB is too fast that test is unable to capture the `inProgress` state.
**Proposed Solution**:
Increased the data to 300MB in the volume so that the rebuilding takes more time and test can get the rebuilding status.
> Fix test volume creation with degraded availability

- manager/integration/tests/test_backing_image.py
- test_backing_image.py::test_backup_with_backing_image
- test_backing_image.py::test_backup_labels_with_backing_image
- test_backing_image.py::test_ha_backup_deletion_recovery
- test_backing_image.py::test_csi_backup_with_backing_image
> Pass set_random_backupstore to configure S3/NFS backup store target

- manager/integration/tests/test_ha.py
> Add test skeletion for test_autosalvage_with_data_locality_enabled

- manager/integration/tests/common.py
- manager/integration/tests/test_node.py
Ref:
https://github.com/longhorn/longhorn/issues/2730
Few flake8 fix
**Cause of Failure**: The available storage logic changed https://github.com/longhorn/longhorn/issues/2680, now it is rounded off till 100 mb
**Solutions**: Same round off is applied while calculating the available storage
> Fix available storage related tests

- test_framework/scripts/longhorn-setup.sh
This PR will use default images of the following components in the nightly tests framework if not otherwise customized
- longhorn-instance-manager
- longhorn-share-manager
- backing-image-manager
original values will be fetched from `longhorn-manager/deploy/install` yaml manifest files.
> [v1.1.3-backport] use default images by default if not customized

- manager/integration/tests/test_basic.py
Remove orphan backup volume config from the remote backup target after test finished 
> Fix test_listing_backup_volume leaves orphan backup volume config

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_recurring_job.py
Because the backup volume CR changes to async pull from the remote backup target.
Add retry to get the backing image information from backup volume CR to
verify the backing image name and checksum.
https://github.com/longhorn/longhorn/issues/2876
> Fix test_backup_labels_with_backing_image

- manager/integration/tests/test_statefulset.py
Run the test with recurring snapshots since the backup store did not configure.
Otherwise, the orphan Backup CR would be staying in the cluster.
Note that, this PR did not fix the flakiness of this test case. But focus on fixing the orphan Backup CR.
> Fix test_statefulset_recurring_backup

- manager/integration/tests/test_kubernetes.py
- manager/integration/tests/test_statefulset.py
This PR backports #692 and #701 to v1.2.x branch
> [v1.2.x] backports fix test_statefulset_recurring_backup and test_backup_kubernetes_status flakiness

- manager/integration/tests/test_basic.py
> Add skeleton for `test_workload_with_fsgroup` test

- manager/integration/pytest.ini
This is to solve below pytest warning
```
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323: PytestUnknownMarkWarning: Unknown pytest.mark.cloning - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
warnings.warn(
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323: PytestUnknownMarkWarning: Unknown pytest.mark.migration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
warnings.warn(
```
> Fix pytest warning

- manager/integration/tests/test_basic.py
longhorn/longhorn#2964
longhorn/longhorn#2967
> [Backport v1.2.x] Add skeleton for test_workload_with_fsgroup test

- manager/integration/tests/common.py
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-ubuntu-amd64/2/
The recurring job `spec.groups` is an optional field https://github.com/longhorn/longhorn-manager/blob/3df7b91/types/resource.go#L190
Check the argument contains the `groups` field and then verify it's equal compares to the recurring job `spec.groups`.
> Fix all recurring job related test failed

- manager/integration/tests/backupstore.py
- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Add a new test `test_backuptarget_available_during_engine_image_not_ready` to verify configures the backup target setting during the default engine image is not ready.
https://github.com/longhorn/longhorn/issues/2960
> Add a new test test_backuptarget_available_during_engine_image_not_ready

- manager/integration/tests/common.py
There is no need to continue waiting if the deletion is done.
Before this fix, `test_engine_live_upgrade` takes 223s. After the fix, the test spends 62s only.
> integration: fix wait_for_engine_image_deletion()

- manager/integration/tests/common.py
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-ubuntu-amd64/2/
The recurring job `spec.groups` is an optional field https://github.com/longhorn/longhorn-manager/blob/3df7b91/types/resource.go#L190
Check the argument contains the `groups` field and then verify it's equal compares to the recurring job `spec.groups`.
> [Backport v1.2.x] Fix all recurring job related test failed

- manager/integration/tests/backupstore.py
- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Add a new test `test_backuptarget_available_during_engine_image_not_ready` to verify configures the backup target setting during the default engine image is not ready.
https://github.com/longhorn/longhorn/issues/2960
> [Backport-V1.2.x] Add a new test test_backuptarget_available_during_engine_image_not_ready

- secscan/scripts/provision.sh
- secscan/terraform/digitalocean/do.tf
> fix secscan: disable apt-upgrade timers for secscan provisioning and move upgrade to provision script

- manager/integration/tests/common.py
The nodes and disks have not been reset. Then the instance manager wait may fail the test (race condition).
> Avoid waiting for instance manager during setting reset

- test_framework/Jenkinsfile
- test_framework/terraform/aws/rhel/variables.tf
- test_framework/terraform/aws/sles/variables.tf
- test_framework/terraform/aws/ubuntu/variables.tf
- Reduce instance name length to fix failing jenkins jobs to Fix v1.2.1 nightly upgrade tests.
Ref: https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-ubuntu-amd64/9/console
- Increase timeout for terraform setup step to 60 min
RHEL 8.4.0 will take longer time to install docker than other OS`s
> fix nightly tests issues

- docs/content/manual/pre-release/node/node-drain-deletion.md
The flag --delete-local-data has been deprecated, use --delete-emptydir-data instead.
> Update flag command

- test_framework/terraform/aws/rhel/main.tf
- test_framework/terraform/aws/sles/main.tf
- test_framework/terraform/aws/ubuntu/main.tf
Sometimes instances will be deleted by automated scripts, we need to tag instances with `DoNotDelete` tag to prevent that.
> add don't delete tags to nightly tests nodes

- test_framework/terraform/aws/rhel/main.tf
- test_framework/terraform/aws/sles/main.tf
- test_framework/terraform/aws/ubuntu/main.tf
backport: https://github.com/longhorn/longhorn-tests/pull/738 to v1.1.3
> [v1.1.3-backport] add don't delete tags to nightly tests nodes

- manager/integration/tests/common.py
From #736 
Should use Exception not ApiException make the the loop wroking
> Change except type in common:wait_for_all_instance_manager_running 

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
After delete the engine image daemonset, we should wait a moment let engine image restart automatically
And use `image['conditions']['ready']['status']` to track engine image status
In origin we use `image.state` to track engine image status but it's always get "deployed" so test case flaky
> Fix flaky case : test_engine_image_daemonset_restart

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
> [backport-v1.2.x] Fix flaky case : test_engine_image_daemonset_restart

- manager/integration/tests/test_ha.py
At very rare rate(1/20) after step 10, volume.conditions.scheduled.status still True not become False immediately, make our test case flaky.
Since we do not specify timing for volume.conditions.scheduled.status become False, I would like to use `common.wait_for_volume_condition_scheduled ` let status become as expect then go next. If status not become False at end, script still raise Fail. Thanks
Steps:
```
1. Set a short interval for setting replica-replenishment-wait-interval.
2. Disable the setting soft-node-anti-affinity.
3. Create volume1 with 1 replica. and attach it to the host node.
4. Mount volume1 to a new mount point. then use it as an extra node disk.
5. Disable the scheduling for the default disk of the host node,
and make …
```
> Fix flaky test_replica_failure_during_attaching

- manager/integration/tests/test_ha.py
> [Backport v1.2.x]Fix flaky test_replica_failure_during_attaching

- manager/integration/tests/common.py
1. Based on the Jenkins parameters, the nfs and s3 backupstore is decided.
2. If the Jenkins parameter is not available, nfs and s3 backupstore will be decided on the test yaml file https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/deploy/test.yaml Longhorn_backupstore variable
https://github.com/longhorn/longhorn/issues/3200
> Make nfs and s3 selection Jenkins parameterized

- docs/content/manual/release-specific/v1.0.1/test-s3-backupstore.md
Make the test steps simpler and add related information.
- Point the Squid proxy configuration to a comment
- For the network configuration, since it is depending on cloud provider, I am leaving this out of test case
Also, I am thinking about renaming the document to `test-s3-behind-proxy.md`. There is no interlink within the docs/ but I am not sure if changing the docs name will impact others.
> Update manual test case "Test S3 backupstore in a cluster sitting behind a HTTP proxy"

- manager/integration/tests/common.py
- test_framework/scripts/longhorn-setup.sh
The variable `backup_store_type` is not available directly in the test from the Jenkins, so updating the test.yaml file while the Longhorn setup takes place based on Jenkins variable.
> Fix backup store type handling

- manager/integration/tests/test_node.py
Origin from [tests.test_node.test_node_eviction_soft_anti_affinity](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64-nfs/12/testReport/junit/tests/test_node/test_node_eviction_soft_anti_affinity/) and can reproduce on my local environment.
All fail happened at step 13, when replicas stop at node 2 and start to schedule on node 1 and node 3, at very few rate volume.robustness become **False** make script assert error and flaky.
In my observation, this volume.robustness become **False** behavior stay at few seconds and did not really effect replica schedule on node 1 and node 3, so I would like to change wait_for_replica_scheduled in common.py let the for loop work on volume and check in the …
> Fix flaky case : test_node_eviction_soft_anti_affinity

- manager/integration/tests/test_node.py
Backport PR#[785](https://github.com/longhorn/longhorn-tests/pull/785) to v1.1.3
> [Backport v1.1.3]Fix flaky test_node_eviction_soft_anti_affinity

- manager/integration/tests/test_node.py
Backport PR#[785](https://github.com/longhorn/longhorn-tests/pull/785) to v1.2.x
> [Backport v1.2.x]Fix flaky test_node_eviction_soft_anti_affinity

- manager/integration/tests/common.py
- manager/integration/tests/test_recurring_job.py
From https://github.com/longhorn/longhorn/issues/3233, we have some flaky recurring job cases in daily run.
Most cases fail reason was timing issue. Longhorn recurring job started at  beginning of a minute, but our test cases will set recurring job directly (maybe at 55th second), then do some test steps then do sleep **whole** minute and check result in the end
Modified `create_recurring_jobs` and reduce sleep time in test cases.
> Recurring job start just after minute start

- manager/integration/tests/test_rwx.py
From https://github.com/longhorn/longhorn/issues/2748
longhorn-nfs install failed in [nightly build](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-lh-tests-ubuntu-amd64/48/testReport/junit/tests/test_rwx/test_rwx_with_statefulset_multi_pods/), because `node_list = api.list_node()` will get non-worker node(we have 1 non-worker node in nightly build), but longhoron-nfs only install on worker node make `if len(nfs_pods) == len(node_list)` raise exception
> Check longhorn-nfs installed on worker node

- manager/integration/tests/test_basic.py
Since the longhorn manager changes the error message for the invalid
backup target setting, update the assert check message to address it.
https://github.com/longhorn/longhorn/issues/3280
> Update the assert check message

- manager/integration/tests/test_rwx.py
backport: #740 to v1.1.3 (Already backported to v1.2.x)
> [Backport 1.1.3] test rwx statefulset scale down up

- manager/integration/tests/test_basic.py
Sleep 1 second to prevent the same BackupTarget CR spec.syncRequestedAt.
> Fix test_backuptarget_available_during_engine_image_not_ready

- manager/integration/tests/test_basic.py
Sleep 1 second to prevent the same BackupTarget CR spec.syncRequestedAt.
> [BACKPORT] Fix test_backuptarget_available_during_engine_image_not_ready

- test_framework/Jenkinsfile
we need to make instance names shorter,
so that the total length of instance name is less than 64 characters
> shorten instance name in nighlty tests

- test_framework/Jenkinsfile
we need to make instance names shorter,
so that the total length of instance name is less than 64 characters
> [v1.1.3-backport] shorten instance name in nighlty tests

- test_framework/Jenkinsfile
we need to make instance names shorter,
so that the total length of instance name is less than 64 characters
> [v1.2.x-backport] shorten instance name in nighlty tests

- test_framework/terraform/aws/centos/main.tf
- test_framework/terraform/aws/oracle/main.tf
- test_framework/terraform/aws/rhel/main.tf
- test_framework/terraform/aws/rockylinux/main.tf
- test_framework/terraform/aws/sles/main.tf
- test_framework/terraform/aws/ubuntu/main.tf
> change aws key pair name to avoid potential naming conflict

- test_framework/terraform/aws/centos/main.tf
- test_framework/terraform/aws/oracle/main.tf
- test_framework/terraform/aws/rhel/main.tf
- test_framework/terraform/aws/rockylinux/main.tf
- test_framework/terraform/aws/sles/main.tf
- test_framework/terraform/aws/ubuntu/main.tf
> [v1.2.x-backport] change aws key pair name to avoid potential naming conflict

- test_framework/Jenkinsfile
This will fix issues in nightly tests that doesn't need to configure SELINUX_MODE parameter
Ref: https://github.com/longhorn/longhorn/issues/3076
> add optional parameters to Jenkins file

- test_framework/terraform/aws/rhel/data.tf
Fixes https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/35/console
> fix rhel missing architecture variable

- manager/integration/tests/test_recurring_job.py
After https://github.com/longhorn/longhorn/issues/627 and https://github.com/longhorn/longhorn/issues/3035 closed, backup count in recurring job will reflect by retain count correctly.
Modified test_recurring_job(), make it match longhorn behavior.
> Change backup count to reflect retain count in test_recurring_job

- manager/integration/tests/test_recurring_job.py
Change assertion string to case insensitive. 
Because currently our assertion is `Job Can\\'t retain more than 50 snapshots` and master-head API returned `job Can\\'t retain more than 50 snapshots`
> change assertion string insensitive

- manager/integration/tests/test_statefulset.py
From https://github.com/longhorn/longhorn/issues/3451
From script point of view, this case was flaky was due to when we search backup to restore(the backup just completed by test scenario), we should wait backup URL generated then go to do next step. 
Or we will restore an snapshot without backupstore url as below, and will cause e2e cases error
`'created': '', 'error': '', 'labels': None, 'messages': None, 'name': 'backup-a0eb0c351efc4668', 'progress': 0, 'size': '', 'snapshotCreated': '', 'snapshotName': '953a4c79-89e0-400b-b449-d956780ea5b5', 'state': '', 'url': '', 'volumeBackingImageName': '', 'volumeCreated': '', 'volumeName': 'pvc-084a2fc0-f29f-45fd-843e-9105cc4549fb', 'volumeSize': ''}`  
Correct format will be something like below …
> Fix flaky test_statefulset_restore

- manager/integration/tests/aws.py
- manager/integration/tests/test_infra.py
Our E2E test_node_off always fail when ran on arch arm64, that's because we use k3s as infra in arm64 but rke in amd64.
In test steps we use `metadata.labels` from k8s API to select one **worker** node and turn off it to do test.
In rke , label `node-role.kubernetes.io/worker=true` tell script this is worker node, but in k3s there are none label for worker nodes(so script always fail), only label `node-role.kubernetes.io/control-plane` for controlplane
**rke worker node**
```
'labels': { 'beta.kubernetes.io/arch=amd64',
beta.kubernetes.io/os=linux',
cattle.io/creator=norman',
kubernetes.io/arch=amd64',
kubernetes.io/hostname=worker1',
kubernetes.io/os=linux',
node-role.kubernetes.io/worker=true',
node-role.kubernetes.io/etcd=true'},
``` …
> Fix arch arm64 test_node_off  fail

- manager/integration/tests/common.py
Recently e2e daily build get increased fail number related to backup 
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/554/
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/553/
Most error encountered in wait_for_volume_status().
Did try reproduce but the error situation can not be reproduced, so I would like to add assert message to observe when the backup failure happen again. on build pipeline, thank you.
cc @khushboo-rancher
> Add assert message in wait_for_volume_status

- manager/integration/tests/common.py
- manager/integration/tests/test_tagging.py
https://github.com/longhorn/longhorn/issues/3625
**Cause of failure**:
The CRD is changed to have tags as a list instead of dictionary. 
**Solution**:
Changed the assert to check the list is empty.
cc: @longhorn/qa 
> Fix the tagging tests

- manager/integration/tests/test_rwx.py
We don't need the installation of nfs-common inside the test as the nfs-common installation is taken care in infra set up.
> Remove nfs-installation from the test

- manager/integration/README.md
Turns out ordered list begin with `1.1` doesn't supported in the GitHub Flavored Markdown<sup>*</sup> , and there is a couple trouble<sup>**</sup> with the ordered nested list.
<sup>*</sup> https://github.github.com/gfm/#ordered-list-marker
<sup>**</sup> https://github.com/github/markup/issues/210#issuecomment-470705342
> Fix the integration/README.md ordered list indentation 

- manager/integration/tests/test_zone.py
Replica auto-balance will first balance node then zone. Thus need more time for correction. Increased the time for retry.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/733/testReport/
https://github.com/longhorn/longhorn/issues/3649
> Fix flaky test result for test_replica_auto_balance_zone_best_effort

- manager/integration/tests/test_ha.py
From [e2e](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/53/testReport/junit/tests/test_ha/test_reuse_failed_replica_with_scheduling_check/) 
Because recently CRD changes, using `[]` instead `None` when no expected tags in function `set_tags_for_node_and_its_disks`
> fix test_reuse_failed_replica_with_scheduling_check

- manager/integration/tests/common.py
- manager/integration/tests/conftest.py
For https://github.com/longhorn/longhorn/issues/3557
Add feature to generate support bundle in longhorn-test pod when e2e test case fail
When test case fail , script will create folder `support_bundle` which the abs path is `/integration/tests/support_bundle` in pod
And will generate support bundle renamed `"test case name.zip"` into folder support_bundle
This is current design, for become Jenkins artifact for download, @meldafrawi  could you advise me should I modify code to match your Jenkins design, thank you
cc @innobead , @khushboo-rancher
> Generate support bundle when e2e case fail

- manager/integration/tests/test_basic.py
Set replica-replenishment-wait-interval to 0 so the test will not get blocked.
https://github.com/longhorn/longhorn/issues/3183
> Fix test_allow_volume_creation_with_degraded_availability_restore

- manager/integration/deploy/test.yaml
- manager/integration/tests/run.sh
- test_framework/scripts/longhorn-setup.sh
For task [#3740](https://github.com/longhorn/longhorn/issues/3740)
To fetch the test report, we have to "kubectl cp" the report, but there is no way to "kubectl cp" a completed pod, so another keepalive pod is created and we can get the test report from it.
After resolved the "kubectl cp" issue above, we don't have to use "kubectl logs" to print out the test report anymore. We can use "kubectl logs" to print pytest logs normally.
> Print pytest logs in jenkins console output

- test_framework/scripts/longhorn-setup.sh
Deal with streaming-connection-idle-timeout to fix integration tests fail to publish junit report.
By default, streaming-connection-idle-timeout is set to 4 hours, so the "kubectl logs -f" would lost the connection after 4 hours even though the pod is still running. But it also isn't recommended to disable the streaming-connection-idle-timeout.
So keep tracking the status of the longhorn-tests pod and re-trigger "kubectl logs -f".
> Fix integration tests fail to publish junit report

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
For [#3808](https://github.com/longhorn/longhorn/issues/3808)
when trying to find replica for a backup, the replica name is empty at first. 
Have to wait a few seconds (~5s) to get the correct value.
> Fix timing issue in test_backup_status_for_unavailable_replicas

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
when trying to find replica for a backup, the replica name is empty at first. Have to wait a few seconds (~5s) to get the correct value.
> [backport-v1.2.x] Fix timing issue in test_backup_status_for_unavailable_replicas

- manager/integration/tests/test_recurring_job.py
The current case will fail with longhorn-manager v1.3.0-dev(master branch), due to the introduction of webhook.
Adjusting the assertion string to make it recognize the error message.
---
pytest output for the reference:
```
_______________________________________________________________________ test_recurring_jobs_maximum_retain ________________________________________________________________________
client = <longhorn.Client object at 0x7f7de8274d90>, core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f7de8475a00>, volume_name = 'longhorn-testvol-25ptih'
def test_recurring_jobs_maximum_retain(client, core_api, volume_name): # NOQA
"""
Scenario: test recurring jobs' maximum retain
Given set a recurring job retain to 51.
When create recurring job.
Then should fail.
When …
```
> Fix asserting message in test_recurring_jobs_maximum_retain

- manager/integration/tests/common.py
Recently v1.1.x pipeline run error due to miss function get_volume_running_replica_cnt
--
move get_volume_running_replica_cnt into common.py
Signed-off-by: Chris Chien [chris.chien@suse.com](mailto:chris.chien@suse.com)
> Fix v1.1.x pipeline run error

- manager/integration/tests/common.py
Recently v1.2.x pipeline run error due to miss function `get_volume_running_replica_cnt`
--
move get_volume_running_replica_cnt into common.py
> Fix v1.2.x pipeline run error

- manager/integration/tests/common.py
- manager/integration/tests/test_csi_snapshotter.py
Implement `test_csi_snapshot_with_bak_param`
- Remove `deploy_csi_snapshot_and_classes` from common.py because  `volumesnapshotclass` in test_csi_snapshotter.py can deploy specific volumesnapshotclass and CSI snapshot CRDs already installed in `longhorn-setup.sh`
- Reuse `test_csi_volumesnapshot_basic`
> Implement test csi snapshot with bak param

- manager/integration/tests/test_ha.py
Reverts longhorn/longhorn-tests#929
I am sorry that I did not noticed with v1.1.x not support this feature, so this commit need to be reverted
Test [result](https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-tests-sles-amd64/69/testReport/junit/tests/test_ha/test_disable_replica_rebuild/)
`longhorn.ApiError: (ApiError(...), "500 : fail get setting concurrent-replica-rebuild-per-node-limit: setting concurrent-replica-rebuild-per-node-limit is not supported\n{'code': 500, 'detail': '', 'message': 'fail get setting concurrent-replica-rebuild-per-node-limit: setting concurrent-replica-rebuild-per-node-limit is not supported', 'status': 500}")`
> Revert "[Backport 1.1.x] test_disable_replica_rebuild"

- manager/integration/tests/test_infra.py
which expect aws and k8s node up but sometimes assertion failed
for [#3851](https://github.com/longhorn/longhorn/issues/3851)
> Print logs to debug reset_cluster_ready_status

- manager/integration/tests/requirements.txt
- manager/integration/tests/test_infra.py
(1) print debug messages
(2) mark test_offline_node the last one to be executed
for [#3851](https://github.com/longhorn/longhorn/issues/3851)
> [backport-v1.2.x] debug test offline node

- manager/integration/tests/test_basic.py
- from longhorn/longhorn-tests#756
> [v1.1.x-backport] Fix test_allow_volume_creation_with_degraded_availability_restore

- manager/integration/tests/common.py
- manager/integration/tests/test_recurring_job.py
Backport https://github.com/longhorn/longhorn-tests/pull/955
Flaky test result - [#1155](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1155/)
> [BACKPORT][v1.2.x] Fix flaky test_recurring_job_detached_volume

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_node.py
- manager/integration/tests/test_scheduling.py
- manager/integration/tests/test_tagging.py
There are some errors in the e2e test after introducing the node monitor, like
```
...cannot finish API request due to too many error retries
```
Currently, the tests are not waiting long enough for the disks to be reconciled by the node controller.
The subsequent actions might encounter unexpected errors due to the non-ready disks.
The fix is retrying node/disk update if "too many retries error" happened.
[Longhorn 3939](https://github.com/longhorn/longhorn/issues/3939)
> Retry node/disk update if "too many retries error" happened.

- manager/integration/tests/test_orphan.py
test cases create and teardown disks frequently, so the retry is necessary.
Longhorn 685
> test_orphan.py: retry update_node_disks

- docs/layouts/_default/single.html
- Add edit link be populated under each content section.
- The link will open github web editor
Local preview:
> Add Edit button to the docs/ contents

- test_framework/scripts/longhorn-setup.sh
https://github.com/longhorn/longhorn/issues/4027
Use external snapshotter release branch instead of master branch to avoid unexpected error
> Use external snapshotter release branch in e2e pipeline

- test_framework/scripts/longhorn-setup.sh
Backport https://github.com/longhorn/longhorn-tests/pull/970
> [Backport 1.1.x] Use external snapshotter release branch

- test_framework/scripts/longhorn-setup.sh
backport https://github.com/longhorn/longhorn-tests/pull/970
> [Backport 1.2.x] Use external snapshotter release branch

- manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn/issues/3546
https://github.com/longhorn/longhorn/issues/4033
> grpc-proxy: skip test_backuptarget_available_during_engine_image_not_ready

- docs/content/manual/pre-release/node/node-deletion.md
- docs/layouts/_default/baseof.html
Fix the ordered list for sublists with css, adding to the html > header > style tag block.
It should like this, as tested from my local environment:
> Update node-deletion.md: Fix the ordered list style and add example to crash replicas via cli

- manager/integration/tests/test_basic.py
After all nodes are enabled and replicas are scheduled, the replicas might
be rebuilt before wait_for_volume_healthy(), the volume becomes healthy.
Thus, we wait for the volume healthy rather than degraded, and then check the data.
[Longhorn 3220](https://github.com/longhorn/longhorn/issues/3220)
> Fix the flaky issue in test_allow_volume_creation_with_degraded_ability

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
Implement parallel checks for replica failures in crash_replica_processes.
longhorn/longhorn#4045
Signed-off-by: James Lu <jamesluhz@gmail.com>
> Check replicas failed in parallel.

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
In function `crash_replica_processes`.
Make "check replica failed" in threading.
Longhorn-4045
Signed-off-by: James Lu <jamesluhz@gmail.com>
> [backport-v1.3.x] Implement parallel checks for replica failures

- manager/integration/tests/common.py
In function `crash_replica_processes`.
Make "check replica failed" in threading.
Longhorn-4045
Signed-off-by: James Lu <jamesluhz@gmail.com>
> [backport 1.2.x] Implement parallel checks for replica failures

- manager/integration/tests/common.py
- manager/integration/tests/test_csi_snapshotter.py
https://github.com/longhorn/longhorn/issues/3845
Separate `test_csi_snapshot_with_snap_param` into
- `test_csi_snapshot_snap_create_csi_snapshot`
- `test_csi_snapshot_snap_create_volume_from_snapshot` 
- `test_csi_snapshot_snap_delete_csi_snapshot` (only skeleton)
to reduce long script and avoid hard maintain and debug
> Add test case for test external csi snapshot with snap param

- test_framework/Jenkinsfile
Add user information to build name to easily identify which build is triggered by whom
For https://github.com/longhorn/longhorn/issues/4034
> Add user information to build name to easily identify which build is triggered by whom

- benchmark_test/Jenkinsfile
- benchmark_test/scripts/benchmark-test-setup.sh
- benchmark_test/user-data-scripts/provision_rke2_server.sh.tpl
(1) Fix rke2 control plane schedulable
(2) Cordon redundant nodes when test replica count < cluster worker node count
For https://github.com/longhorn/longhorn/issues/4200
> Refine benchmark test to let volume and replicas on the same node

- manager/integration/tests/common.py
Fix minor issue of the bi_name parameter not actually be used in `check_backing_image_disk_map_status`
> Fix bi_name paremeter not really be used in check_backing_image_disk_map_status

- build_engine_test_images/Dockerfile.setup
- build_engine_test_images/Jenkinsfile
- build_engine_test_images/run.sh
- build_engine_test_images/scripts/build.sh
- build_engine_test_images/scripts/cleanup.sh
- build_engine_test_images/scripts/generate_images.sh
- build_engine_test_images/terraform/aws/ubuntu/data.tf
- build_engine_test_images/terraform/aws/ubuntu/main.tf
- build_engine_test_images/terraform/aws/ubuntu/user-data-scripts/provision.sh
- build_engine_test_images/terraform/aws/ubuntu/variables.tf
From https://github.com/longhorn/longhorn/issues/1961, https://github.com/longhorn/longhorn/issues/4206
Will build amd64/arm64 test engine image by API version for longhorn-test use and push to specific docker hub repo
```
chanow/longhorn-engine:upgrade-test.5-3.3-3.1-1
chanow/longhorn-engine:version-test.5-3.3-3.1-1
chanow/longhorn-engine:version-test.6-4.3-3.1-1
chanow/longhorn-engine:version-test.6-6.3-3.1-1
chanow/longhorn-engine:version-test.4-2.3-3.1-1
chanow/longhorn-engine:version-test.2-2.3-3.1-1
```
Test reault : [amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1602/), [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1601/parameters/)
Environment
- Have docker installed
- Have local …
>  Build test engine/version image for both amd64/arm64

- build_engine_test_images/terraform/aws/ubuntu/variables.tf
Got error `Your requested instance type (a1.medium) is not supported in your requested Availability Zone (us-east-1a)` when building arm64 test images, change zone from us-east-1a to us-east-1b
> change build test engine zone form us-east-1a to us-east-1b

- manager/integration/tests/common.py
- manager/integration/tests/test_cloning.py
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/139/testReport/junit/tests/test_cloning/test_cloning_interrupted/
https://github.com/longhorn/longhorn/issues/4047
Fix test case test_cloning_interrupted
Add `wait_for_volume_degraded` for clone volume before crash source volume replica process.
Or the cloning won't interrupt in recent build.
> Fix test case test_cloning_interrupted

- manager/integration/tests/common.py
- manager/integration/tests/test_backing_image.py
Creating a backing image from a volume then copying it to other nodes during volume attachment would take a longer time. Hence we need to use a longer timeout.
> integration: Use a longer timeout for test_exporting_backing_image_from_volume

- manager/integration/tests/common.py
Fix no cleanup_volume_by_name() in v1.2.x
For https://github.com/longhorn/longhorn/issues/4304
> Fix no cleanup_volume_by_name() in v1.2.x

- manager/integration/tests/common.py
- manager/integration/tests/test_node.py
When deleting the replica at step 7 of the test, the new replica
rebuilding may be not done yet. Then the ReplicaRemove API would
be rejected until the new replica is healthy.
Here I prefer to use a retry rather than directly checking and
waiting for the new replica rebuilding. Since this retry operation
would help verify that the last replica won't disappear
accidentally.
Longhorn/longhorn#4238
> Add replica removal retry for test_disk_eviction_with_node_level_soft_anti_affinity_disabled

- manager/integration/tests/common.py
- test_framework/terraform/aws/rockylinux/data.tf
Fix RockyLinux 8.5 arm64 has no AMI results
For https://github.com/longhorn/longhorn/issues/4341
> Fix RockyLinux 8.5 arm64 has no AMI results

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
From https://github.com/longhorn/longhorn/issues/4309
Root cause : https://github.com/longhorn/longhorn/issues/4309#issuecomment-1197897496
Remove code for catch volume detach after `crash_engine_process_with_sigkill`
Without that line, test script still checked `RestoreInProgress` after engine crash and check restored volume's md5, which matched the test goal
> Fix test_engine_crash_for_restore_volum

- manager/integration/tests/test_settings.py
Fix 1 short loop duration, let the duration more close to test case design ( 2 minute) or the test case may have flaky test result.
> Fix test_setting_concurrent_rebuild_limit short loop duration

- manager/integration/tests/test_ha.py
Backport v1.2.x - fix_test_engine_crash_for_dr_volume
> [Backport v1.2.x] fix test_engine_crash_for_dr_volume

- manager/integration/tests/test_ha.py
Backport v1.2.x - fix_test_engine_crash_for_restore_volume
> [Backport v1.2.x]fix_test_engine_crash_for_restore_volume

- manager/integration/tests/test_ha.py
Backport v1.3.x - fix_test_engine_crash_for_restore_volume
> [Backport v1.3.x] fix_test_engine_crash_for_restore_volume

- manager/integration/tests/test_ha.py
Backport v1,3,x - fix_test_engine_crash_for_dr_volume
> [Backport v1,3,x] fix_test_engine_crash_for_dr_volume

- manager/integration/tests/common.py
In step7 the volume `faulted` state can be observed but not by script because the state transition were too fast 
Modified `wait_for_volume_status`, add option to disable check `wait_for_volume_creation` let script can quick check volume status
> Fix flaky case test_cloning_interrupted

- manager/integration/tests/common.py
Backport https://github.com/longhorn/longhorn-tests/pull/1058 to v1.2.x
> [Backport 1.2.x]Fix flaky case test_cloning_interrupted

- manager/integration/tests/common.py
Backport https://github.com/longhorn/longhorn-tests/pull/1058 to v1.3.x
> [Backport 1.3.x]Fix flaky case test_cloning_interrupted

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_settings.py
Backport below cases to v1.3.x
- test_settings::test_setting_concurrent_rebuild_limit
- test_engin_upgrade.py::test_engine_live_upgrade_while_replica_concurrent_rebuild
> [Backport 1.3.x]test_setting_concurrent_rebuild_limit test_engine_live_upgrade_while_replica_concurrent_rebuild

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_settings.py
Backport below cases to v1.2.x
- test_settings::test_setting_concurrent_rebuild_limit
- test_engin_upgrade.py::test_engine_live_upgrade_while_replica_concurrent_rebuild
> [Backport 1.2.x]test_setting_concurrent_rebuild_limit test_engine_live_upgrade_while_replica_concurrent_rebuild

- manager/integration/tests/common.py
- test_framework/scripts/longhorn-setup.sh
Use longer timeout when running HDD regression test
For https://github.com/longhorn/longhorn/issues/4228
> Use longer timeout when running HDD regression test

- manager/integration/tests/test_ha.py
Signed-off-by: Chris Chien [chris.chien@suse.com](mailto:chris.chien@suse.com)
Fix flaky test_ha_salvage https://github.com/longhorn/longhorn/issues/4381#issuecomment-1212704361
In case the volume faulted status was not easily to catch by script. modify script to detect volume `attaching` state is more stable
Test PR code 20 times on pipeline were [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1873/)
> Fix flaky test_ha_salvage

- manager/integration/tests/common.py
Fix missing write_volume_dev_random_mb_data method in v1.2.x
> Fix missing write_volume_dev_random_mb_data method in v1.2.x

- manager/integration/tests/test_ha.py
Backport https://github.com/longhorn/longhorn-tests/pull/1075 to v1.2.x
> [Backport v1.2.x] Fix flaky test_ha_salvage

- test_framework/scripts/longhorn-setup.sh
ci: fix manifest air gap installation pipeline failed in v1.2.x by avoiding duplicated document separator in yaml file causing yq parsing error.
For https://github.com/longhorn/longhorn/issues/4479
> ci: fix manifest air gap installation pipeline failed in v1.2.x

- docs/content/manual/pre-release/basic-operations-parallelism/snapshot-while-writing-data.md
Update the case is due to the above issue is still open and the scenario will not work.
> Update the case is due to the above issue is still open 

- manager/integration/tests/test_cloning.py
https://github.com/longhorn/longhorn/issues/4487
Somehow `test_cloning_interrupted` still [flaky](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/227/testReport/junit/tests/test_cloning/test_cloning_interrupted/) because step 7 `wait_for_volume_faulted` not every time can catch by script0
I tried to use workaround the of test case [test_ha_salvage](https://github.com/longhorn/longhorn-tests/pull/1075) and run this test case on pipleline 20 times. the result were all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1936/)  for reference.
> Modify test_cloning_interrupted

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Cover enabling and disabling auto failed backup cleanup.
longhorn/longhorn#4515
Signed-off-by: James Lu <james.lu@suse.com>
> [BACKPORT][v1.3.x] Add test case: failed backups cleanup

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Cover enabling and disabling auto failed backup cleanup.
longhorn/longhorn#4514
Signed-off-by: James Lu <james.lu@suse.com>
> [BACKPORT][v1.2.x] Add test case: failed backups cleanup

- secscan/Jenkinsfile
- secscan/scripts/secscan.sh
- secscan/terraform/aws/main.tf
- secscan/terraform/aws/variables.tf
ci: support running secscan test on specified longhorn branch/version
For https://github.com/longhorn/longhorn/issues/4357
> ci: support running secscan test on specified longhorn branch/version

- manager/integration/tests/common.py
- manager/integration/tests/test_cloning.py
Backport https://github.com/longhorn/longhorn-tests/pull/1083 to v1.3.x for fix flaky test_cloning_interrupted
> [Backport v1.3.x] Modify test_cloning_interrupted

- manager/integration/tests/common.py
- manager/integration/tests/test_cloning.py
Backport https://github.com/longhorn/longhorn-tests/pull/1083 to v1.2.x for fix flaky test_cloning_interrupted
> [Backport v1.2.x] Modify test_cloning_interrupted

- docs/content/manual/release-specific/v1.4.0/test-upgrade-for-migrated-longhorn.md
Add test case for Longhorn upgrade on Rancher where the Longhorn app was migrated from cluster explorer to dashboard
> Add test case for upgrade for migrated Longhorn on Rancher

- manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn/issues/4535
After https://github.com/longhorn/longhorn-manager/commit/e2de327809ceaab667d00c882673496b70ff2cd5 merged
Longhorn will auto create new label `"longhorn.io/volume-access-mode":"rwo/rwx"` in backup
Some test case assert the backup label counts and that count did not include new label. 
Need to modify test script to match newest product behavior
> Modify backup_labels_test for new auto generated backup label

- test_framework/scripts/download-support-bundle.sh
ci: prevent corrupt regression test from stuck in download support bundle forever
For https://github.com/longhorn/longhorn/issues/4072
> ci: prevent corrupt regression test from stuck in download support bundle forever

- manager/integration/tests/test_basic.py
Backport https://github.com/longhorn/longhorn-tests/pull/1098 to v1.3.x
> [Backport 1.3.x] Modify backup_labels_test for new auto generated backup label

- test_framework/scripts/download-support-bundle.sh
ci: prevent stuck in download support bundle forever if it cannot be downloaded
For https://github.com/longhorn/longhorn/issues/4072
> ci: prevent stuck in download support bundle forever if it cannot be downloaded

- manager/integration/tests/test_ha.py
Backport https://github.com/longhorn/longhorn-tests/pull/1085 to v1.2.x for fix flaky test_rebuild_with_restoration
> [Backport v1.2.x] Modify test_rebuild_with_restoration

- manager/integration/tests/test_recurring_job.py
From https://github.com/longhorn/longhorn/issues/4535 and https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/248/#showFailuresLink
Related test case
- test_recurring_job_labels_with_backing_image
- test_recurring_job_labels
- test_recurring_job_kubernetes_status
-  change `assert len(backups) == 1` to `wait_for_backup_count(bv, 1)`, because delete extra backup to keep back count the same with retain count need time, and make test case flaky
Test result on [pipeline](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1997/)
> Fix backup count assertion error in recurring job

- manager/integration/tests/test_engine_upgrade.py
https://github.com/longhorn/longhorn/issues/4593
The private longhorn image test v1.3.x report 
1. test_engine_live_upgrade_while_replica_concurrent_rebuild [test report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2009/testReport/tests/test_engine_upgrade/test_engine_live_upgrade_while_replica_concurrent_rebuild)
2. v1.3.x CI test result : [report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2012/#showFailuresLink)
(cherry picked from commit b0f9658a00370be9cfb51498c86976b908ceb570)
> Fix the issue #4593 on 1.3.x, missed commit from master

- manager/integration/tests/test_recurring_job.py
Update `test_recurring_job_labels` label count assertion to fix
- test_backing_image.test_recurring_job_labels_with_backing_image
- test_recurring_job.test_recurring_job_labels
> Update test_recurring_job_labels label assert

- test_framework/terraform/aws/oracle/variables.tf
- test_framework/terraform/aws/rhel/variables.tf
- test_framework/terraform/aws/rockylinux/variables.tf
- test_framework/terraform/aws/sles/variables.tf
ci: update sles default version to 15.4, rocky/rhel/oracle default version to 8.6
For https://github.com/longhorn/longhorn/issues/4620, https://github.com/longhorn/longhorn/issues/4618
> ci: update sles default version to 15.4, rocky/rhel/oracle default version to 8.6

- build_engine_test_images/Jenkinsfile
- build_engine_test_images/scripts/generate_images.sh
- build_engine_test_images/terraform/aws/ubuntu/main.tf
- build_engine_test_images/terraform/aws/ubuntu/variables.tf
https://github.com/longhorn/longhorn/issues/4615
With https://github.com/longhorn/infra/pull/100 to have option to build engine upgrade test images form specific commit
Longhorn v1.2.x engine upgrade test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2067/) with [upgrade-test.5-3.3-3.1-1](https://hub.docker.com/layers/chanow/longhorn-manager-test/upgrade-test.5-3.3-3.1-1/images/sha256-14237c8bac6c32fc44552e37b76199b1e7b6683052e42c4f879e8b6ac5f1bf84?context=repo) 
Longhorn master-head engine upgrade test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2068/) with [upgrade-test.6-3.3-3.1-1](https://hub.docker.com/layers/chanow/longhorn-test/upgrade-test.6-3.3-3.1-1/images/sha256-1d160111b7 …
> Have option to build engine upgrade test images form specific commit

- test_framework/terraform/aws/rockylinux/data.tf
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_agent.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_server.sh.tpl
ci: update rockylinux ami filter to get 8.6 image and refine init script to disable nm-cloud-setup
For https://github.com/longhorn/longhorn/issues/4620
> ci: update rockylinux ami filter to get 8.6 image and refine init script to disable nm-cloud-setup

- manager/integration/tests/test_recurring_job.py
Backport https://github.com/longhorn/longhorn-tests/pull/1112 to v1.3.x
> [Backport v1.3.x] Update test_recurring_job_labels label assert

- build_engine_test_images/terraform/aws/ubuntu/variables.tf
When create ARM64 instances encountered
```
Error: Error launching source instance: Unsupported: Your requested instance type (a1.medium) is not supported in your requested Availability Zone (us-east-1b). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1c, us-east-1d.
status code: 400, request id: ef12f50f-30ed-4265-9d81-9d6912e685a9
```
change the aws_availability_zone from us-east-1b to 1c
> Chanoge aws_availability_zone from us-east-1b to 1c

- airgap/terraform/main.tf
- build_engine_test_images/terraform/aws/ubuntu/main.tf
- secscan/terraform/aws/main.tf
- test_framework/terraform/aws/centos/main.tf
- test_framework/terraform/aws/oracle/main.tf
- test_framework/terraform/aws/rhel/main.tf
- test_framework/terraform/aws/rockylinux/main.tf
- test_framework/terraform/aws/sles/main.tf
- test_framework/terraform/aws/ubuntu/main.tf
ci: ensure all testing resources have proper tag to be identified
(1) ensure aws ec2 instances have Owner="longhorn-infra" to be identified as longhorn testing instances.
(2) ensure all aws resources have Name contains random suffix to be associated to aws ec2 instances, then if there is a long-running aws ec2 instance, the random suffix can be used to track and delete all the aws resources associated to this aws ec2 instance.
(3) add Owner="longhorn-infra" to all aws resources to reverse lookup orphaned resources with no aws ec2 instance.
For https://github.com/longhorn/longhorn/issues/4395
> ci: ensure all testing resources have proper tag to be identified

- test_framework/terraform/aws/rhel/main.tf
- test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/rhel/user-data-scripts/provision_rke.sh.tpl
ci: fix rhel >= 8.4 nm-cloud-setup related error when setup k3s cluster.
For https://github.com/longhorn/longhorn/issues/4333
> ci: fix rhel >= 8.4 nm-cloud-setup related error when setup k3s cluster.

- docs/content/manual/pre-release/node/node-disconnection.md
Add steps to run `sync` command in case 3, make sure test data flushed then do network reconnect
To avoid false alarm like https://github.com/longhorn/longhorn/issues/4680
> Updata manual case node-disconnection

- manager/integration/deploy/test.yaml
- manager/integration/tests/common.py
test: temporarily fix busybox version to 1.34.0 to avoid the CrashLoopBackOff issue in its latest version
For https://github.com/longhorn/longhorn/issues/4685
> test: temporarily fix busybox version to 1.34.0

- manager/integration/tests/common.py
test: longer pod, statefulset timeout for hdd test
For https://github.com/longhorn/longhorn/issues/4688
> test: longer pod, statefulset timeout for hdd test

- manager/integration/deploy/test.yaml
- manager/integration/tests/common.py
- manager/integration/tests/test_cloning.py
- manager/integration/tests/test_ha.py
test: fix busybox version to 1.34.0  to avoid the CrashLoopBackOff issue in its latest version
For https://github.com/longhorn/longhorn/issues/4685
> test: fix busybox version to 1.34.0  to avoid the CrashLoopBackOff issue in its latest version

- manager/integration/tests/test_basic.py
test: fix test_backup_volume_restore_with_access_mode by shortening volume name to avoid volume name truncation.
For https://github.com/longhorn/longhorn/issues/4713
> test: fix test_backup_volume_restore_with_access_mode by shortening volume name

- docs/content/manual/pre-release/resiliency/pvc_provisioning_with_insufficient_storage.md
From https://github.com/longhorn/longhorn/issues/4654
Add manual test case PVC_provisioning_with_insufficent_storage
> Add manual case pvc_provisioning_with_insufficient_storage

- manager/integration/tests/test_basic.py
[Longhorn 4653](https://github.com/longhorn/longhorn/issues/4653)
Description:  As RWX volumes can only be attached in maintenance mode and cannot be attached using the API. Therefore, volumes require additional deployment PVs and PVCs.
Self test: Pass with parameter matrix with 4 condition
> bug: fix to create rwx volume with PV & PVC deployment

- manager/integration/tests/common.py
- manager/integration/tests/test_backing_image.py
Backport test case https://github.com/longhorn/longhorn-tests/pull/1114 test_backing_image_auto_resync to v1.2.x
> [Backport v1.2.x] Implement test_backing_image_auto_resync

- manager/integration/tests/common.py
- manager/integration/tests/test_backing_image.py
Backport test case https://github.com/longhorn/longhorn-tests/pull/1114 `test_backing_image_auto_resync` to v1.3.x
> [Backport v1.3.x] Implement test case test_backing_image_auto_resync

- manager/integration/tests/test_basic.py
[Longhorn 4653](https://github.com/longhorn/longhorn/issues/4653)
Fix e2e test case: test_backup_volume_restore_with_access_mode, failed to backup for RWX volume occasionally.
```
test_basic.py:4625: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:345: in create_backup
data = write_volume_random_data(volume)
common.py:2256: in write_volume_random_data
return write_device_random_data(dev, position=position)
common.py:2270: in write_device_random_data
data_len = dev_write(dev, data_pos, data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dev = '/dev/longhorn/longhorn-testvol-e2290o', start = 88601
data = b'xb1xyet6uz8a1aowdbkpniwg5zvhgk44au6avvyt2dbop4f4v5f7mi0sun04aop …
```
> fix(rwx backup): fix failed to backup for RWX volume occasionally

- docs/content/manual/pre-release/resiliency/timeout.md
Remove Ping Timeout scenario because test scenario outdated https://github.com/longhorn/longhorn/issues/4778#issuecomment-1292771137
> Update manual case Test timeout on loss of network connectivity

- test_framework/terraform/aws/centos/variables.tf
- test_framework/terraform/aws/oracle/variables.tf
- test_framework/terraform/aws/rhel/variables.tf
- test_framework/terraform/aws/rockylinux/variables.tf
- test_framework/terraform/aws/sles/variables.tf
- test_framework/terraform/aws/ubuntu/variables.tf
ci: update default k8s version to v1.25 on master branch
for k3s, update to v1.25.3+k3s1
for rke2, update to v1.25.3+rke2r1
for rke, it doesn't support k8s v1.25 yet
For https://github.com/longhorn/longhorn/issues/4239
> ci: update default k8s version to v1.25 on master branch

- manager/integration/tests/test_basic.py
- manager/integration/tests/test_migration.py
Unscheduled replica would be deleted when volume was detached, so there would not be failed replicas when degraded volume was detached.
Merged after PR https://github.com/longhorn/longhorn-manager/pull/1534
longhorn/longhorn#4791
> Unscheduled replica clean-up

- manager/integration/tests/test_scheduling.py
Wait more time after node 3 schedule enabled to handle replica
Or test case will become flaky in master-head
Origin test code run 25 times will fail 3 times
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2301/
PR code  run 25 times all passed
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2296/
> Fix flaky test_replica_auto_balance_node_best_effort

- manager/integration/tests/test_basic.py
- manager/integration/tests/test_migration.py
Unscheduled replica would be deleted when volume was detached, so there would not be failed replicas when degraded volume was detached.
longhorn/longhorn#4809
> [BACKPORT][v1.2.6] unscheduled replica clean-up

- manager/integration/tests/test_basic.py
- manager/integration/tests/test_migration.py
Unscheduled replica would be deleted when volume was detached, so there would not be failed replicas when degraded volume was detached.
longhorn/longhorn#4808
> [BACKPORT][v1.3.x] unscheduled replica clean-up

- manager/integration/tests/common.py
- manager/integration/tests/requirements.txt
- manager/integration/tests/test_recurring_job.py
test: update kubernetes client version to 25.3 and replace batch/v1beta1 with batch/v1 to fix recurring job test cases failed on master pipeline
For https://github.com/longhorn/longhorn/issues/4830
> test: update kubernetes client version to 25.3 and replace batch/v1beta1 with batch/v1

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
test: fix flaky test case test_autosalvage_with_data_locality_enabled
(1) add mechanism to wait for a stable running pod when deployment restarts its workload
(2) use dd to write large size test data
For https://github.com/longhorn/longhorn/issues/4814
> test: fix flaky test case test_autosalvage_with_data_locality_enabled

- manager/integration/tests/requirements.txt
test: update pyyaml version to 5.4.1 for kubernetes 25.3.0
since kubernetes 25.3.0 depends on pyyaml>=5.4.1
For https://github.com/longhorn/longhorn/issues/4830
> test: update pyyaml version to 5.4.1 for kubernetes 25.3.0

- test_framework/scripts/longhorn-setup.sh
test: update csi snapshotter to v5.0.1 for k8s v1.25
For https://github.com/longhorn/longhorn/issues/4239
> test: update csi snapshotter to v5.0.1 for k8s v1.25

- docs/content/manual/pre-release/backup-and-restore/pull-backup-created-by-another-longhorn.md
test: add manual test case for pulling backup created by another longhorn
For https://github.com/longhorn/longhorn/issues/4637
> test: add manual test case for pulling backup created by another longhorn

- manager/integration/tests/test_backing_image.py
Backport https://github.com/longhorn/longhorn-tests/pull/1183 to v1.3.x
Test result : [Pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2496/testReport/tests/test_backing_image/test_backing_image_cleanup/)
> [Backport v1.3.x] Add test case test_backing_image_cleanup

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Update the case test_backuptarget_available_during_engine_image_not_ready
issue https://github.com/longhorn/longhorn/issues/4750
> Update the case test_backuptarget_available_during_engine_image_not_ready

- manager/integration/tests/common.py
Ref: longhorn-test PR 1181
Avoid teardown error when a volume attached to another disk volume
> Reorder cleanup_client

- manager/integration/tests/test_infra.py
verify aws node status, before checking k8s node status
add retry logic for checking aws and k8s node status
https://github.com/longhorn/longhorn/issues/4921
> Enhance test_offline_node

- manager/integration/tests/common.py
Ref: longhorn-test PR 1181
Avoid teardown error when a volume attached to a volume disk
> [Backport v1.3.x] Reorder cleanup_client

- manager/integration/tests/common.py
Ref: longhorn-test PR 1181
Avoid teardown error when a volume attached to a volume disk
> [Backport v1.2.x] Reorder cleanup_client

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
issue https://github.com/longhorn/longhorn/issues/4859
(cherry picked from commit af452d15c10137acbfb158b076e6c6d7fbbc5f24)
> [BACKPORT][v1.3.x] Enable the case test_backuptarget_available_during_engine_image_not_ready

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
https://github.com/longhorn/longhorn/issues/4737
Add test case `test_auto_upgrade_engine_to_default_version`
Run PR code 10 time on both [AMD64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2385/testReport/tests/test_engine_upgrade/) / [ARM64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2386/testReport/tests/test_engine_upgrade/) were  all passed
For the removed test step in PR code
```
6. In a retry loop, verify that the number of volumes who
is upgrading engine is always smaller or equal to 3
```
I tried to compare value `volume.currentImage` between `volume.engineImage`,  if they were different and `volume.engineImage` is target image, I can consider that the volume is upgrading engine image, and …
> Add test test_auto_upgrade_engine_to_default_version

- manager/integration/tests/test_infra.py
verify aws node down status, before checking k8s node down
Extend retry interval time for checking aws and k8s node down
Ref: [#4940](https://github.com/longhorn/longhorn/issues/4940)
(cherry picked from commit 85b4609867cafa65e705690a547bc829ab297786)
> [BACKPORT][master]Enhance test_offline_node

- manager/integration/tests/test_infra.py
verify aws node down status, before checking k8s node down
Extend retry interval time for checking aws and k8s node down
Ref: [4939](https://github.com/longhorn/longhorn/issues/4939)
(cherry picked from commit 85b4609867cafa65e705690a547bc829ab297786)
> [BACKPORT][v1.3.x]Enhance test_offline_node

- manager/integration/tests/test_scheduling.py
To avoid volume not clean up clearly after longhorn-test [PR1193](https://github.com/longhorn/longhorn-tests/pull/1193) merged
Ref: [4957](https://github.com/longhorn/longhorn/issues/4957)
> Modify test_replica_schedule_to_disk_with_most_usable_storage

- manager/integration/tests/test_scheduling.py
Backport https://github.com/longhorn/longhorn-tests/pull/1209 to v1.3.x
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2594/) on pipeline were passed
> [BACKPORT][v1.3.x]Modify test_replica_schedule_to_disk_with_most_usable_storage

- manager/integration/tests/test_scheduling.py
Backport https://github.com/longhorn/longhorn-tests/pull/1209 to v1.2.x
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2593/) on pipeline were passed
> [BACKPORT][v1.2.x] Modify test_replica_schedule_to_disk_with_most_usable_storage

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
Make wait time become variable in `write_volume_dev_random_mb_data`
Avoid some test case get timeout error when writing big size data into volume
Failed test [case](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/307/testReport/tests/test_basic/test_space_usage_for_rebuilding_only_volume/) 
> Modify common function write_volume_dev_random_mb_data

- docs/content/manual/release-specific/v1.4.0/test-node-id-change-during-backing-image-creation.md
> docs: Add a manual test 'test-node-id-change-during-backing-image-creation'

- docs/content/manual/pre-release/air-gap/_index.md
- docs/content/manual/pre-release/air-gap/air-gap-installation.md
- docs/content/manual/pre-release/air-gap/air-gap-instance-manager-name.md
- docs/content/manual/pre-release/resiliency/test-longhorn-component-recovery.md
1. This is to include components recovery test in the release testing.
2. Removed air gap test from manual test as this is automated already.
> Add longhorn components recovery

- cleanup/scripts/cleanup.sh
ci: shorten cleanup long-running instances threshold to 1 day
> ci: shorten cleanup long-running instances threshold to 1 day

- manager/integration/tests/test_basic.py
Try to rebuild the volume metafile when attaching a volume. Add test case to delete or empty the vollume meta file and then It should still work fine when the volume attached.
longhorn/longhorn#4846
https://github.com/longhorn/longhorn/issues/4964
[PR775](https://github.com/longhorn/longhorn-engine/pull/775)
> test(replica): volume metafile deleted or empty

- manager/integration/tests/test_ha.py
https://github.com/longhorn/longhorn/issues/5014
Split case test_engine_image_missing_on_some_nodes skeleton to below
- test_engine_image_miss_scheduled_perform_volume_operations
- test_engine_image_not_fully_deployed_perform_volume_operations
- test_engine_image_not_fully_deployed_perform_engine_upgrade
- test_engine_image_not_fully_deployed_perform_replica_scheduling
- test_engine_image_not_fully_deployed_perform_autoup_grade_engine
- test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume
> Split case test_engine_image_missing_on_some_nodes skeleton

- docs/content/manual/pre-release/ha/single-replica-node-down.md
Update manual test Single replica node down for strict-local volume in section Node restart/down scenario with `Pod Deletion Policy When Node is Down` set to `delete-both-statefulset-and-deployment-pod`
Ref - longhorn-[4967](https://github.com/longhorn/longhorn/issues/4967)
> doc : Update manual test Single replica node down for strict-local volume

- manager/integration/tests/test_basic.py
- manager/integration/tests/test_recurring_job.py
Fix some failed test cases by increasing volume size after introducing fast lz4 compression method.
longhorn/longhorn#5189
> Enlarge volume size for increasing backup time

- docs/content/manual/release-specific/v1.4.0/test-system-backup.md
- manager/integration/pytest.ini
- manager/integration/tests/backupstore.py
- manager/integration/tests/common.py
- manager/integration/tests/test_system_backup_restore.py
Backport https://github.com/longhorn/longhorn-tests/pull/1191 & https://github.com/longhorn/longhorn-tests/pull/1239 to v1.4.x
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2870/testReport/tests/) on pipeline were passed
https://github.com/longhorn/longhorn/issues/5232
> [BACKPORT][v1.4.x] test(auto/manual): system backup/restore

- docs/content/manual/release-specific/v1.2.3/test-scalability-with-backing-image.md
- docs/content/manual/release-specific/v1.3.0/test-longhorn-manager-starting-scalability.md
- mirror_csi_images/scripts/publish.sh
This PR updates k8s.gcr.io to registry.k8s.io
Part of https://github.com/kubernetes/k8s.io/issues/4780
> Update k8s.gcr.io to registry.k8s.io

- test_framework/terraform/aws/sles/data.tf
- test_framework/terraform/aws/sles/variables.tf
ci: refine sles ami rule to avoid error from ami being deleted
> ci: refine sles ami rule to avoid error from ami being deleted

- manager/integration/tests/test_node.py
test: fix flaky test case test_node_eviction_multiple_volume
by avoiding checking replica running status of an auto-detached volume
For https://github.com/longhorn/longhorn/issues/5475
> test: fix flaky test case test_node_eviction_multiple_volume

- manager/integration/tests/test_recurring_job.py
Update test_recurring_jobs_maximum_retain for adjusted max recurring job retain limit to 100
ref: https://github.com/longhorn/longhorn/issues/5730
> Update test case for adjusted max recurring job retain limit to 100

- manager/integration/tests/common.py
- manager/integration/tests/node.py
- manager/integration/tests/test_support_bundle.py
https://github.com/longhorn/longhorn/issues/5631
https://github.com/longhorn/longhorn/issues/5614
> test(support-bundle): agent with node-selector and taint-toleration

- manager/integration/tests/common.py
Fix this upstream instead.
https://github.com/longhorn/longhorn/issues/5631
https://github.com/longhorn/longhorn/issues/5614
> fix(support-bundle): revert master node taint tolerations

- test_framework/scripts/rancher/terraform/main.tf
test: fix rancher provisioning failure caused by supportBundleManager syntax error
> test: fix rancher provisioning failure caused by supportBundleManager syntax error

- manager/integration/tests/test_provisioner.py
Add case `test_provisioner_fs_format`
Longhorn [5428](https://github.com/longhorn/longhorn/issues/5428)
test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3505/testReport/tests/test_provisioner/)
> test: add case test_provisioner_fs_format

- manager/integration/tests/test_basic.py
test: fix flaky test case test_backup_failed_disable_auto_cleanup by increasing volume size so the backup in-progress state can be caught
For https://github.com/longhorn/longhorn/issues/5838
> test: fix flaky test case test_backup_failed_disable_auto_cleanup

- manager/integration/tests/common.py
- manager/integration/tests/node.py
- manager/integration/tests/test_ha.py
test_engine_image_not_fully_deployed related cases and functions
- prepare_engine_not_fully_deployed_evnironment_with_volumes
- prepare_engine_not_fully_deployed_evnironment
- reset_nodes_taint
- taint_non_current_node
- restart_and_wait_ready_engine_count
- test_engine_image_miss_scheduled_perform_volume_operations
- test_engine_image_not_fully_deployed_perform_volume_operations
- test_engine_image_not_fully_deployed_perform_engine_upgrade
- test_engine_image_not_fully_deployed_perform_replica_scheduling
- test_engine_image_not_fully_deployed_perform_auto_upgrade_engine
ref: longhorn [5014](https://github.com/longhorn/longhorn/issues/5014)
> test_engine_image_not_fully_deployed related cases and functions

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_ha.py
Check if new volume size is smaller than old one in the validator and PVC size is expanded before expanding the volume.
Expansion is not allowed if storage class does not exist.
> fix(expand): expansion behavior changed

- test_framework/terraform/aws/sles/data.tf
ci: refine sles ami filter to avoid using ecs optimized image
it's possible that unable to run any pods on the ecs optimized instance and then causes longhorn installation failed.
> ci: refine sles ami filter to avoid using ecs optimized image

- docs/content/manual/pre-release/node-not-ready/node-down/physical-node-down.md
> Update test cases to exclude RWX from physical node down test cases

- manager/integration/tests/common.py
- manager/integration/tests/test_backing_image.py
- manager/integration/tests/test_basic.py
- manager/integration/tests/test_cloning.py
- manager/integration/tests/test_cluster_autoscaler.py
- manager/integration/tests/test_csi.py
- manager/integration/tests/test_engine_upgrade.py
- manager/integration/tests/test_ha.py
- manager/integration/tests/test_migration.py
- manager/integration/tests/test_node.py
- manager/integration/tests/test_recurring_job.py
- manager/integration/tests/test_scheduling.py
- manager/integration/tests/test_settings.py
- manager/integration/tests/test_stress.py
- manager/integration/tests/test_upgrade.py
> Fix e2e tests to work with new AD mechanism 

- manager/integration/tests/test_csi.py
- manager/integration/tests/test_csi_snapshotter.py
- manager/integration/tests/test_node.py
If `volume.spec.fromBackup` is empty, do not wait for volume restoration finished because the volume doesn't require restoration
> Fix e2e tests

- manager/integration/tests/common.py
test: add try/except for generate support bundle function to avoid internal error
In gke environment, the credential will keep expire and automatically renew during the test running. If the test tries to make requests when the credntial expired and without this try/except, it would cause internal error and fail the whole test process instead of just failing the current test case.
> test: add try/except for generate support bundle function to avoid internal error

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
test: fix flaky test case test_auto_remount_with_subpath
(1) The statefulset pod will be deleted/restarted automatically. If we stick to the to-be-deleted pod and try to read data, we will always get i/o error. Need to access the newly restarted pod.
(2) In the above scenario, the waiting time before the old pod being deleted and a new pod being created could be ~50 seconds long. So the 30s timout is still risky, change it to 90s.
For https://github.com/longhorn/longhorn/issues/6007
> test: fix flaky test case test_auto_remount_with_subpath

- test_framework/terraform/aws/rockylinux/data.tf
- test_framework/terraform/aws/rockylinux/variables.tf
longhorn/longhorn#6088
This change makes use of the official Rocky AMI instead of the one we were using.
Drawbacks:
- Only the latest few versions of Rocky can be used (8.7, 8.9, 9.0, 9.1. 9.2 right now).
Benefits:
- There are ARM versions.
- The latest versions of Rocky are available.
> Change Rocky Linux AMI

- test_framework/terraform/aws/sle-micro/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/sle-micro/user-data-scripts/provision_k3s_server.sh.tpl
After merging https://github.com/k3s-io/k3s/pull/7635, we discovered that when setting up `k3s` on `SUSE Linux Enterprise Micro`, it encountered a permission-related error because it attempted to execute `transactional-update` without using `sudo`.
```bash
suse@ip-172-31-1-245:~> curl -fL https://get.k3s.io/ | sh -s - server --cluster-init --disable-apiserver --disable-controller-manager --disable-scheduler
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 32067  100 32067    0     0   108k      0 --:--:-- --:--:-- --:--:--  108k
[INFO]  Finding release for channel stable
[INFO]  Using v1.26.5+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/sha256sum-amd64.txt …
```
> ci: fix sle-micro transactional-update related error when setup k3s cluster.

- manager/integration/tests/common.py
It needs to change the command instead `awk` because it is not installed in default for the `registry.suse.com/bci/bci-base:15.4`.
Use `pgrep -f` to get the process id.
Regression test for `test_ha.py`:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4055
Local tests
```text
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: order-1.0.1, repeat-0.9.1
collecting ... collected 11 items
test_recurring_job.py::test_recurring_jobs_when_volume_detached_unexpectedly[s3] PASSED [  9%]
test_recurring_job.py::test_recurring_jobs_when_volume_detached_unexpectedly[nfs] FAILED [ 18%] …
```
> fix: change the command for killing processes

- test_framework/scripts/longhorn-setup.sh
ci: wait for csi components created when installing longhorn
For https://github.com/longhorn/longhorn/issues/6111
> ci: wait for csi components created when installing longhorn

- manager/integration/tests/test_kubernetes.py
test: fix test_kubernetes_status and test_backup_kubernetes_status by omitting the 'podStatus': 'Running' check
For https://github.com/longhorn/longhorn/issues/6097
> test: fix test_kubernetes_status and test_backup_kubernetes_status

- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_agent.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_server.sh.tpl
longhorn/longhorn#6088
Tagging this slightly unrelated PR to the above issue since its required to get Rocky testing fully working the way we want/need.
Needed:
1. A rule to allow isciadm the dac_override capability in k3s (only RKE2 provides it by default now).
2. A taint preventing Longhorn from scheduling on the control plane in an RKE2 deployment. Without it, we always fail in [this fixture](https://github.com/longhorn/longhorn-tests/blob/754a03f48d9d75c2655ba64de4cce2221a4fc2b5/manager/integration/tests/common.py#L3319-L3339)
Also rearranged and cleaned up a couple of things for consistency among scripts.
> Rework user data scripts to enable Rocky SELinux testing

- manager/integration/Dockerfile
The `registry.suse.com/bci/python:3.9` image does not have `awk` installed by default. We need to install it.
> Fix awk notfound

- test_framework/terraform/aws/rockylinux/data.tf
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
longhorn/longhorn#6108
The behavior of Longhorn with SELinux "enabled" on RKE2 is different than on k3s. This is because the current k3s deployment scripts don't go far enough to actually enable it.
> Explicitly enable SELinux if it is desired for k3s Rocky testing

- test_framework/Jenkinsfile
- test_framework/scripts/longhorn-setup.sh
- test_framework/terraform/aws/oracle/k3s_instances.tf
- test_framework/terraform/aws/oracle/rke2_instances.tf
- test_framework/terraform/aws/oracle/user-data-scripts/provision_rke2_agent.sh.tpl
- test_framework/terraform/aws/oracle/user-data-scripts/provision_rke2_server.sh.tpl
- test_framework/terraform/aws/rhel/k3s_instances.tf
- test_framework/terraform/aws/rhel/rke2_instances.tf
- test_framework/terraform/aws/rhel/user-data-scripts/provision_rke2_server.sh.tpl
- test_framework/terraform/aws/rockylinux/k3s_instances.tf
- test_framework/terraform/aws/rockylinux/rke2_instances.tf
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_server.sh.tpl
ci: apply selinux workaround to fix iscsiadm permission issue
1. apply selinux workaround to oracle/rocky/rhel to fix iscsiadm permission issue
2. correct selinux_mode parameter passing to make permissive/enforcing mode can be set correctly in the selinux enabled instances
3. fix missing NoSchedule taint in rke2 setup script for some distros to make tests can be run on these rke2 clusters
4. stop firewalld in oracle rke2 setup script otherwise the cluster setup will fail
For https://github.com/longhorn/longhorn/issues/6168
> ci: apply selinux workaround to fix iscsiadm permission issue

- manager/integration/tests/test_basic.py
test: fix flaky test case test_default_storage_class_syncup
The k8s api calls read_storage_class and delete_storage_class are actually flaky in this scenario. 
Somehow they encounter storage class "longhorn" not found randomly.
Add for loop and try/catch to make it retry.
For https://github.com/longhorn/longhorn/issues/6141
> test: fix flaky test case test_default_storage_class_syncup

- manager/integration/deploy/test.yaml
ci: fix unable to cp junit report in selinux enforcing mode
For https://github.com/longhorn/longhorn/issues/6187
> ci: fix unable to cp junit report in selinux enforcing mode

- test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/rhel/data.tf
- test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl
ci: explicitly enable selinux if it's desired for k3s rhel/oracle testing
Sync https://github.com/longhorn/longhorn-tests/pull/1426 to rhel and oracle
> ci: explicitly enable selinux if it's desired for k3s rhel/oracle testing

- manager/integration/tests/test_ha.py
There is a low chance that previous restored snapshot is not deleted and counted with restored snapshot this time at step 16 of the test case `test_inc_restoration_with_multiple_rebuild_and_expansion`
Modified to be that wait for snapshot counts as expected.
Ref: longhorn/longhorn#5496
> fix: wait for snapshot counts of a DR volume

- manager/integration/tests/common.py
test: fix flaky test case test_setting_concurrent_volume_backup_restore_limit by longer timeout
For https://github.com/longhorn/longhorn/issues/6260
> test: fix flaky test case test_setting_concurrent_volume_backup_restore_limit by longer timeout

- manager/integration/tests/test_csi_snapshotter.py
- pipelines/gke/scripts/longhorn-setup.sh
- test_framework/scripts/longhorn-setup.sh
Update CSI external-snapshotter version to `v6.2.1`
ref: [6283](https://github.com/longhorn/longhorn/issues/6283)
After upgrade CSI external-snapshotter version,  use `snapshot.storage.k8s.io/v1beta1` to create VolumesnapshotClass, VolumeSnapshotContent, VolumeSnapshot despertched.
Change `snapshot.storage.k8s.io/v1beta1` to `snapshot.storage.k8s.io/v1` in test script.
> Update CSI external-snapshotter version to v6.2.1

- manager/integration/tests/test_basic.py
Add test skeleton for test case `test_backuptarget_invalid`
ref: [1249](https://github.com/longhorn/longhorn/issues/1249)
> Add test skeleton for test case test_backuptarget_invalid

- build_engine_test_images/terraform/aws/ubuntu/variables.tf
The [build-engine-test-images pipeline](https://ci.longhorn.io/job/private/job/build-engine-test-images/) was failing. Since the engine identity PRs bumped engine versions, this pipeline needed to run to allow [live upgrade tests to pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4754/). The live upgrade tests were specifically failing because they couldn't pull an image tagged `longhornio/longhorn-test:upgrade-test.9-3.5-3.1-1`. However, there was an engine called `longhornio/longhorn-test:upgrade-test.9-3.5-3.1-1-amd64` in Docker Hub. This [block of code](https://github.com/longhorn/longhorn-tests/blob/52653904465252c91f2ad3929ca65d17a611f0fd/build_engine_test_images/scripts/generate_images.sh#L58-L62) is responsible for pushing the multi-architecture manifest …
> Change aws_availability_zone from us-east-1c to 1b

- .drone.yml
- manager/integration/Dockerfile
- manager/integration/deploy/test.yaml
- manager/integration/tests/conftest.py
- manager/integration/tests/test_upgrade.py
- pipelines/helm/Dockerfile.setup
- pipelines/helm/Jenkinsfile
- pipelines/helm/scripts/build.sh
- pipelines/helm/scripts/cleanup.sh
- pipelines/helm/scripts/download-support-bundle.sh
- pipelines/helm/scripts/longhorn-setup.sh
- pipelines/helm/scripts/terraform-setup.sh
- pipelines/helm/scripts/upgrade-longhorn.sh
- pipelines/templates/aws_cred_secrets.yml
- pipelines/utilities/create_aws_secret.sh
- pipelines/utilities/create_longhorn_namespace.sh
- pipelines/utilities/install_backupstores.sh
- pipelines/utilities/install_csi_snapshotter.sh
- pipelines/utilities/kubeconfig.sh
- pipelines/utilities/longhorn_helm_chart.sh
- pipelines/utilities/longhorn_status.sh
- pipelines/utilities/run_longhorn_test.sh
ci: implement helm install/upgrade regression test pipeline
(1) add a separate independent pipeline for helm to avoid heavy Jenkinsfile and longhorn-setup.sh
(2) implement refresh install longhorn helm chart and run regression test
(3) implement (2 stage) upgrade longhorn helm chart for test_upgrade
(4) for setup scripts, separate common functions into utility functions for code reuse
For https://github.com/longhorn/longhorn/issues/3987 https://github.com/longhorn/longhorn/issues/5936
> ci: implement helm install/upgrade regression test pipeline

- test_framework/terraform/aws/sles/k3s_instances.tf
- test_framework/terraform/aws/sles/rke2_instances.tf
- test_framework/terraform/aws/sles/rke_instances.tf
- test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/sles/user-data-scripts/provision_rke.sh
- test_framework/terraform/aws/sles/user-data-scripts/provision_rke2_agent.sh.tpl
- test_framework/terraform/aws/sles/user-data-scripts/provision_rke2_server.sh.tpl
longhorn/longhorn#6504
Changes:
1. Don't create worker instances until we are sure a route to the internet is available.
2. Fail immediately if packages can't be installed (`set -e` in all user-data-scripts).
3. Always manually attempt to register with SUSE servers before installing packages.
> Ensure SLES registration is complete before zypper install

- manager/integration/tests/common.py
- manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/6382
The [Volume Replica Rebuilding Speedup](https://github.com/longhorn/longhorn/issues/4783) feature was introduced as an enhancement in `1.4.0`
The current timeout value for checking the rebuild status may not be sufficient for `v1.3.x`.
To address this, we propose extending the timeout for checking the rebuild volume status on `v1.3.x` branch.
The execution time for each test case to approximately 15-20 minutes.
Private image test result
> Fix flaky test_setting_concurrent_rebuild_limit Extend Volume Rebuild Timeout

- manager/integration/tests/backupstore.py
- manager/integration/tests/test_basic.py
Add test case `test_backuptarget_invalid`
ref: [6638](https://github.com/longhorn/longhorn/issues/6638)
Backup in error state did not have correspond `backupvolume` so in test case I cannot utilize below functions. That's the reason I use k8s API to get/delete backup which in error state
- [delete_backup](https://github.com/longhorn/longhorn-tests/blob/f3324d7535b6f76dd46696c9ec17935ff4123cd0/manager/integration/tests/common.py#L474)
- [find_backup](https://github.com/longhorn/longhorn-tests/blob/f3324d7535b6f76dd46696c9ec17935ff4123cd0/manager/integration/tests/common.py#L3613)
~longhorn-test pod need to delete backup through k8s API, I modified `ClusterRole` `longhorn-test-role` add permission for pod longhorn-test~ (no need after this …
> add test case test_backuptarget_invalid

- e2e/tests/node_reboot.robot
test: make volume type configurable for reboot volume node test case to test both rwo and rwx volume
> test: make volume type configurable for reboot volume node test case

- e2e/libs/network/network.py
```
Setup failed:
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Also teardown failed:
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
Should return default if the variable does not exist.
> fix(negative): get_variable_value "NoneType" error

- e2e/libs/engine/crd.py
```
Getting the volume vol-v7f6au engine on the node ip-10-0-2-85 state
Failed getting volume vol-v7f6au engine state: 'CRD' object has no attribute 'cr_api'
```
> fix(negative): 'CRD' object has no attribute 'cr_api'

- manager/integration/tests/test_basic.py
Fix flaky `test_backuptarget_invalid` by increase loop time from 3 sec to 30 sec.
Test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/355/testReport/tests/test_basic/) (20 times)
> fix flaky test_backuptarget_invalid by increase loop time

- manager/integration/tests/test_csi.py
After upgrading csi-node-driver-registrar to v2.9.0, deleting the PVC also deletes the PV due to the PV reclaim policy.
ref: https://github.com/longhorn/longhorn/issues/6916
> fix(integration): csi_minimal_volume_size

- manager/integration/tests/test_ha.py
longhorn/longhorn#6905
The behavior requested in longhorn/longhorn#2103 was already added with the inclusion of the allow-volume-creation-with-degraded-availability setting. This PR adds a test with that setting on and confirms volume restoration completes. Because it is so similar to a couple of other tests, it refactors all three tests to use the same base functionality.
- [test_single_replica_unschedulable_restore_failure (new) results](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5057/testReport/tests/test_ha/)
- [test_rebuild_with_restoration results](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5059)
- [test_single_replica_restore_failure results](test_single_replica_restore_failure)
- [test_single_replica_unschedulable_restore_failure (new) …
> Refactor restoration tests with replica failure and add one

- manager/integration/tests/common.py
- manager/integration/tests/requirements.txt
- manager/integration/tests/test_metric.py
Add test case `test_volume_metrics`
ref: [4029](https://github.com/longhorn/longhorn/issues/4029)
Each metirc has validated values in  label `node`, `pvc` and `volume`
And for the metric value validation please see below table
| metric  | description |  
|---|---|
| longhorn_volume_actual_size_bytes | assert `volume.controllers[0].actualSize ` | 
| longhorn_volume_capacity_bytes  | assert `volume.size` | 
| longhorn_volume_state |  some items not test because timing issue <br> &#10004; attached <br /> <br> &#10004; detached <br /> <br> &#10007; creating <br /> <br> &#10007; attaching <br /> <br> &#10007; etaching <br /> <br> &#10007; deleting </br>| 
| longhorn_volume_robustness| the item not test is because pytest did not support node down scenario<br> &#10004; healthy </br> <br> …
> add case test_volume_metrics

- manager/integration/tests/test_metric.py
Rename and replace the hardcoded label keys to make the function `check_volume_metric` more generic.
> refactor(integration): make `check_volume_metric` a generic function

- manager/integration/tests/test_node.py
longhorn/longhorn#7210
The node controller refuses to update a node until its disk monitor has synced. In v1.6.0, the node controller is responsible for triggering replica eviction. This means it may take longer for replica eviction to start than it did in the past. In the long term, we may want to try to tighten up this timing again, but unfortunately, there is no obvious and easy way to do so.
test_disk_eviction_with_node_level_soft_anti_affinity_disabled is currently failing because it does not wait long enough for a replica to be evicted from one disk before checking for it on another. This PR ensures the eviction process has started before proceeding to do the check.
> Fix test_disk_eviction_with_node_level_soft_anti_affinity_disabled

- mirror_csi_images/scripts/publish.sh
ci: enable mirror support-bundle-kit in mirror-csi-images pipeline
For https://github.com/longhorn/longhorn/issues/7286
> ci: enable mirror support-bundle-kit in mirror-csi-images pipeline

- test_framework/scripts/longhorn-setup.sh
ci: install different version of external-snapshotter based on longhorn-images.txt
For https://github.com/longhorn/longhorn/issues/7383
> ci: install different version of external-snapshotter based on longhorn-images.txt

- docs/content/manual/release-specific/v1.6.0/test-upgrade-responder-collectiing-average-sizes-for-v1-volumes-only.md
https://github.com/longhorn/longhorn/issues/7380
> test(manual): upgrade-responder collect average sizes for v1 volumes only

- test_framework/scripts/longhorn-setup.sh
ci: fix wrong longhorn-images.txt path for external-snapshotter installation
For https://github.com/longhorn/longhorn/issues/7383
> ci: fix wrong longhorn-images.txt path for external-snapshotter installation

- manager/integration/tests/common.py
Analysis https://github.com/longhorn/longhorn/issues/7438#issuecomment-1870733295
longhorn/longhorn#7438
Test passed 50 times:
```bash
➜  .kube k exec -it longhorn-test -- bash
Defaulted container "longhorn-test" out of: longhorn-test, longhorn-test-report
longhorn-test:/integration/tests # pytest -svvlx test_basic.py::test_engine_image_daemonset_restart --count=50
============================================================================ test session starts ============================================================================
platform linux -- Python 3.9.18, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: repeat-0.9.1, order-1.0.1
collected 50 items …
```
> Fix flaky test test_engine_image_daemonset_restart

- manager/integration/tests/run.sh
ci: enable live logging in pytest by disabling python buffer
For https://github.com/longhorn/longhorn/issues/7490
> ci: enable live logging in pytest by disabling python buffer

- manager/integration/tests/common.py
test: fix flaky test case test_ha_salvage
By separate the `pgrep` command from the `kill` command. The original command format will cause the `pgrep` command also selects the `kill` process itself in addition to the `engine-binary` process, and potentially cause the `kill` process being killed by itself first, so no `engine-binary` process will be killed.
Normally it won't happen because the pid is increasing, a newly created process always has a large pid than an old process, which means the `kill` process always has a large pid than the `engine-binary` process. In this case, the `engine-binary` process will be killed first, and then the `kill` process, the test case won't fail.
But when the pid wraps around at `32768`, the newly created `kill` process gets assigned to a small pid (e.g. …
> test: fix flaky test case test_ha_salvage

- manager/integration/tests/common.py
- pipelines/utilities/longhorn_status.sh
- test_framework/scripts/longhorn-setup.sh
1. Fix error log "Found unknown instance manager"
When we found an instance manager with the correct type but not in the
running state, don't print out the log "Found unknown instance manager"
because it is misleading
The function wait_for_instance_manager_desire_state() below it already
taking care of waiting for the instance manager to be running.
1. Fix bug failed to find a node that is ready and has the default engine image
Wait for the engine image pods to be running before starting the tests
longhorn/longhorn#7413
>  Fix error log "Found unknown instance manager" and bug failed to find a node that is ready and has the default engine image

- manager/integration/deploy/test.yaml
- manager/integration/tests/aws.py
- manager/integration/tests/test_infra.py
- test_framework/scripts/longhorn-setup.sh
- test_framework/scripts/terraform-setup.sh
- test_framework/terraform/aws/oracle/output.tf
- test_framework/terraform/aws/rhel/output.tf
- test_framework/terraform/aws/rockylinux/output.tf
- test_framework/terraform/aws/sle-micro/output.tf
- test_framework/terraform/aws/sles/output.tf
- test_framework/terraform/aws/ubuntu/output.tf
test: fix flaky test case test_offline_node
Adding resource suffix filter to select the correct ec2 instance to be powered off. Originally it only used instance private ip to select the instance, but private ip is not unique, so it's possible to power off the wrong instance which belongs to another cluster instead of the current test case running cluster.
For https://github.com/longhorn/longhorn/issues/7463
> test: fix flaky test case test_offline_node

- manager/integration/tests/common.py
test: fix flaky test case test_volume_reattach_after_engine_sigkill
The pod we're waiting could be terminated and recreated, so reading the pod could raise not found exception. Wrapping it in try/except to make the waiting continue.
For https://github.com/longhorn/longhorn/issues/7491
> test: fix flaky test case test_volume_reattach_after_engine_sigkill

- manager/integration/tests/common.py
test: avoid exception if env variable isn't set
For https://github.com/longhorn/longhorn/issues/7533
> test: avoid exception if env variable isn't set

- build_engine_test_images/Dockerfile.setup
- build_engine_test_images/Jenkinsfile
- build_engine_test_images/run.sh
Revert "ci: check if new engine test images need to be published"
This reverts commit d4b540af193895682716638e2a7a3cb290998c6e.
> Revert "ci: check if new engine test images need to be published"

- manager/integration/pytest.ini
```
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323: PytestUnknownMarkWarning: Unknown pytest.mark.volume_backup_restore - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
warnings.warn(
```
> fix(integration): unknown pytest.mark.volume_backup_restore

- manager/integration/tests/common.py
The test CI deploys Longhorn with the setting value longhorn-critical for the setting priority-class. Don't reset it to empty (which is the default value defined in longhorn-manager code) because this will restart Longhorn managed components and fail the test cases.
longhorn/longhorn#7413
More details are at https://github.com/longhorn/longhorn/issues/7413#issuecomment-1881707958
> Fix Longhorn managed components restart at the begining of a test

- manager/integration/tests/common.py
ref: https://github.com/longhorn/longhorn/issues/7543
BackupVolume is not synced, so the BackingImage field is empty
This leads to the failure when creating Volume. Admission-webhook will denied the request because the BackupVolume.BackingImage is not the same as Volume.BackingImage
> fix: find backup should also wait until backup volume is synced

- docs/content/manual/release-specific/v1.6.0/test-list-backup-when-cluster-has-node-cordoned-before-longhorn-installation.md
> test(manual): cordoned node controller renders the backup target unusable

- manager/integration/tests/common.py
- manager/integration/tests/test_engine_upgrade.py
Modified the test case `test_engine_image_incompatible` by new introduced status field `incompatible`.
Ref: longhorn/longhorn#7683, longhorn/longhorn#7539
> fix(engineimage): new status `incompatible`.

- docs/content/manual/pre-release/environment/cluster-using-customized-kubelet-root-directory.md
> fix(manual): missing example to customize kubelet root dir for workers

- docs/content/manual/release-specific/v1.6.0/test-engine-version-enforcement.md
Issue longhorn/longhorn#5842, longhorn/longhorn#7539
Modify the manual test case for engine version enforcement.
> test: new field `Incompatible` of EngineImage

- test_framework/terraform/aws/sles/variables.tf
15-sp4 is not found anymore
```
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.aws_ami_sles,
│   on data.tf line 6, in data "aws_ami" "aws_ami_sles":
│    6: data "aws_ami" "aws_ami_sles" {
│ 
```
> Update sles distro to 15-sp5

- manager/integration/tests/test_ha.py
Issue longhorn/longhorn#7782
Increase data size in volume make volume restore have longer time. or test case failed on Rocky Linux 9.3 ARM64
Before fix
- [test_rebuild_with_restoration](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/14/testReport/junit/tests/test_ha/test_rebuild_with_restoration_nfs_)
- [test_single_replica_restore_failure[nfs]](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/14/testReport/junit/tests/test_ha/test_single_replica_restore_failure_nfs_)
After fix
- [test_single_replica_restore_failure](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/17/testReport/tests/test_ha/)
- …
> Fix flaky test_rebuild_with_restoration

- manager/integration/tests/test_recurring_job.py
ref: https://github.com/longhorn/longhorn/issues/7744
1. If we run the tests 100 times, the previous test could still be in the process of being cleaned up while the next one starts running
So we should use random volume name to prevent backup lock issue because of the same name.
2. We should get the volume after Backup is ready, or the Volume.BackupStatus will not be correct
> fix(test): fix recurring_job_restored_from_backup_test

- manager/integration/tests/test_backing_image.py
Resolves issue longhorn/longhorn#7611 by fixing a flaky test case. 
The private image test results for different platforms are as follows:
1. sles amd64 : [link](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5951/)
2. sles arm64  : [link](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5952/)
3. ubuntu arm64  : [link](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5953/)
> Fix flaky test_volume_wait_for_backing_image_condition on ubuntu arm64

- docs/content/manual/pre-release/resiliency/pvc_provisioning_with_insufficient_storage.md
longhorn/longhorn#7650
longhorn/longhorn#7650
We have the ticket  longhorn/longhorn#6461 `[IMPROVEMENT] Provide more information for volume scheduling failure`. Our test case requires an update to ensure improved clarity and coverage.
@derekbit @jillian-maroket 
- longhorn/longhorn#6461
> test(manual): Update PVC provisioning with insufficient storage

- pipelines/utilities/argocd.sh
PR https://github.com/longhorn/website/pull/866
The pre-upgrade checker job is actually `preUpgradeChecker.jobEnabled: false` when using the Helm chart for `v1.6.0`.
> ci: update disabling pre-upgrade checker setting for argocd

- mirror_csi_images/scripts/publish.sh
N/A
I discovered the issue while working on longhorn/longhorn#7428
The CSI mirroring scripts ignore images that aren't prefixed with `csi-` or `support-bundle-kit`. However, we need to mirror `registry.k8s.io/sig-storage/livenessprobe` in the same way as `registry.k8s.io/sig-storage/csi...` images. My attempt to mirror a new version of livenessprobe (https://ci.longhorn.io/job/private/job/mirror-csi-images/16/) failed.
I was surprised by the need to leave `csi-|livenessprobe` unquoted, but according to both ShellCheck and my testing it is correct when pattern matching (https://www.shellcheck.net/wiki/SC2076).
It looks like this used to work in the environment variable case, but changes in https://github.com/longhorn/longhorn-tests/pull/1625 broke it.
> Fix automated mirroring of livenessprobe

- manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn/issues/7988
Fix flaky test case test_space_usage_for_rebuilding_only_volume in rockylinux arm64 by increasing the timeout value.
> test: fix flaky test case test_space_usage_for_rebuilding_only_volume in rockylinux arm64

- manager/integration/tests/common.py
Issue N/A
Fix wrong pvc status check. It was wrongly hard-coded to "bound".
> test: fix wrong pvc status check

- manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/8001
fix flaky test case test_auto_detach_volume_when_node_is_cordoned by increasing the retry count.
> test: fix flaky test case test_auto_detach_volume_when_node_is_cordoned

- manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/7438
Test case `test_engine_image_daemonset_restart` is still flaky after https://github.com/longhorn/longhorn-tests/pull/1642: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6300/, so increase `state_count` to wait longer.
> test: fix flaky test case test_engine_image_daemonset_restart

- manager/integration/tests/test_engine_upgrade.py
Add skeleton for test_engine_crash_during_live_upgrade
ref: [7859](https://github.com/longhorn/longhorn/issues/7859)
Issue longhorn/longhorn#7859
> Add skeleton for test_engine_crash_during_live_upgrade

- manager/integration/Dockerfile
- manager/integration/tests/requirements.txt
Issue https://github.com/longhorn/longhorn/issues/8049
fix build test image failed.
> ci: fix build test image failed

- test_framework/scripts/longhorn-setup.sh
Issue #7521
Delete upgrade test pod after receving test report. Otherwise the pod will affect drain test cases because the upgrade test pod does not have a controller to drain normally.
```
+ kubectl delete -f /src/longhorn-tests/manager/integration/deploy/upgrade_test.yaml
serviceaccount "longhorn-test-service-account" deleted
clusterrolebinding.rbac.authorization.k8s.io "longhorn-test-bind" deleted
pod "longhorn-test-upgrade-from-stable" deleted
+ LONGHORN_UPGRADE_TYPE=from_transient
+ LONGHORN_UPGRADE_TEST_POD_NAME=longhorn-test-upgrade-from-transient
```
N/A
> ci: delete upgrade test pod

- manager/integration/tests/test_metric.py
Issue  longhorn/longhorn#7626
According to the [fail](https://github.com/longhorn/longhorn/issues/7626#issuecomment-1965757650) scenario on v1.5.x, add loop to check metric `longhorn_volume_actual_size_bytes` value.
60 times test result
- [master](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6512/testReport/tests/test_metric/)
- [v1.6.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6513/testReport/tests/test_metric/)
- [v1.5.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6526/testReport/tests/test_metric/)
N/A
> Fix flaky test_volume_metrics

- manager/integration/tests/test_scheduling.py
longhorn/longhorn#8011
https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_scheduling.py#L443C8-L443C51
Add `wait_for_volume_healthy` before deleting replicas to wait for volume rebuilding to complete, and avoid the error `failed to remove replica: no other healthy replica available`.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6439/consoleText
jenkins test result: 
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6442/
> test: fix flaky test case `test_replica_rebuild_per_volume_limit`

- manager/integration/tests/test_csi_snapshotter.py
Issue https://github.com/longhorn/longhorn/issues/8046
fix flaky test case `test_csi_volumesnapshot_restore_pre_provision_backing_image` by increasing snapshot deletion wait timeout.
> test: fix flaky test case test_csi_volumesnapshot_restore_pre_provision_backing_image

- docs/content/manual/release-specific/v1.7.0/test-kubelet-restart-no-pending-pod-event.md
Updating the title as our frontend of https://longhorn.github.io/longhorn-tests/manual/ framework depends on this text to build the page. A page with no `title` won't appear on the https://longhorn.github.io/longhorn-tests/manual/
Also, using different text breaks our automation to sync the test cases in Qase.
Ref - https://github.com/longhorn/longhorn-tests/actions/runs/8115565903
> Update title test-kubelet-restart-no-pending-pod-event

- pipelines/utilities/rancher/terraform_install/main.tf
- pipelines/utilities/rancher/terraform_upgrade/main.tf
longhorn/longhorn#8095
When the `LONGHORN_REPO` is set to `longhornio`, we need to update the `livenessProbe.repository` value to `longhornio/livenessprobe` in the Rancher chart.
https://github.com/longhorn/longhorn/issues/8095#issuecomment-1977976920
> ci: Update livenessProbe.repository value in Rancher chart

- manager/integration/tests/test_csi.py
longhorn/longhorn#8009
This is a skeleton for an automated version of https://github.com/longhorn/longhorn-manager/pull/2644#issuecomment-1961916781.
> Skeleton for test restage volume if NodeStageVolume not called

- manager/integration/tests/test_metric.py
Issue #7626
Improve the test case stability. The origin code have a chance to get value `0` by `actual_size = float(volume.controllers[0].actualSize)` because timing issue lead the test case [fail](https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-upgrade-tests-sles-arm64/320/testReport/junit/tests/test_metric/test_volume_metrics_default_/). Update test code to write fixed data size and verify metric `longhorn_volume_actual_size_bytes` with the fixed data size.
100 times test result
- [master](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6598/)
- [v1.6.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6599/)
- [v1.5.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6600/)
N/A
N/A
> test: fix flaky test case test_volume_metrics

- e2e/libs/workload/workload.py
Issue longhorn/longhorn#8193
Check whether the retry count exceeds the `WAIT_FOR_POD_STABLE_MAX_RETRY` instead of verifying the exact match to avoid the loop.
`None`
https://github.com/longhorn/longhorn/issues/8193#issuecomment-2006061894
> fix(negative): wait_for_workload_pods_stable

- manager/integration/tests/test_provisioner.py
longhorn/longhorn#8198
longhorn/longhorn#8198 uncovered the fact that a change had unknowingly broken Longhorn generic ephemeral volumes. We need an automated test to ensure this can't happen in the future.
I wasn't really sure if this skeleton fit best in `test_provisioner.py` (since we want to test the ability to provision generic ephemeral volumes) or `test_kubernetes.py`, since the actual change I made in https://github.com/longhorn/longhorn-manager/pull/2701 ensures `volume.status.kubernetesStatus.workloadStatus` was correctly populated by the Longhorn Kuberntes PV controller. I went with my gut, but I'm fine with moving it if QA thinks it makes better sense elsewhere.
> Add test_provisioner_generic_ephemeral skeleton

- manager/integration/tests/test_node.py
Issue longhorn/longhorn#7859
Correct the indent in test case `test_drain_with_block_for_eviction_if_contains_last_replica_success`
N/A
https://github.com/longhorn/longhorn-tests/pull/1823#discussion_r1533532611
> fix: indent of create_deployment_and_write_data

- manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/8183
Adds a check for timeout when waiting for deployment to create successfully.
> fix: check for timeout in wait_deployment_replica_ready and fail if so.

- manager/integration/tests/common.py
longhorn/longhorn#8231
Check if the backup volume exists and has been created before proceeding with the backing image synchronization check. 
This addresses the case where the backup volume might not have been created yet.
amd64 : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6658/
arm64 : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6659
> test: fix flaky test case `test_ha_backup_deletion_recovery`

- manager/integration/tests/test_metric.py
Fix flaky [test_node_metrics](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/862/testReport/junit/tests/test_metric/test_node_metrics/)
```
found_metric = Sample(name='longhorn_node_status', labels={'condition': 'schedulable', 'condition_reason': '', 'node': 'ip-10-0-2-55'}, value=1.0, timestamp=None, exemplar=None)
metric_labels = {'condition': 'schedulable', 'condition_reason': 'KubernetesNodeCordoned', 'node': 'ip-10-0-2-55'}
expected_value = 0.0
def examine_metric_value(found_metric, metric_labels, expected_value=None):
for key, value in metric_labels.items():
>           assert found_metric.labels[key] == value
E           AssertionError: assert '' == 'KubernetesNodeCordoned'
E             - KubernetesNodeCordoned
test_metric.py:125: …
```
> Fix flaky test_node_metrics

- manager/integration/tests/common.py
- manager/integration/tests/test_basic.py
ref: https://github.com/longhorn/longhorn/issues/8269
Refactor the code to test the true purpose of this test
When creating Backup during previous Backup deletion, the Backup should be failed because of the lock
So adjust the code to
1. Create the first Snapshot1 and Backup1
2. Create the second Snapshot2
3. Delete the first Backup1
4. Create the second Backup2
5. Backup2 should be failed
6. Wait for Backup1 to be deleted
7. Create third Snapshot3 and Backup3
8. Backup3 should be completed.
> fix(backup lock): fix test case to follow the test purpose

- docs/content/manual/release-specific/v1.7.0/test-gke-container-optimized-os-dependency-setup.md
- manager/integration/tests/common.py
- manager/integration/tests/test_zone.py
Issue longhorn/longhorn#6165
- Integration: The `replica_auto_balance_zone` test cases failed when Kubernetes is running on GKE with COS_CONTAINERD. This is because the node zone label is periodically updated with the actual GCP zone. To address this, implement a workaround by refreshing the zone label with each retry iteration to maintain the expected zone label.
- Manual: test dependencies configure/setup.
Skip zone-related tests when the cluster is running on COS.
`None`
`None`
> test(integration/manual): support GKE Container-Optimized OS

- manager/integration/tests/test_metric.py
Issue longhorn/longhorn#8268
Test case flaky due to sometimes `delete_replica_processes` not make volume faulted. Add retry to make sure volume faulted before check Longhorn metric.
100 times test result on [master](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6687/ ) and [v1.6.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6689/)
N/A
> fix: flaky test_volume_metircs

- manager/integration/tests/test_settings.py
Issue longhorn/longhorn#8318
Fix failed test case [test_instance_manager_cpu_reservation](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/880/testReport/junit/tests/test_settings/test_instance_manager_cpu_reservation/)
N/A
> fix: fix failed test_instance_manager_cpu_reservation

- manager/integration/tests/test_zone.py
Issue longhorn/longhorn#6165
Missing zone label setup. This is a side-effect from https://github.com/longhorn/longhorn-tests/pull/1819.
https://github.com/longhorn/longhorn/issues/6165#issuecomment-2042214247
`None`
> fix(integration): test_replica_auto_balance_node_duplicates_in_multiple_zones

- e2e/keywords/common.resource
- e2e/libs/backupstore/__init__.py
- e2e/libs/backupstore/base.py
- e2e/libs/backupstore/minio.py
- e2e/libs/backupstore/nfs.py
- e2e/libs/keywords/backupstore_keywords.py
- e2e/libs/longhorn.py
- e2e/libs/recurringjob/recurringjob.py
- e2e/libs/recurringjob/rest.py
- e2e/libs/setting/__init__.py
- e2e/libs/setting/constant.py
- e2e/libs/setting/setting.py
- e2e/requirements.txt
- pipelines/utilities/run_longhorn_e2e_test.sh
test: implement backupstore setup
(1) add backupstore.py for robot test cases
(2) only support s3 now, the subprocess parts in backupstore.py need to be refined to make nfs work
(3) fix wrong longorn client url issue when using it out-of-cluster (the same issue as https://github.com/longhorn/longhorn-tests/pull/1300#discussion_r1273250265)
For https://github.com/longhorn/longhorn/issues/6710
> test(negative): implement backupstore setup

- test_framework/Dockerfile.setup
Issue https://github.com/longhorn/longhorn/issues/7166
fix go tool cover error: go.mod requires go >= 1.22.2
> ci: fix go tool cover error: go.mod requires go >= 1.22.2

- e2e/keywords/common.resource
- e2e/keywords/storageclass.resource
- e2e/libs/keywords/storageclass_keywords.py
- e2e/libs/keywords/workload_keywords.py
- e2e/libs/storageclass/__init__.py
- e2e/libs/storageclass/storageclass.py
- e2e/libs/utility/constant.py
- e2e/libs/utility/utility.py
- e2e/libs/workload/workload.py
Issue longhorn/longhorn#8440
Create 1 replica storageclass `longhorn-test-1-replica` and 2 replicas storageclass `longhorn-test-2-replicas` at test step for PVC use
Local test code
```robot 
*** Test Cases ***
Replica Test
Given Create persistentvolumeclaim 0 using RWO volume
And Create persistentvolumeclaim 1 using RWO volume with 1-replica storageclass
And Create persistentvolumeclaim 2 using RWO volume with 2-replicas storageclass
And Create deployment 0 with persistentvolumeclaim 0
And Create deployment 1 with persistentvolumeclaim 1
And Create deployment 2 with persistentvolumeclaim 2
```
[report.zip](https://github.com/longhorn/longhorn-tests/files/15127237/report.zip)
> test(robot): add storageclass for different replica count

- test_framework/scripts/longhorn-setup.sh
Issue N/A
fix unable to specify custom longhorn repo
> ci: fix unable to specify custom longhorn repo

- e2e/keywords/backing_image.resource
- e2e/keywords/common.resource
- e2e/libs/backing_image/__init__.py
- e2e/libs/backing_image/backing_image.py
- e2e/libs/backing_image/base.py
- e2e/libs/backing_image/rest.py
- e2e/libs/keywords/backing_image_keywords.py
- e2e/libs/keywords/volume_keywords.py
- e2e/libs/volume/crd.py
- e2e/libs/volume/volume.py
- e2e/tests/regression/test_backing_image.robot
migrate test_backing_image_basic_operation
> test(robot): migrate test_backing_image_basic_operation

- manager/integration/tests/common.py
- manager/integration/tests/test_csi.py
longhorn/longhorn#8488
Don't attempt to create XFS file systems that are smaller than 300 MiB.
- Without this PR, test_xfs_pv fails: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/906/testReport/.
- With this PR, text_xfs_pv passes: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6782/testReport/tests/test_csi/.
> Don't test with XFS volumes smaller than 300 MiB

- e2e/Dockerfile
- manager/integration/Dockerfile
- manager/integration/tests/requirements.txt
- mirror_csi_images/Dockerfile.setup
This reverts commit 5a5759b5abf7263b47cd57930503b7efa613d159.
Issue N/A
Revert python version from 3.12 back to 3.11. Because kubernetes python client doesn't officially support python 3.12.
> Revert "chore(deps): update docker dependencies"

- benchmark_test/scripts/benchmark-test-setup.sh
Issue longhorn/longhorn#8568
After [89270bf](https://github.com/longhorn/longhorn/commit/89270bf0fabe40dcffe4eb8b345ca21326ae6b0c) was merged, we also need to update [Uninstal Longhorn step](https://github.com/longhorn/longhorn-tests/blob/master/benchmark_test/scripts/benchmark-test-setup.sh#L231). 
https://github.com/longhorn/longhorn/commit/89270bf0fabe40dcffe4eb8b345ca21326ae6b0c
https://ci.longhorn.io/job/private/job/longhorn-benchmark-test/
> test: specify the namespace when uninstall Longhorn

- e2e/libs/workload/pod.py
- e2e/libs/workload/workload.py
Issue longhorn/longhorn#8550
https://github.com/longhorn/longhorn/issues/8550#issuecomment-2109276522
> fix(robot): skip kubelet terminated pod in get_workload_pods

- test_framework/Jenkinsfile
Issue https://github.com/longhorn/longhorn/issues/8588
only keep the last coverage profile and archive at project level instead of build level to save disk space
> ci: only keep the last coverage profile and archive at project level instead of build level to save disk space

- e2e/keywords/common.resource
- e2e/keywords/host.resource
- e2e/keywords/persistentvolumeclaim.resource
- e2e/keywords/statefulset.resource
- e2e/keywords/workload.resource
- e2e/libs/host/host.py
- e2e/libs/keywords/host_keywords.py
- e2e/libs/keywords/volume_keywords.py
- e2e/libs/keywords/workload_keywords.py
- e2e/libs/persistentvolumeclaim/crd.py
- e2e/libs/persistentvolumeclaim/persistentvolumeclaim.py
- e2e/libs/volume/crd.py
- e2e/libs/volume/rest.py
- e2e/libs/volume/volume.py
- e2e/libs/workload/constant.py
- e2e/libs/workload/workload.py
- e2e/templates/workload/statefulset.yaml
- e2e/tests/test_cases/single_replica_node_down.robot
Issue longhorn/longhorn#8350
Make manual test case [Single replica node down](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-down/single-replica-node-down/) an automtaion test case
1. Create workload with `3` replicas then set the PVC replica count to `1`. After that,  delete specific replicas to make volume and the only one replica located on the same node or on diffent node. In the end power off the volume node to observe workload become ready or not by setting `node-down-pod-deletion-policy` and the only one replica locality.
2. And when volume faluted, the nodeID field is empty so it need `power_on_all_nodes` to boot up off node.
[test-report.zip](https://github.com/longhorn/longhorn-tests/files/15198264/test-report.zip)
> test(robot): add single replica node down cases

- docs/content/manual/release-specific/v1.7.0/test-support-bundle-node-collection-timeout.md
Issue longhorn/longhorn#8623
Propose manually testing the support bundle node timeout to include a simulation of the node collection blockage with a patched image.
`None`
https://github.com/rancher/support-bundle-kit/pull/109
> test(manual): support bundle node collection timeout

- manager/integration/tests/common.py
- manager/integration/tests/test_csi.py
- Add test_csi.py::test_csi_encrypted_migratable_block_volume
- Fix test_csi.py::test_csi_encrypted_block_volume
Longhorn/longhorn#7678
> Add test_csi.py::test_csi_encrypted_migratable_block_volume

- test_framework/terraform/aws/ubuntu/data.tf
longhorn/longhorn#8696
If `var.os_distro_version` is Ubuntu 22.04, it would be:
```
ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-202*****
or
ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-202*****
```
For Ubuntu 24.04, it would be:
```
ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-202*****
or
ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-202*****
```
So we need to update [data.tf](https://github.com/longhorn/longhorn-tests/blob/master/test_framework/terraform/aws/ubuntu/data.tf#L8) to filter Ubuntu 24.04 AMI.
> ci: Update data.tf to support ubuntu 24.04

- manager/integration/tests/test_basic.py
Refine [test_backuptarget_invalid](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/944/testReport/junit/tests/test_basic/test_backuptarget_invalid/)
Modify the loop break logic because a backup will in `Penging` state for a while when backup target is invalid on master-head images
```
NAMESPACE         NAME                      SNAPSHOTNAME   SNAPSHOTSIZE   SNAPSHOTCREATEDAT      STATE     LASTSYNCEDAT
longhorn-system   backup-85313580390a48f9                                 2024-06-14T07:13:13Z   Pending   <no value>
longhorn-system   backup-85313580390a48f9                                 2024-06-14T07:13:13Z   Error     2024-06-14T07:13:35Z
longhorn-system   backup-85313580390a48f9                                 2024-06-14T07:13:13Z …
```
> test: refine test_backuptarget_invalid

- docs/content/manual/pre-release/node-not-ready/node-disconnection/node-disconnection.md
Issue #8617
Update manual test case [Node disconnection test](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-disconnection/node-disconnection/). Because the last content updated was 2 years ago.
Tested on v1.4.4 and master-head, after volume node network back, the volume does not detach, but if data is written during the volume node network disconnect, replica rebuilding is observed..
> test(manual) update Node disconnection test

- e2e/keywords/volume.resource
- e2e/libs/keywords/volume_keywords.py
- e2e/libs/replica/crd.py
- e2e/libs/replica/replica.py
- e2e/libs/replica/rest.py
- e2e/libs/utility/constant.py
- e2e/tests/node_reboot.robot
Issue longhorn/longhorn#8825 , longhorn/longhorn#1992
Add a new case to ensure that no new replica is created and rebuilt on the same node if the node is powered off for a duration longer than the replica-replenishment-wait-interval. When the node is powered on, the existing replica should be reused.
`None`
`None`
> test(robot): power off replica node should not rebuild new replica on same node

- docs/content/manual/release-specific/v1.7.0/test-storage-network-support-for-rwx-volume.md
Issue longhorn/longhorn#8184
Propose to verify the behavior of Longhorn RWX volume workloads during the cluster upgrade process with existing storage network configured. Ensure no disruption to existing workload pods and proper handling of RWX volume workloads for both pre-existing and newly created RWX volume workloads after the upgrade.
`None`
https://github.com/longhorn/longhorn/pull/8616
> test(manual): storage network support for RWX volume

- docs/content/manual/pre-release/ha/ha-volume-migration.md
longhorn/longhorn#8735
longhorn/longhorn#3401
Many of the manual HA volume migration test cases no longer pass with the introduction of the volume attachment controller in `v1.5.0`. I reworked the behavior in longhorn/longhorn#8735, but the manual tests cases also need to be updated. In this iteration, I removed a couple of cases that weren't particularly interesting, added a couple of additional cases, and added detail regarding the expected behavior in `v1.5.0+`.
> Rework HA volume migration test cases for v1.5.0+

- manager/integration/tests/test_node.py
Add retry in `check_replica_evict_state` 
`test_drain_with_block_for_eviction` related test cases failed on Ubuntu 24.04 due to `check_replica_evict_state`  did not have wait mechanism
Origin failed test on [Ubuntu](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/597/testReport/junit/tests/test_node/)
This PR tested pass on [Ubuntu 24.04](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7229/testReport/tests/test_node/) and [SLES 15 SP6](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7231/)
> fix(integration): test_drain_with_block_for_eviction

- docs/content/manual/release-specific/v1.3.0/test-storage-network.md
- docs/content/manual/release-specific/v1.6.0/test-storage-network.md
I decided to create this PR while setting up a storage network to test https://github.com/longhorn/longhorn-manager/pull/2970 for https://github.com/longhorn/longhorn/issues/9000.
There are two locations in the manual tests where we document how to set up an AWS environment capable of supporting the Longhorn storage network feature. While the existing documentation makes it clear that `Source/destination check` should be stopped on all involved instances, I couldn't find the option in the console `Launch instances` dialogue, so I ignored the step. Later, I spend a few hours debugging routing on the storage network before realizing that the instances and/or VPC was/were dropping traffic on the 192.168.0.0/16 network due to the setting being enabled.
This PR makes it clear that the check …
> docs(storage-network): clarify source/destination check step

- manager/integration/tests/test_csi.py
Fix `test_csi_block_volume_online_expansion`
`test_csi_block_volume_online_expansion` is flaky on [rhel 9.3.0](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/175/)
This PR tested by perform 50 times of `test_csi_block_volume_online_expansion` and `test_csi_mount_volume_online_expansion` on rhel all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7240/testReport/tests/test_csi/)
N/A
> Fix test_csi_block_volume_online_expansion

- manager/integration/tests/backupstore.py
- manager/integration/tests/common.py
- manager/integration/tests/test_system_backup_restore.py
ref: https://github.com/longhorn/longhorn/issues/9041
The issue is caused by the backup backing image left over from the previous test.
We should clean up the backup backing image in the backupstore_cleanup function
> fix(backupbackingimage): cleanup backup backing image in the backupstore_cleanup function

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
Issue # longhorn/longhorn#9038
After we tainted a node as `NoSchedule` and delete the EngineImage DaemonSet, `nodeDeploymentMap` will be unstable for a period and it is not enough only to check if the `nodeDeploymentMap` has the expected count for deloyed node.
> fix(engineimage): check if engine image is deployed correctly

- manager/integration/tests/test_support_bundle.py
Issue # longhorn/longhorn#9055
In the test case `test_support_bundle_should_not_timeout`, we change the support bundle size manually, and we should wait for the changed size to be updated before we start to do the download action.
Local testing 30 times: **PASSED**
```shell
master:~# k logs longhorn-test -c longhorn-test -f
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3.11
cachedir: .pytest_cache
rootdir: /integration, configfile: pytest.ini
plugins: order-1.0.1, repeat-0.9.1
collecting ... collected 30 items
+test_support_bundle.py::test_support_bundle_should_not_timeout[1-30] PASSED [  3%]
test_support_bundle.py::test_support_bundle_should_not_timeout[2-30] …
```
> fix(supportbundle): wait for changed support bundle size updated

- manager/integration/tests/backupstore.py
ref: https://github.com/longhorn/longhorn/issues/9037
Longhorn automatically creates backup resource in the cluster when there is a backup in the backupstore.
We need to check if the backup resource is deleted as well before creating the next backup.
Otherwise, the following backup creation might fail due to the deletion lock introduced by previous backup CR deletion.
> fix(backup): check if dummy backup resource is deleted when the config is deleted

- test_framework/scripts/longhorn-setup.sh
Issue N/A
use longhornctl to handle prerequisite installations and perform environment checks
> ci: use longhornctl to handle prerequisite installations and perform environment checks

- test_framework/terraform/aws/eks/main.tf
Issue N/A
prevent overwriting the desired size of eks node group
> ci: prevent overwriting the desired size of eks node group

- manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn/issues/8269
skip test case test_backup_lock_creation_during_deletion since in the current Longhorn implementation, it's almost impossible to catch the moment when the lock is held and the test case always fails.
> test: skip test case test_backup_lock_creation_during_deletion

- e2e/libs/node/node.py
When run self built test image I encountered below error, fix it by this PR
```
==============================================================================
Tests                                                                         
==============================================================================
[ ERROR ] Error in file '/e2e/keywords/common.resource' on line 4: Importing library '/e2e/libs/keywords/common_keywords.py' failed: SyntaxError: invalid syntax (node.py, line 38)
Traceback (most recent call last):
File "/e2e/libs/keywords/common_keywords.py", line 2, in <module>
from node import Node
File "/e2e/libs/node/__init__.py", line 1, in <module>
from node.node import Node
```
> test(robot): fix syntax in node.py

- manager/integration/tests/test_backing_image.py
longhorn/longhorn#9254
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7486/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7487/
After executing the test case 20 times, I found that `volume3 = wait_for_volume_healthy` takes 350 to 450 seconds.
> Fix flaky test_exporting_backing_image_from_volume on sle-micro arm64

- e2e/keywords/deployment.resource
- e2e/tests/replica_rebuilding.robot
Add two cases in e2e/tests/replica_rebuilding.robot
- `Delete replicas one by one after the volume is healthy`
- `Delete replicas one by one regardless of the volume health`
Issue longhorn/longhorn#9240
Verified on local
N/A
> test(robot): add more replica rebuilding test cases

- manager/integration/tests/test_backing_image.py
longhorn/longhorn#9227
Add scenario for backing image size larger than volume size then backup volume.
Currently this scenario only included in `test_system_backup_and_restore_volume_with_backingimage` but v1.6.x does not support system backup with backing image so the scenario not tested in v1.6,x.
test result
- [amd](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7480/)
- [arm](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7477/)
- [sle-micro arm](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7478/)
> test: update test_backup_with_backing_image

- manager/integration/tests/test_system_backup_restore.py
Issue longhorn/longhorn#9330, longhorn/longhorn#9338
Add DR volume to `test_system_backup_with_volume_backup_policy_always`.
`None`
`None`
> test(integration): DR volume when volume backup policy set to always

- manager/integration/tests/test_kubernetes.py
Issue https://github.com/longhorn/longhorn/issues/9391
fix unable to set default sc to a non-existing sc
> test: fix unable to set default sc to a non-existing sc

- manager/integration/tests/test_csi.py
Issue https://github.com/longhorn/longhorn/issues/9451
fix flaky test case test_csi_block_volume_online_expansion caused by md5 calculation timeout
> test: fix flaky test case test_csi_block_volume_online_expansion caused by md5 calculation timeout

- manager/integration/tests/test_recurring_job.py
longhorn/longhorn#9453
longhorn/longhorn#9453
- Updated the number of backups completed for `backup1` and `backup2`.
- Adjusted the timeline for data writes and backup intervals.
- Changed the sleep time from 20 to 30 seconds to align snapshot and backup timing.
- Clarified the expected number of backups and added a comment about the volume-head snapshot.
https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-amd64/196/testReport/junit/tests/test_recurring_job/test_recurring_job_nfs_/
> Update `test_recurring_job` story

- manager/integration/tests/common.py
- manager/integration/tests/test_ha.py
ref: https://github.com/longhorn/longhorn/issues/8573
https://github.com/longhorn/longhorn/issues/8573#issuecomment-2348405896
When the engine image is not stable, there is a chance that the volume changes the owner and creates duplicated replicas.
This might fail this e2e test because it checks the number of replicas before the volume is attached.
We should attach the volume and let Longhorn deletes duplicated replicas before starting the test.
> fix: attach volumes to eliminate duplicated replicas

- manager/integration/tests/test_metric.py
ref: https://github.com/longhorn/longhorn/issues/8508
Export the metrics in the following form
- metric name: `longhorn_volume_file_system_read_only`
- type: gauge
- if the volume becomes read-only, it has metric value 1 with the corresponding labels
- So you know which volume is in read-only mode now
- You can sum up the metrics to see how many volumes are in read-only mode now 
```
longhorn_volume_file_system_read_only{node="kworker1",pvc="nginx",pvc_namespace="default",volume="pvc-3a7a208b-c8c9-46a9-b2ce-4c5f740c8673"} 1
```
Note:
If Longhorn remounts the mount point to read-write successfully, the metrics will be cleaned up.
The metric is either 1 or no record for each volume
> feat(metric): add e2e test for volume filesystem readonly metrics

- pipelines/utilities/run_longhorn_e2e_test.sh
https://github.com/longhorn/longhorn/issues/9554
Fix empty enviroment varibale `LONGHORN_BACKUPSTORE` in longhorn-test(e2e) pod when `BACKUP_STORE_TYPE` set to `nfs`
Verified on my local Jenkins with `s3` and `nfs` set.
> ci(e2e): fix empty nfs backupstore environment variable in longhorn-test pod

- e2e/libs/backing_image/backing_image.py
Let backuping images clean up been executed at test case teardown.
> fix(robot): delete backing images at teardown

- e2e/Dockerfile
- e2e/keywords/backup.resource
- e2e/keywords/longhorn.resource
- e2e/keywords/volume.resource
- e2e/libs/backup/backup.py
- e2e/libs/backup/base.py
- e2e/libs/backup/rest.py
- e2e/libs/k8s/k8s.py
- e2e/libs/keywords/backup_keywords.py
- e2e/libs/keywords/longhorn_deploy_keywords.py
- e2e/libs/keywords/volume_keywords.py
- e2e/libs/longhorn_deploy/__init__.py
- e2e/libs/longhorn_deploy/base.py
- e2e/libs/longhorn_deploy/longhorn_deploy.py
- e2e/libs/longhorn_deploy/longhorn_helm_chart.py
- e2e/libs/longhorn_deploy/longhorn_kubectl.py
- e2e/libs/utility/constant.py
- e2e/libs/utility/utility.py
- e2e/tests/negative/uninstallation_checks.robot
- e2e/utilities/longhorn-install.sh
- pipelines/utilities/run_longhorn_e2e_test.sh
Issue #longhorn/longhorn#9222
Transfer manual test case `Uninstallation Checks` into robot framework
Having environment below variable set first if run on local
- `LONGHORN_INSTALL_METHOD` (`manifest` or `helm`) 
- `LONGHORN_REPO_BRANCH`
- `CUSTOM_LONGHORN_MANAGER_IMAGE` (if not using master-head)
- `CUSTOM_LONGHORN_ENGINE_IMAGE` (if not using master-head)
- `CUSTOM_LONGHORN_INSTANCE_MANAGER_IMAGE` (if not using master-head)
- `CUSTOM_LONGHORN_SHARE_MANAGER_IMAGE` (if not using master-head)
-`CUSTOM_LONGHORN_BACKING_IMAGE_MANAGER_IMAGE` (if not using master-head)
issue command
- `./run.sh -t "Uninstallation Checks" 
[report.zip](https://github.com/user-attachments/files/16725623/report.zip)
> test(robot): add uninstallation check test case

- e2e/keywords/common.resource
- e2e/tests/negative/node_drain.robot
Issue N/A
replace "Cleanup test resources include off nodes" with "Cleanup test resources"
> test(robot): replace "Cleanup test resources include off nodes" with "Cleanup test resources"

- e2e/libs/workload/pod.py
- e2e/tests/negative/node_reboot.robot
Issue longhorn/longhorn#9498
When the `node-down-pod-deletion-policy` is set to `do-nothing`, Longhorn doesn't actively delete the workload pod. In this case, reattaching may not happen, as this behavior will depend on Kubernetes' response. We should remove the check of the volume's attaching state and just ensure that the workload pod is in a terminating state, which is expected.
`None`
`None`
> fix(robot): Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Replica Node

- e2e/tests/negative/node_reboot.robot
Issue longhorn/longhorn#9622
Remove redundant intermediate check as when node down deletion policy is set to `do-nothing`, the workload pod deletion isn't handled by Longhorn.
`None`
`Name`
> fix(robot): Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Volume Node

- e2e/tests/regression/test_ha.robot
Issue https://github.com/longhorn/longhorn/issues/9276
fix flaky test case Disrupt Data Plane Traffic For Less Than Long Engine Replica Timeout
> fix(robot): fix flaky test case Disrupt Data Plane Traffic For Less Than Long Engine Replica Timeout

- e2e/keywords/common.resource
- e2e/keywords/engine.resource
- e2e/keywords/replica.resource
- e2e/keywords/volume.resource
- e2e/libs/engine/crd.py
- e2e/libs/engine/engine.py
- e2e/libs/keywords/engine_keywords.py
- e2e/libs/keywords/replica_keywords.py
- e2e/libs/keywords/setting_keywords.py
- e2e/libs/keywords/volume_keywords.py
- e2e/libs/replica/crd.py
- e2e/libs/replica/replica.py
- e2e/libs/setting/setting.py
- e2e/libs/volume/crd.py
- e2e/libs/volume/rest.py
- e2e/libs/volume/volume.py
- e2e/tests/regression/test_basic.robot
Issue https://github.com/longhorn/longhorn/issues/9318
add test strict local volume disabled revision conuter by default
> test(robot): add test strict local volume disabled revision conuter by default

- e2e/keywords/common.resource
Issue `None`
The `reset_backupstore` task is being called twice. Should either remove the duplicated call or add a comment to explain why.
`None`
https://github.com/longhorn/longhorn-tests/pull/2080/files#diff-84cbf5801bda0fa4be66cfbfdc6b0b4ff977edc0485718924095d3947c2c0529R54-R55
> chore(robot): remove duplicated call of reset_backupstore

- test_framework/terraform/harvester/oracle/main.tf
- test_framework/terraform/harvester/oracle/variables.tf
Issue https://github.com/longhorn/longhorn/issues/9691
support oracle for hal cluster
> ci: support oracle for hal cluster

- test_framework/scripts/longhorn-setup.sh
- test_framework/terraform/harvester/sles/main.tf
Issue #10597
`test_framework/scripts/longhorn-setup.sh`
- We have a `shutdown -r +5`([ref](https://github.com/longhorn/longhorn-tests/blob/master/test_framework/terraform/harvester/sles/main.tf#L150-L152)) in the harvester worker node provisioning process. IIRC, this command schedules a system reboot after 5 minutes, which allows time for all running packages to complete their tasks before the node restarts. To avoid the risk of a node reboot occurring while Longhorn is still installing, I added a sleep 300s delay to ensure the shutdown happens after Longhorn's installation is complete.
`test_framework/terraform/harvester/sles/main.tf`
- When building the `longhorn-test-regression` job container (which uses the same harvester terraform script as the alternative AppCo …
> ci: refine HAL pipeline flow

- manager/integration/tests/common.py
- pipelines/utilities/run_longhorn_test.sh
Add the environment variable `RUN_V2_TEST` back into the `longhorn-test` pod after recent test code refinements.
N/A
N/A
N/A
> ci: add environment variable RUN_V2_TEST back into longhorn-test pod

- manager/integration/tests/common.py
- manager/integration/tests/test_settings.py
Refine `test_settings.py` by counting instance manager based on the data engine
Test result:  https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8389/testReport/tests/test_settings/
> test(pytest): refine test_settings.py by count instance manager based on data engine

- manager/integration/tests/requirements.txt
Issue #10688
Upgrade PyYAML to bypass [setuptools PEP639 check](https://github.com/pypa/setuptools/issues/4938), and fix our CI.
> ci: fix setuptools lisence issue for pyyaml

- pipelines/appco/scripts/longhorn-setup.sh
- test_framework/terraform/harvester/sles/main.tf
Issue https://github.com/rancher/suse-storage/issues/4
fix x509 certificate signed by unknown authority error when pulling images from registry.suse.de
> ci: fix x509 certificate signed by unknown authority error when pulling images from registry.suse.de

- e2e/keywords/longhorn.resource
- e2e/keywords/workload.resource
- e2e/libs/k8s/k8s.py
- e2e/libs/keywords/k8s_keywords.py
- e2e/tests/negative/node_down.robot
Issue #9759
Implement manual test case [Physical node down](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-down/physical-node-down/)
Test result: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2467/, not include below test cases 
due to https://github.com/longhorn/longhorn/issues/10689 validate first
- `Physical Node Down Deployment Deletion Policy Delete Statefulset Pod`
- `Physical Node Down Deployment Deletion Policy Do Nothing`
> test(robot): automate manual test case Physical node down

- test_framework/Dockerfile.setup
- test_framework/terraform/aws/talos/README.md
- test_framework/terraform/aws/talos/data.tf
- test_framework/terraform/aws/talos/longhorn-talos.yaml
- test_framework/terraform/aws/talos/main.tf
- test_framework/terraform/aws/talos/variables.tf
https://github.com/longhorn/longhorn/issues/9932
- ci: use upstream Talos AMI
- Updated `variables.tf` to change the default OS distribution version from 1.8.3 to 1.9.5.
- Added a new resource in `main.tf` to upload the Talos schematic
- Handle upgrades for control and worker nodes.
- Add README.md
@yangchiu @chriscchien
> ci: use upstream Talos AMI

- manager/integration/tests/common.py
- manager/integration/tests/test_orphan.py
Issue longhorn/longhorn#10802
The orphan auto deletion settings is moved:
- old `orphan-auto-deletion`: deprecated, read-only
- new `orphan-resource-auto-deletion`: enable replica data cleanup by list `replicaData` in this semi-colon list string
> test: fix orphan auto deletion settings

- manager/integration/tests/common.py
Tolerate v2 data engine enable fail for managed k8s cluster
> test: tolerate v2 data engine enable fail for managed k8s cluster

- pipelines/gke/scripts/longhorn-setup.sh
- pipelines/utilities/install_backupstores.sh
- test_framework/scripts/longhorn-setup.sh
Use longhorn repo backupstores on GKE pipeline to avoid backupstore pods not scheduled
```
138950374eed:/src/longhorn-tests# k get pods
NAME                                    READY   STATUS    RESTARTS   AGE
longhorn-test                           2/2     Running   0          19m
longhorn-test-azblob-76454445df-qhdbb   1/1     Running   0          3m1s
longhorn-test-cifs-5975587fc8-wpxbp     1/1     Running   0          3m1s
longhorn-test-minio-6cf745556b-q8sdh    0/1     Pending   0          22m
longhorn-test-nfs-8dc6fdf45-vv2vd       0/1     Pending   0          22m
```
Pod events:
```
Normal   NotTriggerScaleUp  3m4s (x237 over 23m)  cluster-autoscaler                     pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector
```
N/A
N/A
> test: update GKE pipeline use longhorn repo backupstores

- test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl
- test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl
- test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_agent.sh.tpl
- test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_server.sh.tpl
https://github.com/longhorn/longhorn/issues/10838
Test case `test_multiple_volumes_creation_with_degraded_availability` is failing on `ubuntu upgrade test job` due to the pod failed to mount the volume. The issue was caused by the `multipathd.socket` and `multipathd.service` not being stopped on the worker nodes.
@james-munson @yangchiu 
https://longhorn.io/kb/troubleshooting-volume-with-multipath/
> ci: disable the `multipathd` on aws ubuntu cluster

- test_framework/terraform/aws/talos/main.tf
https://github.com/longhorn/longhorn/issues/10756
This enhancement allows users to define and manage the Kubernetes version explicitly, ensuring better control and compatibility in Talos environments.
> ci: talos support setting a specific K8S version

- pipelines/appco/Jenkinsfile
- pipelines/appco/scripts/prepare-airgap-appco-images.sh
Issue #10859
AppCo v1.8.1 images have new registry `dp.apps.rancher.io`. Add authentication for `dp.apps.rancher.io` for airgap installation for pulling correspond images
N/A
`APPCO_USERNAME`: okta user name
`APPCO_PASSWORD`:  token create under https://apps.rancher.io/settings/access-tokens ([ref](https://docs.apps.rancher.io/get-started/first-steps/))
> ci: AppCo pipeline authenticate AppCo OCI registry pull images(airgap)

- pipelines/utilities/cleanup.sh
Issue https://github.com/longhorn/longhorn/issues/10849
prevent cloud credential from being deleted before harvester cluster is deleted on hal by a 2-stage `terraform destroy`, the 1st stage deletes the cluster only, and the 2nd stage deletes the remaining resources, including the credential.
> ci: prevent cloud credential from being deleted before harvester cluster is deleted on hal

- manager/integration/tests/backupstore.py
Issue longhorn/longhorn#10878
- Revert commit 309655b6bde562f491b04716c67ff3ea814e2875.
- NFS should work after updating the nfs-ganesha version in the nfs-backupstore image.
- Dependent on https://github.com/longhorn/nfs-backupstore/pull/2
`None`
> Revert "fix(pytest): NFS backupstore not working on Talos v1.9.x"

- manager/integration/deploy/backupstores/nfs-backupstore.yaml
longhorn/longhorn-10878
Cherry-pick the changes from https://github.com/longhorn/longhorn/pull/10901 to the `nfs-backupstore.yaml` file in the https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/deploy/backupstores/nfs-backupstore.yaml#L51](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/deploy/backupstores/nfs-backupstore.yaml#L51.
Previously, Longhorn did not maintain a repository for the NFS backupstore image build. Now that we've introduced the [longhornio/nfs-backupstore](https://github.com/longhorn/nfs-backupstore), the image name will be aligned with the project name.
https://github.com/longhorn/longhorn/pull/10901
https://github.com/longhorn/longhorn/pull/10878
> chore(backupstore/nfs): align image with longhorn/nfs-backupstore

- manager/integration/tests/test_snapshot.py
https://github.com/longhorn/longhorn/issues/10886
This PR enhances `wait_for_snapshot_checksums_generate` by adding `elapsed_time` tracking, providing more accurate timing information.
private image test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8561/testReport/
> Add `elapsed_time` tracking in `wait_for_snapshot_checksums_generate`

- manager/integration/tests/test_snapshot.py
https://github.com/longhorn/longhorn/issues/10886
This PR enhances `wait_for_snapshot_checksums_generate` by adding `elapsed_time` tracking, providing more accurate timing information.
private image test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8561/testReport/
https://github.com/longhorn/longhorn-tests/pull/2496
> Add elapsed_time tracking in `wait_for_snapshot_checksums_generate` v1.9.x (backport #2496)

- manager/integration/tests/test_snapshot.py
https://github.com/longhorn/longhorn/issues/10886
This PR enhances `wait_for_snapshot_checksums_generate` by adding `elapsed_time` tracking, providing more accurate timing information.
private image test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8561/testReport/
https://github.com/longhorn/longhorn-tests/pull/2496
> Add elapsed_time tracking in wait_for_snapshot_checksums_generate v1.8.x (backport #2496)

- manager/integration/tests/test_snapshot.py
https://github.com/longhorn/longhorn/issues/10886
This PR enhances `wait_for_snapshot_checksums_generate` by adding `elapsed_time` tracking, providing more accurate timing information.
private image test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8561/testReport/
https://github.com/longhorn/longhorn-tests/pull/2496
> Add elapsed_time tracking in wait_for_snapshot_checksums_generate v1.7.x (backport #2496)

- manager/integration/tests/test_orphan.py
longhorn/longhorn#6764
The regression test for `v1.9.0-rc3` failed at https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/611/testReport/junit/tests/test_orphan/test_orphan_auto_deletion/
This PR addresses the issue by updating the test case to ensure compatibility and resolve the failure.
@COLDTURNIP @derekbit
> Update `SETTING_ORPHAN_RESOURCE_AUTO_DELETION` value to `replica-data`

- manager/integration/tests/test_metric.py
Issue https://github.com/longhorn/longhorn/issues/10957
Remove `assert isinstance(found_metric.value, float)` for some metric value changed to `int`
We still utilize `found_metric.value == expected_value` to check metric value
> test: refine metric test cases

- manager/integration/tests/test_provisioner.py
https://github.com/longhorn/longhorn/issues/10974
- Added the `dataEngine` parameter to the storage class configuration in the `test_provisioner_tags` test case.
- Ensures that the test aligns with the updated storage class requirements.
@chriscchien
> fix(tests): add `dataEngine` parameter to storage class in `test_provisioner_tags`

- e2e/tests/prerelease_checks.robot
longhorn/longhorn#11098
- Improved the logic of `prerelease_checks` to include the `${test_v2_only}` condition.  
- This enhancement aims to make it easier for developers to test v2 volumes.  
- By refining the testing logic, developers can identify v2-related issues more efficiently.  
@yangchiu 
**CUSTOM_TEST_OPTIONS**
`-t \"Pre-release Checks\" --exclude \"cluster\" --exclude \"storage-network\" --exclude \"large-size\" -v LOOP_COUNT:1 -v RETRY_COUNT:600 -v DATA_ENGINE:v2 -v test_v2_only:true`
> test(robot): Add ${test_v2_only} condition to enhance prerelease_checks for v2 volume testing

- e2e/tests/prerelease_checks.robot
- manager/integration/deploy/backupstores/nfs-backupstore.yaml
longhorn/longhorn#11128
Enhance the Prerelease Checks test case to address the issue of `no space left on device` encountered during the validation of the `longhorn-rancher-chart-test`.
The detailed report : https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/197/
The PR test result:
- `106.1.1+up1.7.3` > `106.2.1+up1.8.2`
-  https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/233/
- `106.2.1+up1.8.2`
-  https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/234/
> test(robot): Optimize prerelease checks to prevent space issue

- e2e/README.md
If run e2e on local and perform upgrade test case, it is necessary to manually copy folder `pipelines` into folder `e2e` now, or the test case will fail due to not find installation script. Add the step into `README.md`
> test(robot): update e2e README.md

- manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/11316
fix getting longhorn api client could hang
(1) set timeout for socket connect function
(2) avoid trying to get longhorn api client from a terminating longhorn manager pod
> test: fix getting longhorn api client could hang

- e2e/keywords/sharemanager.resource
- e2e/libs/keywords/common_keywords.py
- e2e/tests/regression/test_encrypted_volume.robot
longhorn/longhorn#11121
longhorn/longhorn#11120
Add case `rwx encryption volume online expansion`
@COLDTURNIP 
PR test log : https://ci.longhorn.io/job/private/job/longhorn-e2e-test/3676/robot/report/log.html
Here's how to execute test case:  `./run.sh -t "Test Encrypted RWX Volume Online Expansion"`
> test(robot): Add case rwx encryption volume online expansion

- manager/integration/tests/common.py
Issue # longhorn/longhorn#11337
Add the sub-string "failed to list system backups in" into BACKUP_TARGET_MESSAGES_INVALID
> fix(backup): add failed sub-string in BACKUP_TARGET_MESSAGES_INVALID

- test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl
Issue longhorn/longhorn#11529
Force `Ubuntu` use `IPv4` for install dependency to avoid dependency install fail
Before the fix, v2 regression test case all failed
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/9226/
Use this fix, v2 test case worked properly with Ubuntu
- https://10.115.5.5/job/private/job/longhorn-tests-regression-experiment/16/
> ci: Force `Ubuntu` use `IPv4` for install dependency

- e2e/libs/recurringjob/crd.py
- e2e/tests/regression/test_recurringjob.robot
Issue https://github.com/longhorn/longhorn/issues/11533
Fix unreachable sleep in waiting for system backup to be created.
And attaching the volume before creates backups since allow-recurring-job-while-volume-detached is disabled by default
> test(robot): fix unreachable sleep in waiting for system backup to be created

- pipelines/appco/Jenkinsfile
- pipelines/helm/Jenkinsfile
- test_framework/Jenkinsfile
Issue N/A
fix SUSE_Trust_Root.crt not found error in airgap pipelines and support running appco pipeline on public jenkins
(1) fix  SUSE_Trust_Root.crt not found error in helm/manifest airgap installation pipelines
(2) fix permission denied error when cp SUSE_Trust_Root.crt on public jenkins
(3) remove redundant cp of repeatedly copying SUSE_Trust_Root.crt from jenkins server to the same test build workspace
(4) add suse dns servers to be able to access registry.suse.de on public jenkins
> ci: fix SUSE_Trust_Root.crt not found error in airgap pipelines and support running appco pipeline on public jenkins

- e2e/tests/regression/test_backup.robot
Issue #
Remove not support test case `Test DR Volume Backup Block Size` in v1.9.x
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/4122/
> test(robot): remove Test DR Volume Backup Block Size

- e2e/tests/negative/upgrade_with_new_default_storageclass.robot
Issue N/A
fix Test system upgrade with a new storage class being default on v2 volumes by detaching v2 volumes before upgrading
> test(robot): fix Test system upgrade with a new storage class being default on v2 volumes by detaching v2 volumes before upgrading

- airgap/Dockerfile.setup
Issue #
Change air gap alpine version from latest to `3.19` to avoid OpenSSL library version mismatch
```
3.960 OpenSSL version mismatch. Built against 3050003f, you have 30500010
------
[33m2 warnings found (use docker --debug to expand):
[0m - ConsistentInstructionCasing: Command 'From' should match the case of the command majority (uppercase) (line 1)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 11)
Dockerfile.setup:21
--------------------
20 |     
21 | >>> RUN wget -q https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && \
22 | >>>     mv kubectl /usr/local/bin/kubectl && \
23 | >>>     chmod +x /usr/local/bin/kubectl  && \
24 | >>>     wget -q …
```
> ci: use alpine 3.19 instead of latest in air gap container

- manager/integration/tests/common.py
- manager/integration/tests/test_csi_snapshotter.py
Issue longhorn/longhorn#11885
extend `test_csi_snapshotter` v2 volume test coverage
https://github.com/longhorn/longhorn/issues/9760#issuecomment-2538283018
test result of `test_csi_snapshotter.py`
- [v1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/9632/)
- [v2](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/9633/)
> test(pytest): extend test_csi_snapshotter v2 volume test coverage
