manager/integration/tests/common.py, manager/integration/tests/test_cloning.py
Backport test_cloning cases into v1.2.x because currently only test skeleton of cloning cases in v1.2.x
cc @khushboo-rancher
=> [Backport 1.2.x] Add volume cloning basic test

manager/integration/tests/test_ha.py
From https://github.com/longhorn/longhorn/issues/3104
Implement test case test_recovery_from_im_deletion()
=> implement test_recovery_from_im_deletion

manager/integration/tests/test_ha.py
Backport test_recovery_from_im_deletion() to v1.2.x
Fixed conflict with test_autosalvage_with_data_locality_enabled() as well
=> [Backport V1.1.x] implement test_recovery_from_im_deletion

manager/integration/tests/test_ha.py
Backport test_recovery_from_im_deletion() to v1.2.x
=> [Backport V1.2.x] implement test_recovery_from_im_deletion

manager/integration/tests/test_ha.py
Implement test_autosalvage_with_data_locality_enabled()
=> Implement test_autosalvage_with_data_locality_enabled()

manager/integration/tests/test_ha.py
Signed-off-by: Chris Chien [chris.chien@suse.com](mailto:chris.chien@suse.com)
Backport test_autosalvage_with_data_locality_enabled() to v1.1.x
=> [Backport v1.1.x] implement test_autosalvage_with_data_locality_enabled

manager/integration/tests/test_ha.py
Backport test_autosalvage_with_data_locality_enabled() to v1.2.x
=> [Backport v1.2.x] implement test_autosalvage_with_data_locality_enabled

docs/content/manual/release-specific/v1.3.0/test-helm-uninstall-different-namespace.md
https://github.com/longhorn/longhorn/issues/2034
=> Add manual test - uninstall Longhorn in different namespace

docs/content/manual/release-specific/v1.3.0/test-helm-uninstall-different-namespace.md
https://github.com/longhorn/longhorn-tests/pull/918
https://github.com/longhorn/longhorn/issues/2034
=> Fix manual test - uninstall Longhorn in different namespace

manager/integration/tests/common.py, manager/integration/tests/test_ha.py
Implement test_disable_replica_rebuild()
=> Implement test_disable_replica_rebuild

manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py
Implement `test_exporting_backing_image_from_volume`
https://github.com/longhorn/longhorn/issues/3791
=> Implement test_exporting_backing_image_from_volume

manager/integration/deploy/test.yaml, manager/integration/tests/run.sh, test_framework/scripts/longhorn-setup.sh
=> [backport-v1.1.x] jenkins print pytest logs

manager/integration/deploy/test.yaml, manager/integration/tests/run.sh, test_framework/scripts/longhorn-setup.sh
=> [backport-v1.2.x] jenkins print pytest logs

manager/integration/tests/test_cloning.py
Implement `test_cloning_with_backing_image`
https://github.com/longhorn/longhorn/issues/3797
=> Implement test_cloning_with_backing_image

manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py
Backport test_exporting_backing_image_from_volume() to v1.2.x
=> [Backport  v1.2.x]Implement test_exporting_backing_image_from_volume

manager/integration/tests/test_ha.py
Backport 1.1.x -  test_disable_replica_rebuild
=> [Backport 1.1.x] test_disable_replica_rebuild

manager/integration/tests/test_ha.py
Backport 1.2.x - `test_disable_replica_rebuild`
=> [Backport 1.2.x] test_disable_replica_rebuild

manager/integration/tests/test_cloning.py
Backport v1.2.x - Implement `test_cloning_with_backing_image()`
=> [Backport 1.2.x] Implement test_cloning_with_backing_image

manager/integration/tests/test_basic.py
=> integration: Add skeleton test_default_storage_class_syncup

manager/integration/tests/test_csi_snapshotter.py
Implement test case `test_csi_snapshot_with_invalid_param`
=> Implement test_csi_snapshot_with_invalid_param

manager/integration/tests/requirements.txt, manager/integration/tests/test_infra.py
to prevent cascading failure
for [#3851](https://github.com/longhorn/longhorn/issues/3851)
=> Mark test_offline_node the last one to be executed

test_framework/terraform/aws/centos/k3s_instances.tf, test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/k3s_instances.tf, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rhel/k3s_instances.tf, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rockylinux/k3s_instances.tf, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/sles/k3s_instaces.tf, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/ubuntu/k3s_instaces.tf, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl
to debug regression test
for [#3856](https://github.com/longhorn/longhorn/issues/3856)
=> Print cloud-init log if jq command not found

test_framework/terraform/aws/centos/main.tf, test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/main.tf, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rhel/main.tf, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rockylinux/main.tf, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/sles/main.tf, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/ubuntu/main.tf, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl
to debug regression test
for [#3856](https://github.com/longhorn/longhorn/issues/3856)
=> [backport-v1.2.x] Print cloud-init-output.log if cloud-init error

test_framework/terraform/aws/centos/main.tf, test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/main.tf, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rhel/main.tf, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rockylinux/main.tf, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/sles/main.tf, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/ubuntu/main.tf, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl
to debug regression test
for [#3856](https://github.com/longhorn/longhorn/issues/3856)
=> [backport-v1.1.x] Print cloud-init-output.log if cloud-init error

test_framework/terraform/aws/centos/data.tf, test_framework/terraform/aws/centos/k3s_instances.tf, test_framework/terraform/aws/centos/main.tf, test_framework/terraform/aws/centos/rke2_instances.tf, test_framework/terraform/aws/oracle/data.tf, test_framework/terraform/aws/oracle/k3s_instances.tf, test_framework/terraform/aws/oracle/main.tf, test_framework/terraform/aws/oracle/rke2_instances.tf, test_framework/terraform/aws/rhel/data.tf, test_framework/terraform/aws/rhel/k3s_instances.tf, test_framework/terraform/aws/rhel/main.tf, test_framework/terraform/aws/rhel/rke2_instances.tf, test_framework/terraform/aws/rockylinux/data.tf, test_framework/terraform/aws/rockylinux/k3s_instances.tf, test_framework/terraform/aws/rockylinux/main.tf, test_framework/terraform/aws/rockylinux/rke2_instances.tf, test_framework/terraform/aws/sles/data.tf, test_framework/terraform/aws/sles/k3s_instaces.tf, test_framework/terraform/aws/sles/main.tf, test_framework/terraform/aws/sles/rke2_instances.tf, test_framework/terraform/aws/ubuntu/data.tf, test_framework/terraform/aws/ubuntu/k3s_instaces.tf, test_framework/terraform/aws/ubuntu/main.tf, test_framework/terraform/aws/ubuntu/rke2_instances.tf
From https://github.com/longhorn/longhorn/issues/3892
Newest terraform not accept length = 0 cluster secret, modify code to cope it
cc @meldafrawi
=> fix secret expected length to be at least (1)

docs/content/manual/release-specific/v1.3.0/test-snapshot-purge-retry.md, manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py, manager/integration/tests/test_basic.py
Longhorn/longhorn#3613
Longhorn/longhorn#3748
=> Test for Snapshot prune feature & snapshot revert improvement

manager/integration/Dockerfile
Related issue: longhorn/longhorn#2939
Reference build result with manually built test image: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1116/
=> Update Dockerfile: change base image to SLE BCI

test_framework/Jenkinsfile
to prevent resources limitation caused failure
=> Temporarily add aws_creds selection

manager/integration/Dockerfile
Signed-off-by: David Ko <dko@suse.com>
=> Fix findmnt notfound after migrating to bci

manager/integration/tests/common.py, manager/integration/tests/test_recurring_job.py
Flaky test results - [#1150](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1150/testReport/tests/test_recurring_job/)
=> Fix flaky test_recurring_job_detached_volume

mirror_csi_images/Dockerfile.setup, mirror_csi_images/Jenkinsfile, mirror_csi_images/scripts/build.sh, mirror_csi_images/scripts/image-mirror.sh, mirror_csi_images/scripts/publish.sh
Add mirror csi images code
For [#3056](https://github.com/longhorn/longhorn/issues/3056)
=> Add mirror csi images code

benchmark_test/Dockerfile.setup, benchmark_test/Jenkinsfile, benchmark_test/scripts/benchmark-test-setup.sh, benchmark_test/scripts/build.sh, benchmark_test/scripts/cleanup.sh, benchmark_test/scripts/fio-cmp.yaml, benchmark_test/scripts/fio-local-path.yaml, benchmark_test/scripts/fio-longhorn.yaml, benchmark_test/scripts/terraform-setup.sh, benchmark_test/user-data-scripts/provision_k3s_agent.sh.tpl, benchmark_test/user-data-scripts/provision_k3s_server.sh.tpl, benchmark_test/user-data-scripts/provision_rke.sh, benchmark_test/user-data-scripts/provision_rke2_agent.sh.tpl, benchmark_test/user-data-scripts/provision_rke2_server.sh.tpl
to run kbench and record results periodically
for issue [#3540](https://github.com/longhorn/longhorn/issues/3540)
=> Add Benchmark test

manager/integration/tests/common.py, manager/integration/tests/test_settings.py
Implement test case `test_setting_backing_image_auto_cleanup`
=> Implement test case test_setting_backing_image_auto_cleanup

manager/integration/tests/test_settings.py
If the actual wait interval is the same as the setting value, the backing image file **may** be removed then the backing image status checks in step 5-6 get failed.
=> integration: Update test_setting_backing_image_auto_cleanup

manager/integration/tests/common.py, manager/integration/tests/test_settings.py
Backport V1.2.x test_setting_backing_image_auto_cleanup
=> [Backport V1.2.x] test_setting_backing_image_auto_cleanup

benchmark_test/Jenkinsfile, benchmark_test/scripts/benchmark-test-setup.sh
Run benchmark test for customized longhorn
For [#3919](https://github.com/longhorn/longhorn/issues/3919)
=> Run benchmark test for customized longhorn

manager/integration/tests/common.py
Use more precise error message for comparison.
[Longhorn 3939](https://github.com/longhorn/longhorn/issues/3939)
=> Use more precise error message for comparison

manager/integration/pytest.ini, manager/integration/tests/common.py, manager/integration/tests/test_orphan.py
[Longhorn 685](https://github.com/longhorn/longhorn/issues/685)
=> integration: Add orphan tests

manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn-manager/pull/1338#issuecomment-1138029690
=> cleanup: test_backuptarget_available_during_engine_image_not_ready

manager/integration/tests/backupstore.py
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1362/testReport/junit/tests/test_ha/test_dr_volume_with_restore_command_error_s3__2/
https://github.com/longhorn/longhorn-manager/pull/1338#issuecomment-1138380264
https://github.com/longhorn/longhorn/issues/3546
=> flaky-results: fix backupstore cleanup

manager/integration/tests/common.py, manager/integration/tests/test_ha.py
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1362/testReport/junit/tests/test_backing_image/test_ha_salvage_with_backing_image/
https://github.com/longhorn/longhorn-manager/pull/1338#issuecomment-1138380264
https://github.com/longhorn/longhorn/issues/3546
=> flaky-results: fix crash_replica_processes

docs/content/manual/release-specific/v1.3.0/test-backing-image-download-to-local.md
=> doc: Add a test for the backing image download feature

docs/content/manual/release-specific/v1.3.0/test-storage-network.md
https://github.com/longhorn/longhorn/issues/2285
https://github.com/longhorn/longhorn/issues/3546
=> storage-network: manual setup and test

manager/integration/tests/test_backing_image.py
https://github.com/longhorn/longhorn/issues/4090
=> integration: Add test skeletons test_backing_image_auto_resync

docs/content/manual/release-specific/v1.3.0/test-npe-when-longhorn-ui-deployment-not-exist.md
https://github.com/longhorn/longhorn/issues/4065
=> manual: test NPE when UI deployment CR not exist

manager/integration/tests/test_settings.py
=> integration: Fix test_setting_backing_image_auto_cleanup

docs/content/manual/release-specific/v1.3.0/test-grpc-proxy.md
https://github.com/longhorn/longhorn/issues/4038
https://github.com/longhorn/longhorn/issues/2821
=> manual: test IM proxy gRPC connection metrics

test_framework/Jenkinsfile, test_framework/terraform/aws/rockylinux/k3s_instances.tf, test_framework/terraform/aws/rockylinux/variables.tf
(1) Fix os distro version is not passed to terraform
(2) Fix rockylinux cloud-init status permission issue
(3) Update default rockylinux version
=> Fix os distro version is not passed to terraform

test_framework/Jenkinsfile, test_framework/terraform/aws/rockylinux/main.tf, test_framework/terraform/aws/rockylinux/variables.tf
(1) Fix os distro version is not passed to terraform
(2) Fix rockylinux cloud-init status permission issue
(3) Update default rockylinux version
=> [backport-v1.2.x] Fix os distro version is not passed to terraform

test_framework/terraform/aws/oracle/k3s_instances.tf, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/variables.tf
(1) Fix cloud-init status permission denied
(2) Disable firewalld to let k3s cluster work
(3) Update Oracle distro version
=> Fix Oracle build issue

test_framework/terraform/aws/oracle/main.tf, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/variables.tf
(1) Fix cloud-init status permission denied
(2) Disable server firewalld to let k3s cluster work
(3) Update Oracle distro version
=> [backport-v1.2.x] Fix Oracle build issue

test_framework/terraform/aws/oracle/k3s_instances.tf, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/variables.tf
(1) Fix cloud-init status permission denied
(2) Disable server firewalld to let k3s cluster work
(3) Update Oracle distro version
=> [backport-v1.3.x] Fix Oracle build issue

manager/integration/tests/common.py, manager/integration/tests/test_node.py
Implement test case test_disk_eviction_with_node_level_soft_anti_affinity_disabled
https://github.com/longhorn/longhorn/issues/4040
=> Add test case : test case test_disk_eviction_with_node_level_soft_anti_affinity_disabled

manager/integration/tests/test_csi.py
1. When volume status was False, after deployment scale up from 0 to 1, get pod data  immediately may cause `Reason: Handshake status 500 Internal Server Error`, add retry mechanism.
2. When volume status was True, after deployment scale up from 0 to 1, wait volume healthy then get pod data to avoid flaky status (Previously pass case all at volume healthy status).
https://github.com/longhorn/longhorn/issues/4121
=> fix flaky test_allow_volume_creation_with_degraded_availability_csi

manager/integration/tests/test_csi.py
[Backport v1.2.x] fix flaky test_allow_volume_creation_with_degraded_availability_csi
https://github.com/longhorn/longhorn-tests/pull/999
=> [Backport v1.2.x] fix flaky test_allow_volume_creation_with_degraded_availability_csi

manager/integration/tests/test_csi.py
[Backport v1.3.x] fix flaky test_allow_volume_creation_with_degraded_availability_csi
https://github.com/longhorn/longhorn-tests/pull/999
=> [Backport v1.3.x] fix flaky test_allow_volume_creation_with_degraded_availability_csi

test_framework/Jenkinsfile
Add Longhorn version information on the build summary page
For https://github.com/longhorn/longhorn/issues/4204
=> Add Longhorn version information on the build summary page

test_framework/Jenkinsfile
Add Longhorn version information on the build summary page
=> [Backport v1.3.x] Add Longhorn version information on the build summary page

test_framework/Jenkinsfile
Add Longhorn version information on the build summary page
=> [Backport v1.2.x] Add Longhorn version information on the build summary page

airgap/Dockerfile.setup, airgap/scripts/build.sh, airgap/scripts/cleanup.sh, airgap/scripts/terraform-setup.sh, airgap/terraform/data.tf, airgap/terraform/main.tf, airgap/terraform/output.tf, airgap/terraform/user-data-scripts/provision_registry_server.sh, airgap/terraform/variables.tf, test_framework/Jenkinsfile, test_framework/scripts/longhorn-setup.sh
Setup pipeline for testing longhorn air gap installation.
for [#3926](https://github.com/longhorn/longhorn/issues/3926)
=> Setup pipeline for testing longhorn air gap installation.

test_framework/Jenkinsfile
Fix missing parameters in master pipeline
=> Fix missing parameters in master pipeline

test_framework/Jenkinsfile
Fix parameters shadowing in regression and master pipelines
=> Fix parameters shadowing in regression and master pipelines

manager/integration/tests/test_basic.py
=> Add test skeleton 'test_space_usage_for_rebuilding_only_volume'

manager/integration/tests/test_migration.py
Add test case `test_migration_with_failed_replica`
=> Add case test_migration_with_failed_replica

manager/integration/tests/common.py, manager/integration/tests/test_engine_upgrade.py, manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/3872
Add test case test_setting_concurrent_rebuild_limit
=> Add test case : test_setting_concurrent_rebuild_limit

manager/integration/tests/common.py
https://github.com/longhorn/longhorn-tests/pull/1019
https://github.com/longhorn/longhorn/issues/4260
=> [v1.2.x] fix: backport caused missing import

manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn/issues/4183
https://github.com/longhorn/longhorn/issues/4251
=> [BACKPORT][v1.3.x] Add test skeleton 'test_space_usage_for_rebuilding_only_volume'

manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn/issues/4183
https://github.com/longhorn/longhorn/issues/4252
=> [BACKPORT][v1.2.x] Add test skeleton 'test_space_usage_for_rebuilding_only_volume'

docs/content/manual/release-specific/v1.4.0/test-helm-install-on-rancher-deployed-windows-cluster.md
https://github.com/longhorn/longhorn/issues/4246
=> manual: test helm on Rancher deployed Windows cluster

manager/integration/tests/requirements.txt, manager/integration/tests/test_settings.py
=> integration: add test cases for setting update via configmap

manager/integration/tests/requirements.txt, manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/2570
https://github.com/longhorn/longhorn/issues/3488
=> [BACKPORT][1.2.x] integration: add test cases for setting update via configmap

manager/integration/tests/test_backing_image.py
https://github.com/longhorn/longhorn/issues/4256
https://github.com/longhorn/longhorn/issues/4297
=> [Backport][v1.3.x] integration: Add test skeletons test_backing_image_cleanup

manager/integration/tests/common.py, manager/integration/tests/test_node.py
https://github.com/longhorn/longhorn/issues/4238
https://github.com/longhorn/longhorn/issues/4313
=> [Backport][v1.3.x] Add and fix test_disk_eviction_with_node_level_soft_anti_affinity_disabled

manager/integration/tests/common.py, manager/integration/tests/test_node.py
https://github.com/longhorn/longhorn/issues/4238
https://github.com/longhorn/longhorn/issues/4314
=> [Backport][v1.2.x] Add and fix test_disk_eviction_with_node_level_soft_anti_affinity_disabled

manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/4308
=> integration: Add validation retry for test_setting_backing_image_auto_cleanup

airgap/terraform/main.tf, manager/integration/tests/common.py
Fix no enough disk space on air gap registry server
For https://github.com/longhorn/longhorn/issues/4350
=> Fix no enough disk space on air gap registry server

manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/4308
https://github.com/longhorn/longhorn/issues/4343
=> [Backport][v1.3.x] integration: Add validation retry for test_setting_backing_image_auto_cleanup

manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/4308
https://github.com/longhorn/longhorn/issues/4344
=> [Backport][v1.2.x] integration: Add validation retry for test_setting_backing_image_auto_cleanup

manager/integration/tests/common.py, manager/integration/tests/test_engine_upgrade.py
https://github.com/longhorn/longhorn/issues/4332
https://github.com/longhorn/longhorn/issues/4338
=> [BACKPORT][v1.3.1] Update engineImage refCount assertions in test cases

manager/integration/tests/common.py, manager/integration/tests/test_engine_upgrade.py
https://github.com/longhorn/longhorn/issues/4332
https://github.com/longhorn/longhorn/issues/4339
=> [BACKPORT][v1.2.5] Update engineImage refCount assertions in test cases

manager/integration/tests/common.py, manager/integration/tests/test_ha.py
The same problem from https://github.com/longhorn/longhorn/issues/4309#issuecomment-1197897496
Verified on local cluster
=> Fix test_engine_crash_for_dr_volume

manager/integration/tests/test_ha.py
https://github.com/longhorn/longhorn/issues/4383
=> integration: Fix test_all_replica_restore_failure

manager/integration/tests/test_ha.py
Longhorn/longhorn#4294
https://github.com/longhorn/longhorn/issues/4365
=> [Backport][v1.3.x] docs: Add a test for the eviction transient error issue

manager/integration/deploy/test.yaml, manager/integration/tests/common.py
=> Fix bug: make sure to cleanup all deployment created by the tests and Allow customization for timeouts when running tests on hdd disk

manager/integration/tests/test_ha.py
https://github.com/longhorn/longhorn/issues/4381
https://github.com/longhorn/longhorn/issues/4383
https://github.com/longhorn/longhorn/issues/4394
=> [BACKPORT][v1.2.x] Fix volume faulted related integration tests

test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke.sh, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_server.sh.tpl
Fix Ubuntu 22.04 SSH authentication failed
For https://github.com/longhorn/longhorn/issues/4320
=> Fix Ubuntu 22.04 SSH authentication failed

manager/integration/tests/test_ha.py
Backport https://github.com/longhorn/longhorn-tests/pull/1075 to v1.3.x
=> [Backport v1.3.x] Fix flaky test_ha_salvage

manager/integration/tests/test_basic.py
Add test case test_default_storage_class_syncup
https://github.com/longhorn/longhorn/issues/4417
=> Add test case test_default_storage_class_syncup

manager/integration/tests/test_basic.py
Backport https://github.com/longhorn/longhorn-tests/pull/1074 to v1.3.x
=> [Backport v1.3.x] Add test case test_default_storage_class_syncup 

test_framework/scripts/longhorn-setup.sh
ci: create new secret in chart air gap installation
=> ci: create new secret in chart air gap installation

manager/integration/tests/common.py, manager/integration/tests/test_basic.py
longhorn/longhorn#4481
Signed-off-by: James Lu <james.lu@suse.com>
=> Add test case: failed backups cleanup

manager/integration/tests/test_migration.py
Add test case `test_migration_with_unscheduled_replica`
=> Add test case test_migration_with_unscheduled_replica

manager/integration/tests/test_migration.py
Backport https://github.com/longhorn/longhorn-tests/pull/1095 to v1.3.x
=> [Backport v1.3.x] Add test case test_migration_with_unscheduled_replica

manager/integration/tests/test_migration.py
Backport https://github.com/longhorn/longhorn-tests/pull/1095 to v1.2.x
=> [Backport 1.2.x] Add test case test_migration_with_unscheduled_replica

benchmark_test/Jenkinsfile, benchmark_test/scripts/benchmark-test-setup.sh, manager/integration/scripts/upgrade-longhorn.sh, manager/integration/tests/conftest.py, manager/integration/tests/test_upgrade.py, test_framework/Jenkinsfile, test_framework/scripts/longhorn-setup.sh
ci: get rid of longhorn-manger repo in test setup
For https://github.com/longhorn/longhorn/issues/4476
=> ci: get rid of longhorn-manger repo in test setup

manager/integration/tests/test_recurring_job.py
Backport https://github.com/longhorn/longhorn-tests/pull/1109 to v1.3.x
=> [Backport v1.3.x] Fix backup count assertion error in recurring job

manager/integration/tests/test_migration.py
Add test case test_migration_with_rebuilding_replica
=> Add test case test_migration_with_rebuilding_replica

manager/integration/tests/test_zone.py
Implement the case to reproduce and validate the fix for https://github.com/longhorn/longhorn/issues/4502
The replica auto-balance should not go into a rebuilding loop when the replica is already running on an un-schedulable node.
=> test(replica-auto-balance): unschedulable node

manager/integration/tests/test_zone.py
https://github.com/longhorn/longhorn/issues/4630
https://github.com/longhorn/longhorn/issues/4502
=> [BACKPORT][v1.3.x] test(replica-auto-balance): unschedulable node

manager/integration/tests/test_zone.py
https://github.com/longhorn/longhorn/issues/4629
https://github.com/longhorn/longhorn/issues/4502
=> [BACKPORT][v1.2.x] test(replica-auto-balance): unschedulable node

manager/integration/tests/test_migration.py
Backport https://github.com/longhorn/longhorn-tests/pull/1099 to v1.3.x
Test result on pipeline : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2033/console
=> [Backport v1.3.x] Implement test case test_migration_with_rebuilding_replica

manager/integration/tests/test_migration.py
Backport https://github.com/longhorn/longhorn-tests/pull/1099 to v1.2.x
Test result on pipeline : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2031/testReport/tests/test_migration/
=> [Backport v1.2.x] Implement test case test_migration_with_rebuilding_replica

manager/integration/tests/test_basic.py
[Longhorn 4531](https://github.com/longhorn/longhorn/issues/4531)
Add test cases to check whether the backup access mode is stored and the correctness of restore.
=> Add test case: check restored volume same as original volume

manager/integration/tests/test_basic.py
[Longhorn 4649](https://github.com/longhorn/longhorn/issues/4649)
(cherry picked from commit 4d01c58adc04fd265fce65b9bcf848e0d7472e69)
=> [Backport v1.3.x]  Add test case: check restored volume same as original volume

manager/integration/tests/test_cloning.py, manager/integration/tests/test_ha.py
test: missed fixing some busybox:1.34.0 in previous commit
For https://github.com/longhorn/longhorn/issues/4685
=> test: missed fixing some busybox:1.34.0 in previous commit

manager/integration/tests/common.py, manager/integration/tests/test_migration.py
Backport https://github.com/longhorn/longhorn-tests/commit/5b0f81c4e37d5a0af8f729f1099c7ce5d3d7de2b to v1.2.x
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2079/testReport/tests/test_migration/) on pipeline using v1.2.x LH images, test_migration.py were all passed
=> [Backport v1.2.x] Add case test_migration_with_failed_replica

cleanup/Dockerfile.setup, cleanup/Jenkinsfile, cleanup/scripts/build.sh, cleanup/scripts/cleanup.sh
ci: pipeline for deleting unexpected long-running testing resources
For https://github.com/longhorn/longhorn/issues/3913
=> ci: pipeline for deleting unexpected long-running testing resources

manager/integration/tests/common.py, manager/integration/tests/test_migration.py
Add test case test_migration_with_restore_volume
=> Add test case test_migration_with_restore_volume

manager/integration/tests/common.py, manager/integration/tests/test_migration.py
Backport https://github.com/longhorn/longhorn-tests/pull/1103 test_migration_with_restore_volume to v1.2.x
=> [Backport v1.2.x] Implement test case test_migration_with_restore_volume

manager/integration/tests/common.py, manager/integration/tests/test_migration.py
Backport  https://github.com/longhorn/longhorn-tests/pull/1103 `test_migration_with_restore_volume` to v1.3.x
=> [Backport v1.3.x] Implement test case test_migration_with_restore_volume

manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py
Implement test case `test_backing_image_auto_resync`
=> Implement test case test_backing_image_auto_resync

manager/integration/tests/test_basic.py
[Longhorn 4736](https://github.com/longhorn/longhorn/issues/4736)
(cherry picked from commit 9abe81b0e7f0e54555d86696c8cf3fdc29f1fecd)
- backport https://github.com/longhorn/longhorn/issues/4653
=> bug(rwx): fix to create rwx volume with PV & PVC deployment

manager/integration/tests/test_basic.py
[Longhorn 4792](https://github.com/longhorn/longhorn/issues/4792)
(cherry picked from commit 578c07373c98bbd98e1d9c4c36f1482b5e8df441)
=> fix(rwx backup): fix failed to backup for RWX volume occasionally

test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/centos/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_server.sh.tpl
ci: refine terraform k3s cloud-init scripts to support k8s v1.25
For https://github.com/longhorn/longhorn/issues/4807
=> ci: refine terraform k3s cloud-init scripts to support k8s v1.25

manager/integration/tests/test_scheduling.py
- https://github.com/longhorn/longhorn/issues/4762
- https://github.com/longhorn/longhorn/issues/4763
- https://github.com/longhorn/longhorn/issues/4761
=> [BACKPORT][v1.3.3] test(replica-auto-balance): with data locality

manager/integration/tests/test_scheduling.py
- https://github.com/longhorn/longhorn/issues/4767
- https://github.com/longhorn/longhorn/issues/4763
- https://github.com/longhorn/longhorn/issues/4761
=> [BACKPORT][v1.2.6] test(replica-auto-balance): with data locality

benchmark_test/Jenkinsfile, benchmark_test/scripts/benchmark-test-setup.sh
test: running different versions of longhorn in the same benchmark test build for comparison
For https://github.com/longhorn/longhorn/issues/4259
=> test: running different versions of longhorn in the same benchmark test build for comparison

manager/integration/tests/test_backing_image.py
Add test case `test_backing_image_cleanup`
=> Add test case test_backing_image_cleanup

manager/integration/tests/test_upgrade.py
=> test: fix drone-publish error

manager/integration/tests/test_backing_image.py
Backport  https://github.com/longhorn/longhorn-tests/pull/1183 to v1.2.x
Test result : [Pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2492/testReport/tests/test_backing_image/test_backing_image_cleanup/)
=> [Backport v1.2.x ] Add test case test_backing_image_cleanup

manager/integration/tests/test_upgrade.py
Ref:
https://github.com/longhorn/longhorn/issues/4726
https://github.com/longhorn/longhorn/issues/4730
=> Add skeleton of test_upgrade_with_auto_upgrade_latest_engine_enabled

manager/integration/pytest.ini, manager/integration/tests/common.py, manager/integration/tests/test_support_bundle.py, test_framework/scripts/rancher/terraform/main.tf
https://github.com/longhorn/longhorn/issues/4908
https://github.com/longhorn/longhorn/issues/2759
=> test(auto): support bundle enhancement

manager/integration/tests/common.py, manager/integration/tests/test_basic.py
Add test case `test_space_usage_for_rebuilding_only_volume`
=> Add test case test_space_usage_for_rebuilding_only_volume

mirror_csi_images/Dockerfile.setup, mirror_csi_images/Jenkinsfile, mirror_csi_images/scripts/publish.sh
ci: update csi images from longhorn-images.txt file
For https://github.com/longhorn/longhorn/issues/3914
=> ci: update csi images from longhorn-images.txt file

manager/integration/tests/common.py, manager/integration/tests/test_recurring_job.py
Add the test case for backing up and restoring recurring jobs and groups.
longhorn/longhorn#2227
=> feat(backup): recording recurring jobs test case

docs/content/manual/pre-release/ha/single-replica-node-down.md
Make test steps more clear
ref: https://github.com/longhorn/longhorn/issues/4793
=> Update single replica node down test case

manager/integration/tests/common.py
test: fix upgrade test failed due to list_support_bundle api error
For https://github.com/longhorn/longhorn/issues/4970
=> test: fix upgrade test failed due to list_support_bundle api error

docs/content/manual/release-specific/v1.4.0/test-engine-binary-recovery.md
https://github.com/longhorn/longhorn/issues/4380
=> test(manual): engine binary recovery

manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py
Ref: [4852](https://github.com/longhorn/longhorn/issues/4852), [4878](https://github.com/longhorn/longhorn/issues/4878)
Waiting issue [4852](https://github.com/longhorn/longhorn/issues/4852)  resolved, then can verify test script
=> test case test_backing_image_with_wrong_md5sum

manager/integration/tests/test_csi_snapshotter.py
Add test case test_csi_snapshot_snap_delete_csi_snapshot
Ref [4995](https://github.com/longhorn/longhorn/issues/4995)
=> Add test case test_csi_snapshot_snap_delete_csi_snapshot

manager/integration/tests/test_provisioner.py
https://github.com/longhorn/longhorn/issues/4922
=> Add test case for FS param in storage class

manager/integration/Dockerfile, manager/integration/tests/common.py, manager/integration/tests/requirements.txt, manager/integration/tests/test_snapshot.py
Longhorn/longhorn#4210
Longhorn/longhorn#3198
=> Implement test cases for snapshot checksum and check features

manager/integration/README.md
I saw @khushboo-rancher created a task https://github.com/longhorn/longhorn/issues/5182; I corrected it locally while trying this. Here is the PR for the same.
Signed-off-by: Shilpi shilpisinha895@gmail.com
=> updated command to watch the test logs

docs/content/manual/release-specific/v1.4.0/test-online-expansion.md, manager/integration/tests/common.py, manager/integration/tests/test_basic.py, manager/integration/tests/test_csi.py, manager/integration/tests/test_ha.py
=> Update tests for online expansion

manager/integration/tests/common.py, manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/4558
https://github.com/longhorn/longhorn/issues/4993
=> test(auto): setting concurrent-backup-restore-limit

docs/content/manual/release-specific/v1.4.0/test-filesystem-trim.md, manager/integration/tests/common.py, manager/integration/tests/test_basic.py
=> integration: Add test_filesystem_trim

manager/integration/tests/common.py
=> Add check for system backup feature support

manager/integration/tests/common.py, manager/integration/tests/test_upgrade.py
issue https://github.com/longhorn/longhorn/issues/4709
=> Add replica deletion rebuilding case steps in the upgrade test

manager/integration/tests/common.py, manager/integration/tests/test_upgrade.py
Ref. https://github.com/longhorn/longhorn/issues/5253
(cherry picked from commit 82dd6889449c1f2c4abdc4f0cf468c761a35b8ad)
=> [BACKPORT][v1.4.x] Add replica deletion rebuilding case steps in the upgrade test

manager/integration/tests/test_basic.py
Enlarge volume size for increasing backup time
Longhorn/longhorn#5189
=> Enlarge volume size in test_backup_status_for_unavailable_replicas

docs/content/manual/pre-release/node/node-drain-deletion.md
[Longhorn 2237](https://github.com/longhorn/longhorn/issues/2237)
=> test(Manual): Stopped replicas on deleted nodes should not be counted as healthy replicas when draining nodes

manager/integration/pytest.ini, manager/integration/tests/test_snapshot.py
issue https://github.com/longhorn/longhorn/issues/4845
=> Add test cases for volume set the snapshot data integrity and fix a typo

qa_docs/testing_guidance.md
Added test guidance having manual testing best practices.
https://github.com/longhorn/longhorn/issues/5178
=> Add test guidance

build_engine_test_images/Dockerfile.setup, build_engine_test_images/Jenkinsfile, build_engine_test_images/run.sh
ci: check if new engine test images need to be published
For https://github.com/longhorn/longhorn/issues/5400
=> ci: check if new engine test images need to be published

manager/integration/tests/common.py, manager/integration/tests/test_upgrade.py
Ref. https://github.com/longhorn/longhorn/issues/5254
(cherry picked from commit 82dd6889449c1f2c4abdc4f0cf468c761a35b8ad)
=> [BACKPORT][v1.3.x] Add replica deletion rebuilding case steps in the upgrade test

docs/content/manual/release-specific/v1.4.0/test-filesystem-trim.md, manager/integration/tests/common.py, manager/integration/tests/test_basic.py
backport of pull request https://github.com/longhorn/longhorn-tests/pull/1169
=> integration: Add test_filesystem_trim (backport #1169)

manager/integration/tests/common.py, manager/integration/tests/test_basic.py, manager/integration/tests/test_csi.py, manager/integration/tests/test_ha.py
integration: Update the existing expansion test to fit the online expansion
backport https://github.com/longhorn/longhorn-tests/pull/1223
=> integration: Update the existing expansion test to fit the online expansion

manager/integration/tests/common.py, manager/integration/tests/test_recurring_job.py
https://github.com/longhorn/longhorn/issues/5273
https://github.com/longhorn/longhorn/issues/3836
=> test(recurring-job): snapshot cleanup

manager/integration/tests/test_recurring_job.py
Update test case validate string in test case test_recurring_jobs_maximum_retain
Ref: [5434](https://github.com/longhorn/longhorn/issues/5434)
=> Update test_recurring_jobs_maximum_retain validate string

docs/content/manual/pre-release/node/node-disconnection.md
test: update node disconnection test for behavior change
For https://github.com/longhorn/longhorn/issues/5476
=> test: update node disconnection test for behavior change

manager/integration/tests/common.py, manager/integration/tests/test_recurring_job.py
https://github.com/longhorn/longhorn/issues/5273
https://github.com/longhorn/longhorn/pull/5416
https://github.com/longhorn/longhorn/issues/3836
=> [BACKPORT][v1.3.3] test(recurring-job): snapshot cleanup

docs/content/manual/pre-release/backup-and-restore/restore-volume-node-down.md
https://github.com/longhorn/longhorn/issues/5666
=> fix(manual): The node the restore volume attached to is down

test_framework/Jenkinsfile, test_framework/terraform/aws/sle-micro/data.tf, test_framework/terraform/aws/sle-micro/k3s_instaces.tf, test_framework/terraform/aws/sle-micro/main.tf, test_framework/terraform/aws/sle-micro/output.tf, test_framework/terraform/aws/sle-micro/rke2_instances.tf, test_framework/terraform/aws/sle-micro/rke_instances.tf, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_rke2_server.sh.tpl, test_framework/terraform/aws/sle-micro/variables.tf
ci: add sle-micro provisioning
For https://github.com/longhorn/longhorn/issues/5675
=> ci: add sle-micro provisioning

manager/integration/tests/test_recurring_job.py
https://github.com/longhorn/longhorn-tests/pull/1233#discussion_r1115289497
=> doc(auto): typo in recurring job tests

docs/content/manual/pre-release/ha/backing-image-error-reporting-and-retry.md
issue https://github.com/longhorn/longhorn/issues/5539
=> Update CLI steps for verifying backing image sync failure test case

manager/integration/tests/common.py
test: add gke default sc to avoid cleanup fail in gke
For https://github.com/longhorn/longhorn/issues/5733
=> test: add gke default sc to avoid cleanup fail in gke

manager/integration/tests/node.py, manager/integration/tests/test_support_bundle.py
https://github.com/longhorn/longhorn/issues/5614
=> fix(support-bundle): fix support-bundle agent test cases

manager/integration/tests/test_settings.py
test: fix flaky test case test_setting_concurrent_rebuild_limit by not explicitly waiting for a specific replica rebuilding
For https://github.com/longhorn/longhorn/issues/4977
=> test: fix flaky test case test_setting_concurrent_rebuild_limit

manager/integration/tests/test_cloning.py
test: fix flaky test case test_cloning_with_detached_source_volume by deferring the snapshot creation check
For https://github.com/longhorn/longhorn/issues/4848
The source volume will be automatically attached and detached during the clone process, since it will be detached immediately after the clone is completed, it's nearly impossible to always catch the moment of the source volume is still attached and get the snapshot list. Defer the snapshot creation check to the end of the test case by manually attaching the source volume.
=> test: fix flaky test case test_cloning_with_detached_source_volume

docs/content/manual/rancher-integration/_index.md, docs/content/manual/rancher-integration/access-lh-gui-using-rancher-ui.md, docs/content/manual/rancher-integration/drain-using-rancher-ui.md, docs/content/manual/rancher-integration/fleet-deploy.md, docs/content/manual/rancher-integration/lh-hardend-rancher.md, docs/content/manual/rancher-integration/upgrade-using-rancher-ui.md, docs/content/manual/rancher-integration/upgrade-using-suc.md
https://github.com/longhorn/longhorn/issues/5505
=> Add Rancher integration test

manager/integration/deploy/test.yaml, manager/integration/pytest.ini, manager/integration/tests/common.py, manager/integration/tests/test_cluster_autoscaler.py, manager/integration/tests/test_node.py, manager/integration/tests/test_zone.py
https://github.com/longhorn/longhorn/issues/2203
=> Add tests for cluster autoscaler

manager/integration/tests/requirements.txt
test: fix urllib3 dependency conflict
=> test: fix urllib3 dependency conflict

manager/integration/tests/test_csi.py
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3600/)
Ref [5820](https://github.com/longhorn/longhorn/issues/5820)
Signed-off-by: Chris <chris.chien@suse.com>
=> Add case test_csi_block_volume_online_expansion

manager/integration/tests/common.py, manager/integration/tests/test_recurring_job.py
https://github.com/longhorn/longhorn/issues/5528
https://github.com/longhorn/longhorn/issues/5186
=> test(recurring-job): filesystem-trim

manager/integration/tests/common.py
https://github.com/longhorn/longhorn/issues/5792
https://github.com/longhorn/longhorn/issues/5501
=> fix(air-gap): failed image pull

test_framework/terraform/aws/sle-micro/k3s_instaces.tf, test_framework/terraform/aws/sle-micro/rke2_instances.tf, test_framework/terraform/aws/sle-micro/rke_instances.tf
ci: install apparmor-parser on sle-micro
=> ci: install apparmor-parser on sle-micro

docs/content/manual/pre-release/node-not-ready/_index.md, docs/content/manual/pre-release/node-not-ready/node-down/_index.md
=> Update index.md by removing unneeded lines and fixing a typo

manager/integration/tests/test_settings.py
test: fix instance manager consolidation fails pod updating related test cases
For https://github.com/longhorn/longhorn/issues/5208
=> test: fix instance manager consolidation fails pod updating related test cases

manager/integration/tests/common.py
https://github.com/longhorn/longhorn/issues/5849
=> Remove deprecated mkfs-ext4-parameters setting

manager/integration/tests/test_scheduling.py
https://github.com/longhorn/longhorn/issues/5909
=> fix(auto/sle-micro): test_replica_schedule_to_disk_with_most_usable_storage

cleanup/scripts/cleanup.sh
ci: refine cleanup resources pipeline for instance launch time format change
=> ci: refine cleanup resources pipeline for instance launch time format change

manager/integration/tests/test_snapshot.py
test: fix flaky test cases test_snapshot_hash_detect_corruption_in_global_enabled_mode and test_snapshot_hash_detect_corruption_in_global_fast_check_mode
(1) cronjob setting: in the current implementation, it's possible that the cronjob is set to something like: 59/5 6 * * *. This cronjob will only be executed once per day on 6:59 AM, and if the test case missed this chance to trigger the integrity check, it has to wait until tomorrow, so the test case will timeout and fail. This PR changes the cronjob to something like: 59,4,9,14,19,24,29 6,7 * * * (every 5 minutes in the upcoming 30 minutes), so if 6:59 AM is missed, it can still be triggered on 7:04 AM.  
(2) wait toleration: in the current implementation, it has a wait toleration 60s to handle that we're unable to precisely predict …
=> test: fix flaky test case test_snapshot_hash_detect_corruption

test_framework/Dockerfile.setup, test_framework/Jenkinsfile, test_framework/scripts/cleanup.sh, test_framework/scripts/download-support-bundle.sh, test_framework/scripts/longhorn-setup.sh, test_framework/scripts/terraform-setup.sh, test_framework/terraform/gcp/gke/main.tf, test_framework/terraform/gcp/gke/output.tf, test_framework/terraform/gcp/gke/variables.tf
ci: add gke provisioning
For https://github.com/longhorn/longhorn/issues/4621
=> ci: add gke provisioning

test_framework/Jenkinsfile, test_framework/scripts/cleanup.sh, test_framework/scripts/download-support-bundle.sh, test_framework/scripts/longhorn-setup.sh, test_framework/scripts/terraform-setup.sh, test_framework/terraform/azure/aks/main.tf, test_framework/terraform/azure/aks/output.tf, test_framework/terraform/azure/aks/variables.tf
ci: add aks provisioning
For https://github.com/longhorn/longhorn/issues/4621
=> ci: add aks provisioning

manager/integration/tests/common.py, manager/integration/tests/test_settings.py
https://github.com/longhorn/longhorn/issues/5917
=> test: remove guarenteed cpu settings

manager/integration/tests/test_recurring_job.py
https://github.com/longhorn/longhorn/issues/5791
=> test(recurring-job): PVC label

manager/integration/tests/test_zone.py
https://github.com/longhorn/longhorn/issues/5993
https://github.com/longhorn/longhorn/issues/5971
=> test(replica-auto-balance): respect node selector

manager/integration/tests/test_ha.py
Add test case `test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume`
ref: [5974](https://github.com/longhorn/longhorn/issues/5974)
=> test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume

manager/integration/tests/test_support_bundle.py
https://github.com/longhorn/longhorn/issues/5882
=> test(support-bundle): should replace existing

manager/integration/tests/common.py, manager/integration/tests/test_scheduling.py
https://github.com/longhorn/longhorn/issues/5448
=> test(data-locality): strict local should schedule Pod to the same node

manager/integration/tests/test_system_backup_restore.py
https://github.com/longhorn/longhorn/issues/5011
=> test(system-backup): volume backup policies

docs/content/manual/release-specific/v1.5.0/test-upgrade-responder-collect-extra-info.md
https://github.com/longhorn/longhorn/issues/5235
=> test(upgrade_request): collect extra info

test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_server.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_server.sh.tpl
=> Remove broken systemctl line from Rocky setup

docs/content/manual/pre-release/node-not-ready/node-down/node-drain-deletion.md
Update the manual test plan since the setting has been changed
=> doc(manual test): update the setting name for drain node policy

manager/integration/tests/test_kubernetes.py
=> Add test skeleton test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly

manager/integration/tests/common.py, manager/integration/tests/test_upgrade.py
Explanation:
* https://github.com/longhorn/longhorn/issues/6200#issuecomment-1610031861
* https://github.com/longhorn/longhorn/issues/6200#issuecomment-1610274243
longhorn/longhorn#6200
=> Fix upgrade test

manager/integration/tests/common.py, manager/integration/tests/test_ha.py
Backup volume needs some time to synchronize the information when last backup is completed.
Ref: longhorn/longhorn#6213
=> fix(backup): wait for backup volume synced

test_framework/terraform/aws/sles/k3s_instaces.tf, test_framework/terraform/aws/ubuntu/k3s_instaces.tf
ci: sudo cat cloud-init log to avoid permission issue
For https://github.com/longhorn/longhorn/issues/3856
=> ci: sudo cat cloud-init log to avoid permission issue

manager/integration/tests/test_ha.py
Fix flaky test case `test_recovery_from_im_deletion`
Immediately exec into deployment pod after instance-manager pod delete and recreate ready some how will get `kubernetes.client.exceptions.ApiException` make test case flaky.
Add a retry mechanism to fetch deployment pod data to avoid test case directly fail
Master branch test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4381/) 5/10 failure
PR code test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4382/) 0/10 failure
ref [6222](https://github.com/longhorn/longhorn/issues/6222)
=>  Fix flaky test case test_recovery_from_im_deletion

manager/integration/scripts/upgrade-longhorn.sh, manager/integration/tests/common.py, manager/integration/tests/test_upgrade.py
test: create custom resources before upgrade
For https://github.com/longhorn/longhorn/issues/6249
=> test: create custom resources before upgrade

manager/integration/tests/test_upgrade.py
test: refine upgrade test for backward compatibility
(1) for upgrade from v1.3.x to v1.4.x, there's no system backup in v1.3.x, add checking before create one 
(2) for upgrade from v1.3.x to v1.4.x, there's no restoreInitiated key in v1.4.x, use alternative way to check restore 
(3) delete orphan created in upgrade test to avoid affecting following test cases
For https://github.com/longhorn/longhorn/issues/6249
=> test: refine upgrade test for backward compatibility

test_framework/Jenkinsfile, test_framework/scripts/longhorn-setup.sh, test_framework/terraform/aws/sles/data.tf, test_framework/terraform/aws/sles/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/sles/user-data-scripts/provision_rke2_server.sh.tpl, test_framework/terraform/aws/sles/variables.tf
ci: add cis-1.23 hardening in sles rke2 terraform script
For https://github.com/longhorn/longhorn/issues/6092
=> ci: add cis-1.23 hardening in sles rke2 terraform script

manager/integration/tests/test_snapshot.py
longhorn/longhorn#6298
https://github.com/longhorn/longhorn/issues/6312
=> Add test skeleton test_snapshot_cr

manager/integration/tests/common.py
https://github.com/longhorn/longhorn/issues/6320
=> fix(support-bundle): test_support_bundle_purge

manager/integration/tests/test_csi_snapshotter.py
Add test case `test_csi_volumesnapshot_restore_on_demand_backing_image`
ref: [6231](https://github.com/longhorn/longhorn/issues/6231)
Add test case `test_csi_volumesnapshot_backing_image_basic`
ref: [6293](https://github.com/longhorn/longhorn/issues/6293)
Add test case `test_csi_volumesnapshot_restore_pre_provision_backing_image`
ref: [6309](https://github.com/longhorn/longhorn/issues/6309)
Signed-off-by: Chris <chris.chien@suse.com>
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4643/testReport/tests/test_csi_snapshotter/)
=> Add test case test_csi_volumesnapshot_restore_on_demand_backing_image, test_csi_volumesnapshot_backing_image_basic

manager/integration/tests/test_kubernetes.py
Add test case test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly
ref: [6373](https://github.com/longhorn/longhorn/issues/6373)
=> Add test case test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly

manager/integration/tests/test_scheduling.py
Add test case `test_soft_anti_affinity_scheduling_volume_disable`
ref: [6394](https://github.com/longhorn/longhorn/issues/6394)
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4680/testReport/tests/test_scheduling/)
Add test case `test_soft_anti_affinity_scheduling_volume_enable`
ref: [6409](https://github.com/longhorn/longhorn/issues/6409)
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4682/testReport/tests/test_scheduling/)
=> Add test case test_soft_anti_affinity_scheduling_volume_disable

manager/integration/tests/common.py, manager/integration/tests/test_snapshot.py
Add test case `test_snapshot_cr`
ref: [6418](https://github.com/longhorn/longhorn/issues/6418), https://github.com/longhorn/longhorn/issues/6312
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4710/testReport/tests/test_snapshot/)
=> Add test case test_snapshot_cr

test_framework/scripts/download-support-bundle.sh
test: print messages to debug download support bundle parsing error
For https://github.com/longhorn/longhorn/issues/6186
=> test: print messages to debug download support bundle parsing error

manager/integration/tests/test_rwx.py
Add test skeleton of
- `test_rwx_onine_expansion`
- `test_rwx_offine_expansion`
ref: [2181](https://github.com/longhorn/longhorn/issues/2181), [2484](https://github.com/longhorn/longhorn/issues/2484)
=> Add test skeleton of test_rwx_onine_expansion and test_rwx_offine_expansion

manager/integration/tests/aws.py
Fixed AWS environment variable validations.
=> fix(integration): aws environment variable validations

docs/content/manual/pre-release/upgrade/test-node-drain-policy.md
longhorn/longhorn#5549
longhorn/longhorn#5620
=> Add manual test for Test Node Drain Policy Setting AND remove deprecated allow-node-drain-with-last-healthy-replica setting

manager/integration/Dockerfile, manager/integration/deploy/test.yaml, manager/integration/tests/common.py, manager/integration/tests/conftest.py, manager/integration/tests/test_upgrade.py, pipelines/flux/Dockerfile.setup, pipelines/flux/Jenkinsfile, pipelines/flux/scripts/build.sh, pipelines/flux/scripts/longhorn-setup.sh, pipelines/flux/scripts/upgrade-longhorn.sh, pipelines/utilities/flux.sh, pipelines/utilities/run_longhorn_test.sh
ci: implement flux install/upgrade regression test pipeline
For https://github.com/longhorn/longhorn/issues/3987 https://github.com/longhorn/longhorn/issues/6343 https://github.com/longhorn/longhorn/issues/5936
=> ci: implement flux install/upgrade regression test pipeline

test_framework/scripts/download-support-bundle.sh
test: fix download support bundle randomly failed
For https://github.com/longhorn/longhorn/issues/6503
=> test: fix download support bundle randomly failed

manager/integration/tests/test_engine_upgrade.py, manager/integration/tests/test_ha.py, manager/integration/tests/test_upgrade.py
=> Replace spec.engineImage with spec.image in volume, replica and engine resources

e2e/keywords/common.resource, e2e/keywords/node.resource, e2e/keywords/recurring_job.resource, e2e/keywords/volume.resource, e2e/libs/keywords/common_keywords.py, e2e/libs/keywords/node_keywords.py, e2e/libs/keywords/recurring_job_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/node_exec/node_exec.py, e2e/libs/recurring_job/__init__.py, e2e/libs/recurring_job/base.py, e2e/libs/recurring_job/crd.py, e2e/libs/recurring_job/recurring_job.py, e2e/libs/recurring_job/rest.py, e2e/libs/utility/utility.py, e2e/libs/volume/base.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/requirements.txt, e2e/tests/heavy_writing_and_recurring_jobs.robot, e2e/tests/node_reboot.robot, e2e/tests/replica_resiliency_test.robot
test: negative test case involves 2 volumes and recurring jobs
For https://github.com/longhorn/longhorn/issues/6498
=> test: negative test case involves 2 volumes and recurring jobs

e2e/keywords/common.resource, e2e/keywords/node.resource, e2e/keywords/volume.resource, e2e/keywords/workload.resource, e2e/libs/keywords/node_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/node/node.py, e2e/libs/utility/utility.py, e2e/libs/volume/volume.py, e2e/libs/workload/__init__.py, e2e/libs/workload/workload.py, e2e/templates/litmus/reboot-node.yaml, e2e/templates/workload/deployment_with_rwo_volume.yaml, e2e/templates/workload/deployment_with_rwx_volume.yaml, e2e/templates/workload/rwo_pvc.yaml, e2e/templates/workload/rwx_pvc.yaml, e2e/templates/workload/statefulset_with_rwo_volume.yaml, e2e/templates/workload/statefulset_with_rwx_volume.yaml, e2e/tests/cluster_restart.robot, e2e/tests/heavy_writing_and_recurring_jobs.robot
test: add cluster restart test case
For https://github.com/longhorn/longhorn/issues/6667
=> test: add cluster restart test case

manager/integration/Dockerfile, manager/integration/tests/test_upgrade.py, pipelines/argocd/Dockerfile.setup, pipelines/argocd/Jenkinsfile, pipelines/argocd/scripts/build.sh, pipelines/argocd/scripts/longhorn-setup.sh, pipelines/argocd/scripts/upgrade-longhorn.sh, pipelines/utilities/argocd.sh, pipelines/utilities/kubeconfig.sh
ci: implement argocd install/upgrade regression test pipeline
For https://github.com/longhorn/longhorn/issues/3987 https://github.com/longhorn/longhorn/issues/5936 https://github.com/longhorn/longhorn/issues/6434
=> ci: implement argocd install/upgrade regression test pipeline

e2e/libs/keywords/common_keywords.py, e2e/libs/keywords/engine_keywords.py, e2e/libs/keywords/node_keywords.py, e2e/libs/keywords/pod_keywords.py, e2e/libs/keywords/recurring_job_keywords.py, e2e/libs/keywords/replica_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/node/node.py, e2e/libs/node_exec/node_exec.py, e2e/libs/recurring_job/crd.py, e2e/libs/recurring_job/recurring_job.py, e2e/libs/recurring_job/rest.py, e2e/libs/replica/crd.py, e2e/libs/replica/replica.py, e2e/libs/utility/utility.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/workload/workload.py
test: add realtime logs to track test execution progress
For https://github.com/longhorn/longhorn-tests/pull/1515#discussion_r1311215163
=> test: add realtime logs to track test execution progress

e2e/libs/node/node.py, e2e/libs/utility/utility.py, e2e/libs/volume/crd.py, e2e/libs/workload/workload.py, e2e/run.sh, e2e/tests/cluster_restart.robot, e2e/tests/heavy_writing_and_recurring_jobs.robot, e2e/tests/node_reboot.robot, e2e/tests/replica_rebuilding.robot, e2e/tests/replica_resiliency_test.robot
test: dynamically set wait condition timeout and reduce log size
For https://github.com/longhorn/longhorn/issues/6667
=> test: dynamically set wait condition timeout and reduce log size

manager/integration/tests/common.py, manager/integration/tests/test_basic.py, manager/integration/tests/test_ha.py, manager/integration/tests/test_scheduling.py, manager/integration/tests/test_tagging.py
Ref: longhorn/longhorn#6830
[Test Cases for Volume Condition Type on `master-head`](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4990/testReport/tests/)
[2-stage upgrade on `master-head` ](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4988/)
=> Update Test Cases for volume condition type

docs/content/manual/release-specific/v1.6.0/test-rebuild-in-meta-blocks-engine-start.md
https://github.com/longhorn/longhorn/issues/6626
=> test: fix `Rebuild` in volume.meta blocks engine start

docs/content/manual/Test-cases-to-reproduce-attach-detach-issues/_index.md, docs/content/manual/Test-cases-to-reproduce-attach-detach-issues/attachment-detachment-issues-reproducibility.md
Added identified test cases which might help in reproducing the issues related to attaching detaching of volume
=> Add test cases to reproduce attach-detach issues

docs/content/manual/pre-release/basic-operations/storage-network.md, docs/content/manual/release-specific/v1.6.0/test-storage-network.md
https://github.com/longhorn/longhorn/issues/6953
=> test(manual): storage-network on Multus version above v4.0.0

e2e/keywords/kubelet.resource, e2e/libs/keywords/kubelet_keywords.py, e2e/libs/kubelet/kubelet.py, e2e/libs/node_exec/node_exec.py, e2e/libs/utility/utility.py, e2e/libs/workload/pod.py, e2e/tests/kubelet_restart.robot
test: implement kubelet restart
currently only support k3s
For https://github.com/longhorn/longhorn/issues/6707
=> test: implement kubelet restart

e2e/keywords/common.resource, e2e/keywords/node.resource, e2e/libs/keywords/network_keywords.py, e2e/libs/network/network.py, e2e/libs/node_exec/node_exec.py, e2e/libs/utility/utility.py, e2e/tests/cluster_restart.robot, e2e/tests/node_reboot.robot
test: inject control plane node network latency
For https://github.com/longhorn/longhorn/issues/6704 https://github.com/longhorn/longhorn/issues/6818
=> test: inject control plane node network latency

e2e/libs/keywords/volume_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/kubelet/kubelet.py, e2e/libs/network/network.py, e2e/libs/node/stress.py, e2e/libs/utility/utility.py
=> refactor(negative): cleanup

e2e/libs/engine/crd.py
=> fix(negative): import "utils.common_utils" could not be resolved

e2e/libs/engine/engine.py
=> fix(negative): "logging" is not defined

e2e/libs/volume/crd.py
=> refactor(negative): improve logging

e2e/keywords/volume.resource, e2e/keywords/workload.resource, e2e/libs/keywords/volume_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/volume/base.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/libs/workload/workload.py
Improve readability by renaming the function to reflect its purpose.
=> refactor(negative): rename function to reflect purpose

docs/content/manual/pre-release/upgrade/upgrade-with-new-instance-manager.md
=> Update `Test System Upgrade with New Instance Manager`

e2e/libs/engine/crd.py, e2e/libs/engine/engine.py
=> refactor(negative): consolidate engine validation

e2e/libs/keywords/node_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/network/network.py, e2e/libs/node/node.py, e2e/libs/node/utility.py, e2e/libs/utility/utility.py
- Consolidated list node functions.
- Rename and reorganize the get node function.
=> refactor(negative): cleanup get/list node functions

e2e/keywords/node.resource, e2e/keywords/volume.resource, e2e/libs/keywords/volume_keywords.py, e2e/libs/volume/crd.py, e2e/libs/volume/volume.py, e2e/libs/workload/pod.py, e2e/tests/stress_cpu.robot, e2e/tests/stress_memory.robot
https://github.com/longhorn/longhorn/issues/6951
=> test(negative): stress cpu/mem during volume attach detach

e2e/keywords/node.resource, e2e/libs/keywords/node_keywords.py, e2e/libs/node/utility.py, e2e/tests/stress_cpu.robot, e2e/tests/stress_memory.robot
- Reorganize to another file for test case expansion
- Improve reliability
- Consolidate duplicated codes
=> refactor(negative): enhance stress cpu/mem keywords

e2e/libs/node/node.py
test(negative): force stop instances to simulate hard shutdown
For https://github.com/longhorn/longhorn/issues/7093
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
=> test(negative): force stop instances to simulate hard shutdown

e2e/libs/keywords/volume_keywords.py, e2e/libs/volume/volume.py
=> refactor(negative): remove unused imports

docs/content/manual/release-specific/v1.6.0/test-support-bundle-kubelet-log-for-k3s.md
https://github.com/longhorn/longhorn/issues/7121
=> test(manual): support bundle should include kubelet log when on K3s cluster

manager/integration/tests/test_node.py
longhorn/longhorn#7021 (for longhorn/longhorn#2238)
=> Add test skeletons for new node drain policies

docs/content/manual/release-specific/v1.6.0/test-storage-network.md
https://github.com/longhorn/longhorn/issues/5048
=> test(manual): Multus thick plugin

manager/integration/tests/test_ha.py
=> Replace `spec.engineImage` with `spec.image` in `volume`

manager/integration/tests/test_zone.py
https://github.com/longhorn/longhorn/issues/6508
https://github.com/longhorn/longhorn/issues/7273
=> test(integration): replica-auto-balance when disabled disk scheduling in zone

manager/integration/tests/test_zone.py
https://github.com/longhorn/longhorn/issues/6671
https://github.com/longhorn/longhorn/issues/7276
=> test(integration): replica-auto-balance when no storage available

manager/integration/tests/common.py, manager/integration/tests/test_csi.py, manager/integration/tests/test_rwx.py
Longhorn/longhorn#7045
Longhorn/longhorn#7046
=> rwx: implement test_encrypted_rwx_volume

pipelines/utilities/argocd.sh
ci: set helmPreUpgradeCheckerJob.enabled = false in argocd pipeline
For https://github.com/longhorn/longhorn/issues/6946
=> ci: set helmPreUpgradeCheckerJob.enabled = false in argocd pipeline

manager/integration/Dockerfile, manager/integration/tests/test_upgrade.py, pipelines/fleet/Dockerfile.setup, pipelines/fleet/Jenkinsfile, pipelines/fleet/scripts/build.sh, pipelines/fleet/scripts/longhorn-setup.sh, pipelines/fleet/scripts/upgrade-longhorn.sh, pipelines/utilities/fleet.sh
ci: add pipeline for fleet
For https://github.com/longhorn/longhorn/issues/6935
=> ci: add pipeline for fleet

test_tools/gen_data/README.md, test_tools/gen_data/clean.sh, test_tools/gen_data/config.yaml, test_tools/gen_data/deployment.yaml, test_tools/gen_data/run.sh, test_tools/gen_data/statefulset.yaml
Add generate test data script 
- test_tools/gen_data/clean.sh
- clean workload
- test_tools/gen_data/config.yaml
- config
- test_tools/gen_data/deployment.yaml  
- template
- test_tools/gen_data/README.md
- test_tools/gen_data/run.sh
- test_tools/gen_data/statefulset.yaml    
- template
`./run.sh`
`./clean.sh`
ref: [6665](https://github.com/longhorn/longhorn/issues/6665)
=> Script to generate test data

manager/integration/tests/common.py, manager/integration/tests/test_node.py
ref: https://github.com/longhorn/longhorn/issues/6978
=> test(node): add auto detach manually attached volume when node cordoned

docs/content/manual/release-specific/v1.6.0/test-upgrade-responder-collect-spdk-related-info.md
https://github.com/longhorn/longhorn/issues/6033
Depends on https://github.com/longhorn/longhorn-manager/pull/2346.
=> test(manual): upgrade responder should collect SPDK info

.github/workflows/publish.yaml
ci(gh-action): test using github runner for publish docs action
=> ci(gh-action): test using github runner for publish docs action

pipelines/e2e/Dockerfile.setup, pipelines/utilities/run_longhorn_e2e_test.sh
ci(negative): fix build test env image system-wide python package installation error
For https://github.com/longhorn/longhorn/issues/7308
=> ci(negative): fix build test env image system-wide python package installation error

manager/integration/tests/common.py
test: shorten check interval in wait_for_engine_image_condition
For https://github.com/longhorn/longhorn/issues/7433
=> test: shorten check interval in wait_for_engine_image_condition

docs/content/manual/release-specific/v1.6.0/test-engine-version-enforcement.md
https://github.com/longhorn/longhorn/issues/5842
=> test: engine version enforcement

manager/integration/tests/common.py, manager/integration/tests/test_settings.py
=> e2e: add test_setting_v1_data_engine

manager/integration/tests/test_node.py
=> Add skeleton for test_do_not_react_to_brief_kubelet_restart

manager/integration/tests/common.py, manager/integration/tests/test_metric.py
https://github.com/longhorn/longhorn/issues/5869
https://github.com/longhorn/longhorn/issues/7318
=> test(integration): snapshots metric collection

manager/integration/tests/common.py, manager/integration/tests/test_basic.py, manager/integration/tests/test_node.py, manager/integration/tests/test_orphan.py
https://github.com/longhorn/longhorn/issues/3161
=> test: talos support

manager/integration/tests/common.py
test: fix flaky test case test_recovery_from_im_deletion
For https://github.com/longhorn/longhorn/issues/7544
=> test: fix flaky test case test_recovery_from_im_deletion

manager/integration/tests/test_metric.py
https://github.com/longhorn/longhorn/issues/7532
=> fix(integration): test_metric_longhorn_snapshot_actual_size_bytes

manager/integration/tests/test_backing_image.py
Add test case `test_volume_wait_for_backing_image_condition`
ref: [7516](https://github.com/longhorn/longhorn/issues/7516)
test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5807/)
=> test: add test_volume_wait_for_backing_image_condition

manager/integration/tests/test_basic.py
Add test case `test_pvc_storage_class_name_from_backup_volume`
ref: [7454](https://github.com/longhorn/longhorn/issues/7454)
test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5785/)
=> test: add test_pvc_storage_class_name_from_backup_volume

manager/integration/tests/test_settings.py
Modify setting test cases for the new behavior.
Ref: longhorn/longhorn#7173
=> feat(setting): lazy update for volume-related settings

manager/integration/tests/test_rwx.py
Issue  https://github.com/longhorn/longhorn/issues/7639
Add a test to rwx regressions to use a storage class with customized NFS mount options.
=> feat(rwx):  add a test to check mount options override.

manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py, manager/integration/tests/test_basic.py, manager/integration/tests/test_cluster_autoscaler.py, manager/integration/tests/test_ha.py, manager/integration/tests/test_migration.py, manager/integration/tests/test_orphan.py, manager/integration/tests/test_recurring_job.py, manager/integration/tests/test_scheduling.py, manager/integration/tests/test_settings.py, manager/integration/tests/test_snapshot.py, manager/integration/tests/test_upgrade.py, manager/integration/tests/test_zone.py
Issue:
- longhorn/longhorn#7768
- longhorn/longhorn#7771
Extend `test_recurring_job_filesystem_trim` with pytest.mark.parametrize fixture to test RWO and RWX volumes.
None
None
=> test(recurring-job/fstrim): test RWO and RWX volume

e2e/keywords/workload.resource, e2e/tests/stress_cpu.robot, e2e/tests/stress_memory.robot
Details https://github.com/longhorn/longhorn/issues/7707#issuecomment-1911322648
longhorn/longhorn#7707
=> Fix Negative test case failed: Stress Volume Node CPU/Memory When Volume Is Offline Expanding

manager/integration/tests/test_zone.py
Issue `N/A`
Fix typo.
`None`
`None`
=> fix(integration): typo

e2e/libs/replica/rest.py, e2e/libs/utility/utility.py, e2e/libs/volume/rest.py
Issue https://github.com/longhorn/longhorn/issues/7811
Add try/catch for every Longhorn API call to avoid it throws exception and fail the test case.
=> test(negative): add try/catch for api calls to increase robustness

.github/mergify.yml
This reverts commit 8b4dce86baa56beb041f4d52c995c326bf0e2971.
=> Revert "Update mergify.yml"

manager/integration/tests/test_ha.py
Issue https://github.com/longhorn/longhorn/issues/7936
Replace assertion with wait mechanism.
=> test: fix flaky test case test_extra_replica_cleanup

build_engine_test_images/terraform/aws/ubuntu/variables.tf, scalability_test/terraform/variables.tf, test_framework/terraform/aws/centos/variables.tf, test_framework/terraform/aws/eks/main.tf, test_framework/terraform/aws/oracle/variables.tf, test_framework/terraform/aws/rhel/variables.tf, test_framework/terraform/aws/rockylinux/variables.tf, test_framework/terraform/aws/sle-micro/variables.tf, test_framework/terraform/aws/sles/variables.tf, test_framework/terraform/aws/ubuntu/variables.tf
Issue https://github.com/longhorn/longhorn/issues/7957
use more cost-effective ec2 instance type
=> ci: use more cost-effective ec2 instance type

test_framework/terraform/aws/oracle/variables.tf, test_framework/terraform/aws/rhel/variables.tf
Issue https://github.com/longhorn/longhorn/issues/7653
update oracle/rhel distro version to 9.3
=> ci: update oracle/rhel distro version

manager/integration/tests/test_basic.py
https://github.com/longhorn/longhorn/issues/7997
=> integration: Improve DR volume with backup deletion case

.drone.yml
Issue https://github.com/longhorn/longhorn/issues/8051
build image in pr check to avoid unexpected dependencies updating corrupts image build process.
=> ci: build image in pr check

build_engine_test_images/terraform/aws/ubuntu/variables.tf, pipelines/storage_network/terraform/variables.tf, scalability_test/terraform/variables.tf, test_framework/terraform/aws/centos/variables.tf, test_framework/terraform/aws/eks/main.tf, test_framework/terraform/aws/oracle/variables.tf, test_framework/terraform/aws/rhel/variables.tf, test_framework/terraform/aws/rockylinux/variables.tf, test_framework/terraform/aws/sle-micro/variables.tf, test_framework/terraform/aws/sles/variables.tf, test_framework/terraform/aws/ubuntu/variables.tf
Issue https://github.com/longhorn/longhorn/issues/7957
Revert "ci: use more cost-effective ec2 instance type"
=> Revert "ci: use more cost-effective ec2 instance type"

e2e/libs/volume/crd.py
Issue longhorn/longhorn#8208
Add retries for the `dd` command to capture failures before invoking the `md5sum` calculation.  This also allows delay for failure investigation with the `RETRY_COUNT` variable.
=> fix(negative): write_random_data

pipelines/utilities/longhorn_rancher_chart.sh, test_framework/scripts/longhorn-setup.sh
Issue https://github.com/longhorn/longhorn/issues/8095
add retry for getting rancher api key since it could be flaky like https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/50/
=> ci: add retry for getting rancher api key

mirror_csi_images/scripts/publish.sh
=> Add automation for mirroring the quay.io/openshift/origin-oauth-proxy image

test_framework/scripts/longhorn-setup.sh
Issue https://github.com/longhorn/longhorn/issues/7166
fix longhorn installation failed on private pipeline
=> ci: fix longhorn installation failed on private pipeline

e2e/README.md, e2e/tests/regression/volume_basic.robot
add test case tag and description
=> test(robot): add test case tag and description

manager/integration/tests/common.py
Issue longhorn/longhorn#8348
Fix the v1.5.5-rc1 failed test case `test_backuptarget_invalid`
Verified on local
N/A
=> fix(intergration): test_backuptarget_invalid

e2e/keywords/workload.resource, e2e/libs/workload/workload.py
Issue N/A
fix wait_for_workload_pods_stable assertion failed
=> test(robot): fix wait_for_workload_pods_stable assertion failed

e2e/libs/keywords/backupstore_keywords.py, e2e/libs/utility/utility.py
=> test(robot): fix backupstore setup

e2e/keywords/common.resource, e2e/keywords/node.resource, e2e/libs/keywords/node_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/node/node.py, e2e/libs/volume/crd.py, e2e/libs/volume/volume.py, e2e/tests/v2/volume.robot
=> test(robot): add basic v2 volume test

e2e/README.md
Issue https://github.com/longhorn/longhorn/issues/6583
add export backup target related variable to readme
=> test(robot): add export backup target related variable to readme

manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/8521
print message when assertion failed
=> test: print message when assertion failed

manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/8520
fix longhorn.ApiError not found status code 404
=> test: fix longhorn.ApiError not found status code 404

pipelines/rancher/Jenkinsfile, pipelines/rancher/scripts/longhorn-setup.sh, pipelines/utilities/longhorn_rancher_chart.sh
Issue https://github.com/longhorn/longhorn/issues/8499
support rancher prime
=> ci: support rancher prime

pipelines/utilities/run_longhorn_e2e_test.sh
Issue N/A
fix backup target not set in robot test cases
=> test(robot): fix backup target not set in robot test cases

manager/integration/tests/test_ha.py
Issue https://github.com/longhorn/longhorn/issues/8562
fix flaky test case test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume
=> test: fix flaky test case test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume

manager/integration/tests/test_recurring_job.py, manager/integration/tests/test_scheduling.py
Issue https://github.com/longhorn/longhorn/issues/8521
add debug message when assertion failed
=> test: add debug message when assertion failed

docs/content/manual/release-specific/v1.2.0/backup-creation-with-old-engine-image.md
Issue longhorn/longhorn#8580
Update manual test case Test Backup Creation With Old Engine Image
=> test(manual) update Test Backup Creation With Old Engine Image

manager/integration/tests/test_csi_snapshotter.py
Issue https://github.com/longhorn/longhorn/issues/8620
test csi snapshot of type=bak (aka Longhorn backup) when volume is detached
=> test: test csi snapshot of type=bak (aka Longhorn backup) when volume is detached

.github/workflows/build.yml, build-image.sh
https://github.com/longhorn/longhorn/issues/8039
Run `make` without error.
=> fix: local make build

manager/integration/Dockerfile
Original CI error: https://github.com/longhorn/longhorn-tests/actions/runs/9315512758/job/25641815189
This PR CI result: https://github.com/longhorn/longhorn-tests/actions/runs/9396482830/job/25877751459?pr=1932
=> ci: fix docker build error

manager/integration/tests/common.py, manager/integration/tests/test_basic.py
Issue longhorn/longhorn#8668
Issue longhorn/longhorn#6561
1. After https://github.com/longhorn/longhorn-manager/pull/2845 is merged, we need to update the related test cases.
2. Update the test case to verify the `toomanysnapshots` expected message.
=> Update Case test_volume_toomanysnapshots_condition

docs/content/manual/release-specific/v1.7.0/test-build-image-package-up-to-date.md
Issue longhorn/longhorn#8721
Proposing a manual test case to verify system packages are up-to-date during the image-building process for Longhorn components.
`None`
`None`
=> Test(manual): system packages are up-to-date during image build

e2e/keywords/common.resource, e2e/keywords/node.resource, e2e/keywords/volume.resource, e2e/libs/keywords/node_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/node/node.py, e2e/libs/utility/constant.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/tests/test_cases/replica_rebuilding.robot
Issue  longhorn/longhorn#8731
Move [Replica Rebuilding](https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/replica-rebuilding/) to robot test case
https://github.com/longhorn/longhorn/issues/7211
=> test(robot): add replica rebuilding test

e2e/deploy/test.yaml, e2e/libs/backing_image/rest.py, e2e/libs/backup/rest.py, e2e/libs/backupstore/base.py, e2e/libs/backupstore/nfs.py, e2e/libs/backupstore/s3.py, e2e/libs/node/node.py, e2e/libs/recurringjob/rest.py, e2e/libs/replica/rest.py, e2e/libs/setting/setting.py, e2e/libs/utility/utility.py, e2e/libs/volume/rest.py, pipelines/e2e/scripts/longhorn-setup.sh, pipelines/utilities/run_longhorn_e2e_test.sh
setup nfs backupstore and run test as a pod
=> test(robot): setup nfs backupstore and run test as a pod

test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_rke.sh, test_framework/terraform/aws/oracle/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_rke.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/sle-micro/k3s_instaces.tf, test_framework/terraform/aws/sle-micro/rke2_instances.tf, test_framework/terraform/aws/sle-micro/rke_instances.tf, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/sles/user-data-scripts/provision_rke.sh, test_framework/terraform/aws/sles/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke.sh, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_agent.sh.tpl
Issue https://github.com/longhorn/longhorn/issues/8688
install cryptsetup for volume encryption test
=> ci: install cryptsetup for volume encryption test

docs/content/manual/pre-release/node-not-ready/node-restart/physical-node-reboot.md
longhorn/longhorn-8567
Issue https://github.com/longhorn/longhorn/issues/8567
In v1.6.2 and master, reboot workload volume node, the workload not 100% attached to the origin node after the rebooted node ready.
Update test case for only check volume healthy and data correct.
=> test(manual): update Physical node reboot

e2e/keywords/network.resource, e2e/keywords/volume.resource, e2e/libs/keywords/network_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/network/network.py, e2e/libs/node/node.py, e2e/tests/test_cases/node_disconnection_test.robot
Issue longhorn/longhorn#8617
Implement manual test case [Node disconnection test](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-disconnection/node-disconnection/)
Manual test case update here https://github.com/longhorn/longhorn-tests/pull/1933
=> test(robot): Node disconnection test

e2e/tests/test_cases/single_replica_node_down.robot
Issue https://github.com/longhorn/longhorn/issues/8350
Remove the unavailable manul test case link (since https://github.com/longhorn/longhorn-tests/pull/1913)
=> test(robot): update single_replica_node_down.robot

manager/integration/tests/test_ha.py
Issue longhorn/longhorn#8871
Adjust the test case following the changes in https://github.com/longhorn/longhorn-manager/pull/2918. We implemented a precheck before creating a new Replica CR, so no new Replica will be created is no suitable node and disk are available.
`None`
`None`
=> fix(integration): test_extra_replica_cleanup

manager/integration/tests/common.py, manager/integration/tests/test_migration.py
Issue longhorn/longhorn#8873
See https://github.com/longhorn/longhorn/issues/8873#issuecomment-2205066596.
`None`
`None`
=> fix(integration): test_migration_with_unscheduled_replica

manager/integration/tests/test_node.py
Issue longhorn/longhorn#8872
Adjust the test case following the changes in https://github.com/longhorn/longhorn-manager/pull/2918. 
`None`
`None`
=> fix(integration): test_node_eviction_no_schedulable_node

manager/integration/tests/test_snapshot.py
=> Add a test skeleton for filesystem freeze functionality

manager/integration/tests/test_ha.py
Issue longhorn/longhorn#8870
Adjust the test case following the changes in https://github.com/longhorn/longhorn-manager/pull/2918.
`None`
`None`
=> fix(integration): test_replica_failure_during_attaching

manager/integration/tests/test_scheduling.py
Issue longhorn/longhorn#8867
Adjust the test case following the changes in https://github.com/longhorn/longhorn-manager/pull/2918.
`None`
`None`
=> fix(integration): test_scheduling.py

manager/integration/tests/common.py, manager/integration/tests/test_ha.py
Issue https://github.com/longhorn/longhorn/issues/8878
specify which container to execute the command in pod exec
=> test: specify which container to execute the command in pod exec

manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn/issues/8888
refine scheduling related test cases
=> test: refine scheduling related test cases

e2e/Dockerfile, manager/integration/Dockerfile
=> build: update java version

manager/integration/tests/test_ha.py
Issue longhorn/longhorn#8891
Adjust the test case following the changes in https://github.com/longhorn/longhorn-manager/pull/2918.
`None`
`None`
=> fix(integration): test_reuse_failed_replica

manager/integration/tests/test_basic.py
Issue longhorn/longhorn#8893
Adjust the test case following the changes in https://github.com/longhorn/longhorn-manager/pull/2918.
`None`
`None`
=> fix(integration): test_allow_volume_creation_with_degraded_availability_restore

manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn-tests/pull/1941
Fix flaky test case test_backuptarget_invalid.
It may take more than 30 seconds to transition from `Pending` state to `Error` state.
=> test: fix flaky test case test_backuptarget_invalid

docs/content/manual/release-specific/v1.7.0/test-node-disk-support.md
longhorn/longhorn#7672
Add manual test cases to perform functional testing of node disk support.
@derekbit
=> test(manual): add test node disk support

e2e/libs/volume/rest.py
Issue N/A
fix no attribute longhorn_client error in Replica Rebuilding test case
=> test(robot): fix no attribute longhorn_client error in Replica Rebuilding test case

e2e/libs/node/node.py
Issue N/A
wait for disk updated when adding disks
=> test(robot): wait for disk updated when adding disks

pipelines/e2e/Jenkinsfile, pipelines/e2e/scripts/longhorn-setup.sh, pipelines/utilities/run_longhorn_e2e_test.sh
Issue N/A
make cluster restart test case be able to run out of cluster
=> test(robot): make cluster restart test case be able to run out of cluster

e2e/libs/volume/crd.py, e2e/tests/test_cases/single_replica_node_down.robot
Issue N/A
fix flaky test case single replica node down and refine logging
=> test(robot): fix flaky test case single replica node down and refine logging

manager/integration/tests/common.py, manager/integration/tests/test_scheduling.py
Issue longhorn/longhorn#7840
Implement test for replica auto balance pressured disk
`None`
longhorn/longhorn#4105
=> test(integration): replica auto balance disk in pressure

manager/integration/tests/common.py, manager/integration/tests/test_backing_image.py, manager/integration/tests/test_csi_snapshotter.py, manager/integration/tests/test_ha.py
ref: https://github.com/longhorn/longhorn/issues/2856
Add e2e tests for backing image enhancement
- HA
- selector
- eviction
=> feat(backingimage): add backing image ha, eviction and selector testing

docs/content/manual/pre-release/v2-volume/sanity-check.md
Issue N/A
update v2 sanity check
=> test(manual): update v2 sanity check

e2e/keywords/common.resource, e2e/keywords/volume.resource, e2e/libs/keywords/volume_keywords.py, e2e/libs/volume/crd.py, e2e/tests/node_reboot.robot, e2e/tests/regression/test_backing_image.robot, e2e/tests/regression/test_backup.robot, e2e/tests/regression/test_basic.robot, e2e/tests/regression/test_migration.robot, e2e/tests/regression/test_settings.robot, e2e/tests/replica_rebuilding.robot, e2e/tests/stress_cpu.robot, e2e/tests/stress_filesystem.robot, e2e/tests/stress_memory.robot, e2e/tests/test_cases/node_disconnection_test.robot, e2e/tests/test_cases/replica_rebuilding.robot
Issue N/A
extend regression test cases to v2 volume
=> test(robot): extend regression test cases to v2 volume

e2e/libs/backing_image/rest.py
Issue N/A
fix backing image test case by passing minNumberOfCopies=1
=> test(robot): fix backing image test case by passing minNumberOfCopies=1

e2e/libs/engine/engine.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/persistentvolumeclaim/crd.py, e2e/libs/persistentvolumeclaim/persistentvolumeclaim.py, e2e/libs/workload/deployment.py, e2e/libs/workload/workload.py, e2e/tests/stress_cpu.robot, e2e/tests/stress_filesystem.robot, e2e/tests/stress_memory.robot
Issue N/A
fix missing claim_namespace and expand pvc error
=> test(robot): fix missing claim_namespace and expand pvc error

e2e/keywords/longhorn.resource, e2e/keywords/workload.resource, e2e/tests/test_cases/node_disconnection_test.robot
Issue N/A
refine Node disconnection test by removing the volume unknown state check as the code cannot reliably catch the transient state.
=> test(robot): refine Node disconnection test

e2e/libs/workload/workload.py
Issue N/A
ensure pod is running before executing commands
=> test(robot): ensure pod is running before executing commands

test_framework/terraform/aws/oracle/variables.tf, test_framework/terraform/aws/rhel/variables.tf, test_framework/terraform/aws/rockylinux/variables.tf, test_framework/terraform/aws/sle-micro/variables.tf, test_framework/terraform/aws/sles/variables.tf, test_framework/terraform/aws/ubuntu/variables.tf
Issue N/A
increase disk size to prevent running out of space during long-running tests
=> test(robot): increase disk size to prevent running out of space during long-running tests

manager/integration/tests/test_csi.py
longhorn/longhorn#9035
https://github.com/longhorn/longhorn/issues/9035#issuecomment-2237341792
I'm not sure about this one yet, as I've had no opportunity to observe a cluster's right right after a failure. However, if my hunch is correct, the slightly modified test will pass 50/50 times.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7268/
=> fix: flake in test_allow_volume_creation_with_degraded_availability_csi

docs/content/manual/pre-release/ha/ha-volume-migration.md
=> docs: clarify old engine node down case for HA migration

test_framework/terraform/azure/aks/main.tf
Issue https://github.com/longhorn/longhorn/issues/9024
use larger azure instance type
=> ci: use larger azure instance type

manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn/issues/9035
fix flaky test case test_allow_volume_creation_with_degraded_availability
=> test: fix flaky test case test_allow_volume_creation_with_degraded_availability

test_framework/Jenkinsfile, test_framework/scripts/longhorn-setup.sh
Issue https://github.com/longhorn/longhorn/issues/9001
avoid generating go-cover in sle-micro read-only file system
=> ci: avoid generating go-cover in sle-micro read-only file system

manager/integration/tests/test_rwx.py
Issue https://github.com/longhorn/longhorn/issues/6205
refine test_rwx_delete_share_manager_pod for share manager HA
=> test: refine test_rwx_delete_share_manager_pod for share manager HA

manager/integration/tests/common.py
Issue N/A
skip deleting preinstalled storage classes in aks
=> test: skip deleting preinstalled storage classes in aks

e2e/tests/cluster_restart.robot, e2e/tests/kubelet_restart.robot, e2e/tests/node_reboot.robot
Issue https://github.com/longhorn/longhorn/issues/6205
extend negative test cases to test rwx volume fast failover
=> test(robot): extend negative test cases to test rwx volume fast failover

test_framework/terraform/aws/sle-micro/k3s_instaces.tf, test_framework/terraform/aws/sle-micro/main.tf, test_framework/terraform/aws/sle-micro/rke2_instances.tf, test_framework/terraform/aws/sle-micro/variables.tf
Issue https://github.com/longhorn/longhorn/issues/9001
workaround for sle-micro not rebooting via ssh
=> ci: workaround for sle-micro not rebooting via ssh

pipelines/storage_network/terraform/user-data-scripts/provision_k3s_agent.sh.tpl
Issue N/A
install cryptsetup in storage network pipeline terraform script
=> ci: install cryptsetup in storage network pipeline terraform script

manager/integration/tests/common.py, manager/integration/tests/test_recurring_job.py
Issue N/A
fix flaky test case test_recurring_job_source_label by adding retry mechanism
https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/12/testReport/tests/test_recurring_job/test_recurring_job_source_label/
=> test: fix flaky test case test_recurring_job_source_label

test_framework/scripts/longhorn-setup.sh
Issue N/A
prevent longhornctl from running on sle-micro
=> ci: prevent longhornctl from running on sle-micro

e2e/libs/keywords/storageclass_keywords.py, e2e/libs/storageclass/storageclass.py, e2e/tests/test_cases/node_disconnection_test.robot, e2e/tests/test_cases/physical_node_reboot.robot, e2e/tests/test_cases/replica_rebuilding.robot, e2e/tests/test_cases/single_replica_node_down.robot
Issue N/A
extend manual test cases to include v2 data engine
=> test(robot): extend manual test cases to include v2 data engine

e2e/tests/node_reboot.robot
Issue N/A
add tag to recurring job test cases for differentiation
=> test(robot): add tag to recurring job test cases for differentiation

test_framework/terraform/aws/sle-micro/k3s_instaces.tf
Issue N/A
install cryptsetup on sle-micro worker nodes
=> ci: install cryptsetup on sle-micro worker nodes

manager/integration/tests/test_ha.py
Issue https://github.com/longhorn/longhorn/issues/9145
fix flaky test case test_rebuild_with_inc_restoration
=> test: fix flaky test case test_rebuild_with_inc_restoration

manager/integration/tests/test_basic.py, manager/integration/tests/test_ha.py
Issue https://github.com/longhorn/longhorn/issues/9161
fix flaky test cases on rockylinux arm64
=> test: fix flaky test cases on rockylinux arm64

test_framework/terraform/aws/sle-micro/k3s_instaces.tf, test_framework/terraform/aws/sle-micro/rke2_instances.tf, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_rke2_agent.sh.tpl
Issue https://github.com/longhorn/longhorn/issues/9135
manually load dm_crypt module on sle-micro
=> ci: manually load dm_crypt module on sle-micro

docs/content/manual/pre-release/v2-volume/sanity-check.md
longhorn/longhorn#9192
Updates the v2 volume sanity check case for Longhorn v1.7.0 and later.
@derekbit 
https://github.com/longhorn/longhorn/issues/8642#issue-2316443071
https://github.com/longhorn/longhorn/issues/8813
https://github.com/longhorn/longhorn/issues/9126
=> test(manual): Update v2 volume sanity check case

e2e/Dockerfile, manager/integration/Dockerfile
=> ci: update java version

pipelines/gke/terraform/main.tf
Issue N/A
using larger instances in gke to prevent test pod crashes
=> ci: using larger instances in gke to prevent test pod crashes

e2e/keywords/network.resource, e2e/libs/keywords/network_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/network/network.py, e2e/libs/volume/crd.py, e2e/libs/workload/workload.py, e2e/tests/cluster_restart.robot, e2e/tests/kubelet_restart.robot, e2e/tests/network_disconnect.robot, e2e/tests/node_delete.robot, e2e/tests/node_drain.robot, e2e/tests/node_reboot.robot, e2e/tests/replica_rebuilding.robot, e2e/tests/stress_cpu.robot, e2e/tests/stress_filesystem.robot, e2e/tests/stress_memory.robot
Issue N/A
extend negative test cases to include v2 data engine
=> test(robot): extend negative test cases to include v2 data engine

pipelines/gke/Jenkinsfile, pipelines/gke/scripts/longhorn-setup.sh, pipelines/gke/terraform/main.tf, pipelines/gke/terraform/variables.tf
Issue https://github.com/longhorn/longhorn/issues/8195
add an option to support gke COS_CONTAINERD
=> ci: add an option to support gke COS_CONTAINERD

test_framework/terraform/aws/oracle/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/oracle/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rhel/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/rockylinux/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/sle-micro/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/sles/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/aws/ubuntu/user-data-scripts/provision_rke2_agent.sh.tpl, test_framework/terraform/equinix/ubuntu/user-data-scripts/provision_k3s_agent.sh.tpl, test_framework/terraform/equinix/ubuntu/user-data-scripts/provision_rke2_agent.sh.tpl
Issue https://github.com/longhorn/longhorn/issues/8813
enable both uio_pci_generic and vfio_pci
=> ci: enable both uio_pci_generic and vfio_pci

e2e/libs/node/node.py
Issue N/A
wait for block disks ready and schedulable
=> test(robot): wait for block disks ready and schedulable

pipelines/e2e/Jenkinsfile
Issue https://github.com/longhorn/longhorn/issues/7307
add custom ssh public key option to longhorn-e2e-test to allow team members to access test cluster
=> ci: add custom ssh public key option to longhorn-e2e-test to allow team members to access test cluster

pipelines/e2e/Dockerfile.setup, pipelines/e2e/Jenkinsfile, pipelines/utilities/junit_to_qase.py, test_framework/Dockerfile.setup, test_framework/Jenkinsfile
Issue https://github.com/longhorn/longhorn/issues/8853 https://github.com/longhorn/longhorn/issues/7412
sync automated test cases between github and qase and post test run for daily regression
=> ci: sync automated test cases between github and qase and post test run for daily regression

e2e/keywords/common.resource
Issue N/A
fix missing import of engine_image_keywords.py
=> test(robot): fix missing import of engine_image_keywords.py

test_framework/scripts/longhorn-setup.sh
Issue https://github.com/longhorn/longhorn/issues/8855
fix missing longhorn-system namespace during iscsi installation
=> ci: fix missing longhorn-system namespace during iscsi installation

test_framework/terraform/aws/talos/main.tf, test_framework/terraform/aws/talos/talos-patch-worker.yaml, test_framework/terraform/aws/talos/talos-patch.yaml, test_framework/terraform/aws/talos/variables.tf
Issue https://github.com/longhorn/longhorn/issues/7791
talos support for v2 data engine
=> ci: talos support for v2 data engine

pipelines/e2e/Jenkinsfile, pipelines/utilities/junit_to_qase.py, test_framework/Jenkinsfile
Issue https://github.com/longhorn/longhorn/issues/8853
add ci build link in the qase test run description
=> ci: add ci build link in the qase test run description

test_framework/scripts/longhorn-setup.sh, test_framework/scripts/terraform-setup.sh
Issue N/A
expose longhorn frontend for debugging
=> ci: expose longhorn frontend for debugging

e2e/libs/volume/crd.py, e2e/libs/volume/rest.py
longhorn/longhorn-9422
Issue longhorn/longhorn#9422
See https://github.com/longhorn/longhorn/issues/9422#issuecomment-2345137231
`None`
`None`
=> fix(robot): remove rootfs from device endpoint

manager/integration/tests/test_upgrade.py
Issue https://github.com/longhorn/longhorn/issues/9398
add strict-local volume upgrade engine image test
=> test: add strict-local volume upgrade engine image test

e2e/README.md, e2e/deploy/test.yaml, pipelines/utilities/run_longhorn_e2e_test.sh
Issue https://github.com/longhorn/longhorn/issues/9521
update robot test README.md and test.yaml
=> ci(robot): update robot test README.md and test.yaml

e2e/keywords/common.resource, e2e/libs/backup/rest.py, e2e/libs/keywords/common_keywords.py, e2e/libs/network/network.py, e2e/libs/node_exec/node_exec.py, e2e/libs/snapshot/rest.py, e2e/libs/utility/utility.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/tests/regression/test_basic.robot
Issue https://github.com/longhorn/longhorn/issues/9513
fix node_exec rootfs mount point missing after node reboot
=> test(robot): fix node_exec rootfs mount point missing after node reboot

test_framework/scripts/longhorn-setup.sh
=> fix: use forked csi-snapshotter repo instead

e2e/keywords/common.resource, e2e/keywords/host.resource
Issue N/A
fix No keyword with name 'Power on off node' error
=> test(robot): fix No keyword with name 'Power on off node' error

e2e/libs/utility/utility.py, e2e/libs/workload/pod.py
Issue N/A
force delete pod to prevent it from getting stuck
=> test(robot): force delete pod to prevent it from getting stuck

e2e/tests/regression/test_ha.robot
=> test(robot): skip test skeleton

e2e/keywords/backup.resource, e2e/keywords/common.resource, e2e/keywords/snapshot.resource, e2e/keywords/volume.resource, e2e/keywords/workload.resource, e2e/libs/backup/backup.py, e2e/libs/backup/base.py, e2e/libs/backup/rest.py, e2e/libs/keywords/backup_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/libs/workload/workload.py, e2e/tests/negative/test_backup_listing.robot
longhorn/longhorn#8355
Implement manual test case [Test backup listing S3/NFS](https://longhorn.github.io/longhorn-tests/manual/pre-release/stress/backup-listing/) in robot.
- https://longhorn.github.io/longhorn-tests/manual/pre-release/stress/backup-listing/
- https://github.com/longhorn/longhorn/issues/8355
- PR test log : 
- ~~[log_20240617_case2.tar.gz](https://github.com/user-attachments/files/15860633/log_20240617_case2.tar.gz)~~
- ~~[log_20240823.tar.gz](https://github.com/user-attachments/files/16720876/log_20240823.tar.gz)~~
- [log_20240926.tar.gz](https://github.com/user-attachments/files/17143932/log_20240926.tar.gz)
- Here's how to execute test case: ` ./run.sh -t "Backup listing of volume bigger than 200 Gi" -v RETRY_COUNT:5400
`
=> test(robot): add test backup listing for large volumes and many backups

e2e/libs/backup/rest.py, manager/integration/tests/backupstore.py
Issue # longhorn/longhorn#10144
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8153/
Run passed for 138 times
=> fix: use the same method when cleaning up backup volumes

e2e/libs/workload/workload.py
Issue longhorn/longhorn#9248
https://github.com/longhorn/longhorn/issues/9248#issuecomment-2752788292
`None`
`None`
=> fix(robot): retry command errors in write_pod_random_data

e2e/Dockerfile, e2e/libs/longhorn_deploy/longhorn_deploy.py, e2e/libs/longhorn_deploy/longhorn_rancher_chart.py, pipelines/rancher/Jenkinsfile, pipelines/rancher/scripts/longhorn-setup.sh, pipelines/utilities/longhorn_rancher_chart.sh, pipelines/utilities/run_longhorn_e2e_test.sh
Issue https://github.com/longhorn/longhorn/issues/10674
implement install/upgrade/uninstall by rancher and support running robot test on rancher chart pipeline
=> test(robot): implement install/upgrade/uninstall by rancher and support running robot test on rancher chart pipeline

e2e/Dockerfile, e2e/libs/longhorn_deploy/longhorn_deploy.py, e2e/libs/longhorn_deploy/longhorn_flux.py, pipelines/flux/Jenkinsfile, pipelines/flux/scripts/longhorn-setup.sh, pipelines/utilities/flux.sh
Issue https://github.com/longhorn/longhorn/issues/10687
implement install/upgrade/uninstall by flux and support running robot test on flux pipeline
=> test(robot): implement install/upgrade/uninstall by flux and support running robot test on flux pipeline

e2e/libs/longhorn_deploy/longhorn_deploy.py, e2e/libs/longhorn_deploy/longhorn_fleet.py, pipelines/fleet/Jenkinsfile, pipelines/fleet/scripts/longhorn-setup.sh, pipelines/utilities/fleet.sh, pipelines/utilities/longhorn_manifest.sh
Issue https://github.com/longhorn/longhorn/issues/10693
implement install/upgrade/uninstall by fleet and support running robot test on fleet pipeline
=> test(robot): implement install/upgrade/uninstall by fleet and support running robot test on fleet pipeline

e2e/Dockerfile, e2e/libs/longhorn_deploy/longhorn_argocd.py, e2e/libs/longhorn_deploy/longhorn_deploy.py, pipelines/argocd/Jenkinsfile, pipelines/argocd/scripts/longhorn-setup.sh, pipelines/utilities/argocd.sh
Issue https://github.com/longhorn/longhorn/issues/10702
implement install/upgrade/uninstall by argocd and support running robot test on argocd pipeline
=> test(robot): implement install/upgrade/uninstall by argocd and support running robot test on argocd pipeline

e2e/keywords/recurringjob.resource, e2e/libs/keywords/recurringjob_keywords.py, e2e/libs/recurringjob/crd.py, e2e/libs/recurringjob/recurringjob.py, e2e/libs/recurringjob/rest.py, e2e/tests/regression/test_recurringjob.robot
Issue https://github.com/longhorn/longhorn/issues/10778
fix Test System Backup Recurring Job test cases
=> test(robot): fix Test System Backup Recurring Job test cases

manager/integration/tests/common.py
Issue N/A
fix misleading support bundle compatibility logic
=> test: fix misleading support bundle compatibility logic

manager/integration/tests/test_node.py
Issue https://github.com/longhorn/longhorn/issues/10801
fix flaky test case test_drain_with_block_for_eviction_success
=> test: fix flaky test case test_drain_with_block_for_eviction_success

e2e/keywords/longhorn.resource, e2e/keywords/orphan.resource, e2e/keywords/support_bundle.resource, e2e/keywords/system_backup.resource, e2e/keywords/variables.resource, e2e/keywords/volume.resource, e2e/keywords/workload.resource, e2e/libs/backing_image/rest.py, e2e/libs/instancemanager/instancemanager.py, e2e/libs/keywords/instancemanager_keywords.py, e2e/libs/keywords/orphan_keywords.py, e2e/libs/keywords/support_bundle_keywords.py, e2e/libs/keywords/system_backup_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/keywords/workload_keywords.py, e2e/libs/longhorn_deploy/longhorn_deploy.py, e2e/libs/longhorn_deploy/longhorn_kubectl.py, e2e/libs/orphan/__init__.py, e2e/libs/orphan/orphan.py, e2e/libs/support_bundle/support_bundle.py, e2e/libs/system_backup/rest.py, e2e/libs/system_backup/system_backup.py, e2e/libs/utility/utility.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/libs/workload/pod.py, e2e/libs/workload/workload.py, e2e/tests/prerelease_checks.robot, pipelines/utilities/longhorn_manifest.sh
Issue https://github.com/longhorn/longhorn/issues/10708
migrate test_upgrade test case
=> test(robot): migrate test_upgrade test case

manager/integration/tests/test_node.py
Issue https://github.com/longhorn/longhorn/issues/10804
fix test case drain node failure
=> test: fix test case drain node failure

e2e/keywords/deployment.resource, e2e/libs/volume/rest.py, e2e/tests/negative/replica_rebuilding.robot, e2e/tests/negative/test_backup_listing.robot, e2e/tests/regression/test_replica.robot
Issue # longhorn/longhorn#8443
=> test(robot): add a workload test case for offline rebuilding

pipelines/gke/terraform/main.tf
Update gke to 1.32.2-gke.1182003 which is the current default version
=> ci: update gke to 1.32.2-gke.1182003

test_framework/terraform/harvester/sle-micro/main.tf, test_framework/terraform/harvester/sles/main.tf
Issue N/A
fix longhornctl failed to check moduels on nodes scheduled for reboot
=> ci(robot): fix longhornctl failed to check moduels on nodes scheduled for reboot

pipelines/utilities/longhorn_helm_chart.sh
Issue https://github.com/longhorn/longhorn/issues/10815
fix test options parsing error in helm chart pipeline
=> test(robot): fix test options parsing error in helm chart pipeline

e2e/tests/negative/node_down.robot, e2e/tests/negative/test_restore_volume_node_reboot.robot
Issue N/A
fix unable to run individual test case in node_down and test_restore_volume_node_reboot test suites
=> test(robot): fix unable to run individual test case in node_down and test_restore_volume_node_reboot test suites

e2e/libs/keywords/volume_keywords.py, e2e/libs/volume/rest.py
Issue https://github.com/longhorn/longhorn/issues/10708
fix engine image upgrade in prerelease checks test case
=> test(robot): fix engine image upgrade in prerelease checks test case

manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn/issues/10879
fix flaky test case test_backup_failed_enable_auto_cleanup
=> test: fix flaky test case test_backup_failed_enable_auto_cleanup

manager/integration/tests/backupstore.py
Issue longhorn/longhorn#10852
https://github.com/longhorn/longhorn/issues/10852#issuecomment-2864879701
`None`
`None`
=> fix(pytest): NFS backupstore not working on Talos v1.9.x

e2e/keywords/common.resource, e2e/libs/backupstore/base.py, e2e/libs/keywords/host_keywords.py, e2e/libs/setting/setting.py, e2e/libs/utility/constant.py, e2e/libs/utility/utility.py
Issue N/A
add default cloud provider and backupstore to simplify local run workflow
=> test(robot): add default cloud provider and backupstore to simplify local run workflow

e2e/libs/host/vagrant.py
Issue https://github.com/longhorn/longhorn/issues/6708 https://github.com/longhorn/longhorn/issues/6741
refine vagrant node reboot function logging
=> test(robot): refine vagrant node reboot function logging

e2e/libs/backing_image/backing_image.py, e2e/libs/backing_image/rest.py
Issue https://github.com/longhorn/longhorn/issues/10916
fix test case Test Longhorn Backing Image Volume Recovery doesn't clean up backing images
=> test(robot): fix test case Test Longhorn Backing Image Volume Recovery doesn't clean up backing images

manager/integration/tests/test_scheduling.py
Issue https://github.com/longhorn/longhorn/issues/10898#issuecomment-2896934181
fix flaky test case test_replica_auto_balance_disk_in_pressure
=> test: fix flaky test case test_replica_auto_balance_disk_in_pressure

e2e/libs/backup/backup.py, e2e/libs/keywords/backup_keywords.py
Issue https://github.com/longhorn/longhorn/issues/10960
fix flaky test case Sync Up With Backup Target During DR Volume Activation
=> test(robot): fix flaky test case Sync Up With Backup Target During DR Volume Activation

e2e/keywords/common.resource
Issue https://github.com/longhorn/longhorn/issues/10811
add orphan cleanup in test case teardown function
=> test(robot): add orphan cleanup in test case teardown function

e2e/tests/negative/component_resilience.robot
Issue https://github.com/longhorn/longhorn/issues/10973
fix flaky test case Test Longhorn Dynamic Provisioned RWO/RWX Volume Recovery
=> test(robot): fix flaky test case Test Longhorn Dynamic Provisioned RWO/RWX Volume Recovery

e2e/keywords/common.resource, e2e/keywords/host.resource, e2e/keywords/volume.resource, e2e/libs/host/aws.py, e2e/libs/host/base.py, e2e/libs/host/harvester.py, e2e/libs/host/vagrant.py, e2e/libs/keywords/host_keywords.py, e2e/tests/negative/vm_snapshot.robot, e2e/tests/regression/test_scheduling.robot
Issue https://github.com/longhorn/longhorn/issues/10918
implement negative factor vm snapshot for aws
=> test(robot): implement negative factor vm snapshot for aws

e2e/keywords/volume.resource
Issue https://github.com/longhorn/longhorn/issues/10977
be able to preserve the env when test case Test Replica Auto Balance Node Least Effort fails
=> test(robot): be able to preserve the env when test case Test Replica Auto Balance Node Least Effort fails

e2e/keywords/common.resource, e2e/keywords/longhorn.resource, e2e/keywords/node.resource, e2e/keywords/volume.resource, e2e/libs/instancemanager/instancemanager.py, e2e/libs/keywords/instancemanager_keywords.py, e2e/libs/keywords/node_keywords.py, e2e/libs/node/node.py, e2e/tests/negative/ha_volume_migration.robot, e2e/tests/negative/node_drain.robot, e2e/tests/regression/test_v2.robot
Issue https://github.com/longhorn/longhorn/issues/7016
add selective v2 data engine activation test cases
=> test(robot): add selective v2 data engine activation test cases

e2e/keywords/common.resource, e2e/keywords/host.resource, e2e/keywords/k8s.resource, e2e/keywords/volume.resource, e2e/libs/k8s/k8s.py, e2e/libs/keywords/host_keywords.py, e2e/libs/keywords/k8s_keywords.py, e2e/libs/keywords/volume_keywords.py, e2e/libs/volume/crd.py, e2e/libs/volume/volume.py, e2e/tests/negative/vm_snapshot.robot, e2e/tests/regression/test_scheduling.robot, e2e/tests/regression/test_zone.robot
Issue https://github.com/longhorn/longhorn/issues/10938
migrate test_replica_zone_anti_affinity
=> test(robot): migrate test_replica_zone_anti_affinity

docs/content/manual/release-specific/v1.9.0/test-orphaned-instance.md, e2e/tests/regression/test_orphan.robot
Issue longhorn/longhorn#6764
Test cases for orphaned runtime instance cleanup.
LEP: https://github.com/longhorn/longhorn/pull/10675
=> test: add tests for orphaned resource handling

pipelines/utilities/terraform_setup.sh, test_framework/terraform/aws/sles/output.tf
Issue longhorn/longhorn#11049
`Test Volume Basic` pased on [k3s](https://10.115.5.5/job/private/job/longhorn-e2e-test/14/) and [rke2](https://10.115.5.5/job/private/job/longhorn-e2e-test/13/)
=> test: add instance mapping when create rke2 cluster

e2e/keywords/recurringjob.resource, e2e/libs/keywords/recurringjob_keywords.py, e2e/libs/recurringjob/crd.py, e2e/libs/recurringjob/recurringjob.py, e2e/libs/recurringjob/rest.py, e2e/tests/regression/test_recurringjob.robot
Issue longhorn/longhorn#11016, longhorn/longhorn#11071
Implement a new case to cover https://github.com/longhorn/longhorn/issues/11016.
`None`
`None`
=> test(robot): recurring job pod should not crash

docs/content/manual/pre-release/node-not-ready/kubelet-restart/kubelet-restart-on-a-node.md, e2e/README.md, e2e/libs/k8s/k8s.py, e2e/tests/negative/kubelet_restart.robot, pipelines/utilities/run_longhorn_e2e_test.sh
Issue longhorn/longhorn#10765
I have also updated manual test case to match current Longhorn behavior
Test result
- [k3s](https://10.115.5.5/job/private/job/longhorn-e2e-test/11/) 
- [rke2](https://10.115.5.5/job/private/job/longhorn-e2e-test/12/)
=> test(robot): automate manual test case Test kubelet restart on a node of the cluster

e2e/keywords/common.resource, e2e/keywords/workload.resource, e2e/libs/keywords/workload_keywords.py, e2e/libs/workload/workload.py, e2e/templates/workload/deployment.yaml, e2e/templates/workload/statefulset.yaml, e2e/tests/regression/test_basic.robot
Issue https://github.com/longhorn/longhorn/issues/10991 https://github.com/longhorn/longhorn/issues/10624
use a non-root user to test a workload and add file ownership and permission test case
=> test(robot): use a non-root user to test a workload and add file ownership and permission test case

e2e/keywords/replica.resource, e2e/keywords/volume.resource, e2e/libs/keywords/volume_keywords.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/tests/regression/test_replica.robot, e2e/tests/regression/test_scheduling.robot, e2e/tests/regression/test_tagging.robot, e2e/tests/regression/test_v2.robot
Issue https://github.com/longhorn/longhorn/issues/10936
migrate case 2,3,4 of test_data_locality_basic
=> test(robot): migrate case 2,3,4 of test_data_locality_basic

e2e/libs/host/aws.py, e2e/libs/host/harvester.py
Issue https://github.com/longhorn/longhorn/issues/10918
implement vm snapshot on hal
=> test(robot): implement vm snapshot on hal

e2e/libs/host/vagrant.py
Issue https://github.com/longhorn/longhorn/issues/10918
implement vm snapshot on vagrant
=> test(robot): implement vm snapshot on vagrant

e2e/README.md, e2e/keywords/longhorn.resource, e2e/libs/instancemanager/instancemanager.py, e2e/libs/keywords/instancemanager_keywords.py, e2e/libs/keywords/longhorn_deploy_keywords.py, e2e/libs/longhorn_deploy/longhorn_argocd.py, e2e/libs/longhorn_deploy/longhorn_deploy.py, e2e/libs/longhorn_deploy/longhorn_fleet.py, e2e/libs/longhorn_deploy/longhorn_flux.py, e2e/libs/longhorn_deploy/longhorn_helm_chart.py, e2e/libs/longhorn_deploy/longhorn_kubectl.py, e2e/libs/longhorn_deploy/longhorn_rancher_chart.py, e2e/tests/negative/upgrade_with_new_instance_manager.robot, pipelines/utilities/longhorn_status.sh
longhorn/longhorn#11122
Automate manual test case [Test System Upgrade with New Instance Manager](https://longhorn.github.io/longhorn-tests/manual/pre-release/upgrade/upgrade-with-new-instance-manager/)
=> test(robot): Automate manual test case Test System Upgrade with New Instance Manager

e2e/keywords/common.resource, e2e/keywords/csi_volume_snapshot.resource, e2e/keywords/snapshot.resource, e2e/libs/csi_volume_snapshot/__init__.py, e2e/libs/csi_volume_snapshot/csi_volume_snapshot.py, e2e/libs/keywords/csi_volume_snapshot_keywords.py, e2e/libs/keywords/snapshot_keywords.py, e2e/libs/snapshot/rest.py, e2e/libs/snapshot/snapshot.py, e2e/templates/csi_volume_snapshot/volumesnapshot.yaml, e2e/templates/csi_volume_snapshot/volumesnapshotclass.yaml, e2e/tests/regression/test_csi_snapshotter.robot
Issue https://github.com/longhorn/longhorn/issues/10939
add csi volume snapshot associated with longhorn snapshot test case
=> test(robot): add csi volume snapshot associated with longhorn snapshot test case

manager/integration/tests/common.py, manager/integration/tests/test_cloning.py, manager/integration/tests/test_infra.py, manager/integration/tests/test_metric.py
Issue longhorn/longhorn#2259
Support single-stacked IPv4 and IPv6 environments.
`None`
`None`
=> test(pytest): support address family

e2e/tests/negative/node_reboot_with_different_anti_affinity.robot
=> fix: robot test node_reboot_with_different_anti_affinity should enable fast rebuilding for v2

build_engine_test_images/scripts/generate_images.sh
Issue https://github.com/longhorn/longhorn/issues/11207
fix build and publish engine test images errors
=> ci: fix build and publish engine test images errors

e2e/libs/csi_volume_snapshot/csi_volume_snapshot.py, e2e/libs/engine_image/engine_image.py
https://github.com/longhorn/longhorn/issues/11202
https://github.com/longhorn/longhorn/issues/10828
https://github.com/longhorn/longhorn/issues/11188
=> fix: e2e test resource cleanup should not fail the test itself

manager/integration/tests/test_settings.py
Issue https://github.com/longhorn/longhorn/issues/11200
refine test case test_instance_manager_cpu_reservation expected error message
=> test: refine test case test_instance_manager_cpu_reservation expected error message

pipelines/utilities/run_longhorn_test.sh
Issue N/A
fix test_offline_node stopping the wrong ec2 instance
=> test: fix test_offline_node stopping the wrong ec2 instance

manager/integration/tests/backupstore.py, manager/integration/tests/test_basic.py
Issue https://github.com/longhorn/longhorn/issues/10087
fix backup target default is not available error
=> test: fix backup target default is not available error

e2e/tests/regression/test_basic.robot
Issue N/A
fix flaky test case V1 Replica Rebuilding
=> test(robot): fix flaky test case V1 Replica Rebuilding

e2e/libs/workload/pod.py, e2e/tests/negative/ha_volume_migration.robot
Issue https://github.com/longhorn/longhorn/issues/10800
=> Fix pod deleteion func and add debug logs for robot tests

e2e/keywords/snapshot.resource, e2e/libs/keywords/snapshot_keywords.py, e2e/libs/snapshot/rest.py, e2e/libs/snapshot/snapshot.py, e2e/tests/negative/checksum_enabled_large_volume_with_multiple_rebuilding.robot, e2e/tests/regression/test_snapshot.robot
Issue N/A
fix flaky test case Compare Large Volume Rebuild Performance Before and After Enabling Snapshot Integrity
=> test(robot): fix flaky test case Compare Large Volume Rebuild Performance Before and After Enabling Snapshot Integrity

e2e/tests/negative/upgrade_with_new_default_storageclass.robot
Issue N/A
fix Test system upgrade with a new storage class being default on v2 volume
=> test(robot): fix Test system upgrade with a new storage class being default on v2 volume

e2e/libs/utility/utility.py
Issue N/A
passing correct namespace to wait_delete_pod function
=> test(robot): passing correct namespace to wait_delete_pod function

e2e/tests/negative/upgrade_conflict_handle.robot
Fix variable scope in test suite `upgrade_conflict_handle` for all the two test case use the same variable
=> test(robot): fix variable scope in test suite upgrade_conflict_handle

airgap/Dockerfile.setup, manager/integration/tests/test_upgrade.py, pipelines/appco/Dockerfile.setup, pipelines/appco/Jenkinsfile, pipelines/appco/scripts/fetch_image_list.sh, pipelines/appco/scripts/longhorn_helm_chart.sh, pipelines/appco/scripts/longhorn_manifest.sh, pipelines/appco/scripts/longhorn_setup.sh, pipelines/appco/scripts/prepare_airgap_appco_images.sh, pipelines/utilities/run_longhorn_test.sh, test_framework/terraform/harvester/sles/main.tf
Refine AppCo pipeline
Refine AppCo pipeline 
- airgap: using manifest
- nonarigep: using helm chart install
- reduce pipeline input field
Test version input field
Underlying logic
```bash
helm install longhorn oci://registry.suse.de/devel/tulip/charts/charts/suse-storage:1.9.0 \
-n longhorn-system \
--set image.longhorn.engine.registry=registry.suse.de/devel/tulip/containers \
--set image.longhorn.manager.registry=registry.suse.de/devel/tulip/containers \
--set image.longhorn.ui.registry=registry.suse.de/devel/tulip/containers \
--set image.longhorn.instanceManager.registry=registry.suse.de/devel/tulip/containers \
--set image.longhorn.shareManager.registry=registry.suse.de/devel/tulip/containers \
--set image.longhorn.backingImageManager.registry=registry.suse.de/devel/tulip/containers \ …
```
=> test(infra): refine appco pipeline

pipelines/appco/scripts/longhorn_helm_chart.sh, pipelines/utilities/run_longhorn_test.sh
https://github.com/rancher/suse-storage/issues/39
ci: helm login for dp.apps.rancher.io in upgrade test pod
Test [result](https://10.115.5.5/job/private/job/longhorn-appco-images-test/103/testReport/)
=> ci: helm login for dp.apps.rancher.io in upgrade test pod

pipelines/utilities/longhornctl.sh, test_framework/scripts/longhorn-setup.sh, test_framework/terraform/aws/eks/main.tf
Issue https://github.com/longhorn/longhorn/issues/10880
update eks ami type and enable longhornctl for amazon linux
=> ci: update eks ami type and enable longhornctl for amazon linux

e2e/libs/keywords/volume_keywords.py
Issue N/A
fix missing argument wait_volume_attached error in attach_volume_in_maintenance_mode
=> test(robot): fix missing argument wait_volume_attached error in attach_volume_in_maintenance_mode

manager/integration/tests/test_snapshot.py
Issue https://github.com/longhorn/longhorn/issues/11448
fix flaky test case test_snapshot_hash_global_enabled_without_immediate_hash
=> test: fix flaky test case test_snapshot_hash_global_enabled_without_immediate_hash

manager/integration/tests/common.py
Issue https://github.com/longhorn/longhorn/issues/11456
fix flaky test case test_backup_kubernetes_status
=> test: fix flaky test case test_backup_kubernetes_status

e2e/keywords/common.resource, e2e/tests/negative/upgrade_conflict_handle.robot, e2e/tests/regression/test_backing_image.robot
Issue longhorn/longhorn#11037, longhorn/longhorn#11034
Automate longhorn/longhorn#11037
Verified on both v1 and v2 data engine
N/A
=> test(robot): add Test Evict Two Replicas Volume With Backing Image

manager/integration/tests/common.py, manager/integration/tests/test_basic.py, manager/integration/tests/test_ha.py, manager/integration/tests/test_settings.py, manager/integration/tests/test_snapshot.py
=> feat(regression): update test cases because of the consolidation of settings

pipelines/gke/terraform/main.tf
Issue N/A
remove hard-coded gke k8s version
=> ci: remove hard-coded gke k8s version

e2e/keywords/backup.resource, e2e/libs/backup/backup.py, e2e/libs/backup/rest.py, e2e/libs/keywords/backup_keywords.py, e2e/tests/regression/test_backup.robot
Issue https://github.com/longhorn/longhorn/issues/11514
fix failed to backup snapshot: snapshot <nil> is invalid in Test Uninstallation With Backups
=> test(robot): fix failed to backup snapshot: snapshot <nil> is invalid in Test Uninstallation With Backups

pipelines/appco/Jenkinsfile, pipelines/appco/scripts/download-support-bundle.sh, pipelines/appco/scripts/longhorn_helm_chart.sh
Issue https://github.com/rancher/suse-storage/issues/32
ci: airgap helm installation in appco pipeline
=> ci: airgap helm installation in appco pipeline

e2e/keywords/volume.resource, e2e/libs/keywords/system_backup_keywords.py, e2e/libs/system_backup/crd.py, e2e/libs/system_backup/rest.py, e2e/libs/system_backup/system_backup.py, e2e/tests/regression/test_system_backup.robot
Issue longhorn/longhorn#10240
add test case `Test Create System Backup With DR Volume`
=> test(robot): add test case Test Create System Backup With DR Volume

e2e/keywords/setting.resource, e2e/libs/setting/setting.py, e2e/libs/utility/utility.py
Issue https://github.com/longhorn/longhorn/issues/11520
fix failed upgrade test cases caused by incompatible changes in longhorn settings
=> test(robot): fix failed upgrade test cases caused by incompatible changes in longhorn settings

pipelines/utilities/longhornctl.sh, test_framework/scripts/longhorn-setup.sh
Issue https://github.com/longhorn/longhorn/issues/11430
remove unused prerequisite script
=> ci: remove unused prerequisite script

e2e/libs/backup/backup.py, e2e/libs/backup/crd.py, e2e/libs/backup/rest.py, e2e/libs/keywords/backup_keywords.py, e2e/tests/regression/test_backup.robot
Issues:
- longhorn/longhorn#11461
- longhorn/longhorn#11475
Implement a ROBOT test case to cover  https://github.com/longhorn/longhorn/issues/11475.
`None`
`None`
=> test(robot): backup older snapshot when newer snapshot backup exists

e2e/keywords/backupstore.resource, e2e/libs/backupstore/base.py, e2e/libs/keywords/backupstore_keywords.py, e2e/libs/keywords/setting_keywords.py, e2e/libs/setting/setting.py, e2e/tests/negative/pull_backup_from_another_longhorn.robot, e2e/tests/negative/test_dr_volume.robot, e2e/tests/negative/uninstallation_checks.robot, e2e/tests/negative/upgrade_conflict_handle.robot, e2e/tests/prerelease_checks.robot, e2e/tests/regression/test_backup.robot
Issue https://github.com/longhorn/longhorn/issues/10087#issuecomment-3195768071
fix default backup target is not available error
=> test(robot): fix default backup target is not available error

manager/integration/tests/common.py, manager/integration/tests/test_scheduling.py, manager/integration/tests/test_snapshot.py
Issue Longhorn/longhorn#11537
Update test_snapshot.py because of the change of the setting snapshot_data_integrity.
=> feat: update test_snapshot.py

e2e/tests/regression/test_recurringjob.robot
Issue https://github.com/longhorn/longhorn-tests/pull/2712#discussion_r2290032380
test system backup recurring job with both attached and detached volumes
=> test(robot): test system backup recurring job with both attached and detached volumes

e2e/tests/regression/test_v2.robot
Issue https://github.com/longhorn/longhorn/issues/11578 https://github.com/longhorn/longhorn/issues/7015#issuecomment-1884354065
remove the non-deterministic test step in Test V2 Instance Manager Deletion On Volume Attached Node With Inactivated Data Engine test case
=> test: remove the non-deterministic test step in Test V2 Instance Manager Deletion On Volume Attached Node With Inactivated Data Engine test case

e2e/keywords/volume.resource, e2e/libs/keywords/volume_keywords.py, e2e/libs/utility/utility.py, e2e/libs/volume/crd.py, e2e/libs/volume/rest.py, e2e/libs/volume/volume.py, e2e/tests/regression/test_backup.robot
Issue longhorn/longhorn#11581
add test case `Test DR Volume Backup Block Size`
=> test(robot): add test case Test DR Volume Backup Block Size

e2e/keywords/workload.resource, e2e/libs/keywords/workload_keywords.py, e2e/libs/node/node.py, e2e/libs/workload/workload.py
Issue https://github.com/longhorn/longhorn/issues/11646
fix workload pod not found error when checking data checksum
=> test(robot): fix workload pod not found error when checking data checksum

e2e/libs/volume/crd.py
Issue longhorn/longhron#11581
ignore volume backup block size in not support version
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/4048/ 
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/4047/
=> test(robot): ignore volume backup block size in not support version

e2e/requirements.txt
Issue https://github.com/longhorn/longhorn/issues/11645
add robotframework-retryfailed package
=> test(robot): add robotframework-retryfailed package

manager/integration/tests/common.py, manager/integration/tests/test_settings.py
Issue longhorn/longhorn#11665
refine `test_instance_manager_cpu_reservation` for `v2` volume
1. Seprate `guaranteed-instance-manager-cpu` between v1 and v2 data engine
2. Add `wait_for_all_nodes_disks_schedulable` for waiting all disks ready in test, we can not reuse, `reset_disks_for_all_nodes` because it wait disk UUID ready, if a disk already exist(having UUID) but not schedulable, `reset_disks_for_all_nodes` will not help
v1: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/9334/
v2: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/9335/
=> test(pytest): refine test_instance_manager_cpu_reservation for v2 volume

e2e/tests/negative/test_dr_volume.robot
longhorn/longhorn#11768
@chriscchien 
https://github.com/longhorn/longhorn/issues/11767
https://github.com/longhorn/longhorn/issues/11768
PR v1 test result :https://ci.longhorn.io/job/private/job/longhorn-e2e-test/4118/
PR v2 test result :https://ci.longhorn.io/job/private/job/longhorn-e2e-test/4121/
=> test(robot): Add Test DR Volume Incremental Restore After Source Volume Expansion

manager/integration/tests/test_cloning.py
Issue https://github.com/longhorn/longhorn/issues/11329 https://github.com/longhorn/longhorn/issues/7794 https://github.com/longhorn/longhorn/issues/11762 https://github.com/longhorn/longhorn/issues/9760
support basic v2 volume cloning test cases
=> test: support basic v2 volume cloning test cases

manager/integration/tests/test_snapshot.py
Issue longhorn/longhorn#9760
https://github.com/longhorn/longhorn/issues/9760#issuecomment-2677886775
=> test(pytest): extend v2 volume snapshot test coverage

e2e/deploy/test.yaml, e2e/templates/workload/pod.yaml, manager/integration/deploy/backupstores/minio-backupstore.yaml, manager/integration/deploy/test.yaml, pipelines/appco/scripts/longhorn_setup.sh
Issue https://github.com/longhorn/longhorn/issues/11883
fix pulling minio backupstore image error due to dockerhub rate-limit on hal
=> test: fix pulling minio backupstore image error due to dockerhub rate-limit on hal

e2e/libs/backupstore/__init__.py, e2e/libs/backupstore/base.py, e2e/libs/backupstore/cifs.py, e2e/libs/keywords/backupstore_keywords.py, e2e/tests/negative/pull_backup_from_another_longhorn.robot, e2e/tests/regression/test_backup.robot, manager/integration/deploy/backupstores/cifs-backupstore.yaml, pipelines/utilities/install_backupstores.sh, test_framework/terraform/harvester/sles/main.tf
Issue https://github.com/longhorn/longhorn/issues/11883
move cifs backupstore image to ecr and support cifs backupstore for robot test
=> test: move cifs backupstore image to ecr and support cifs backupstore for robot test

e2e/keywords/host.resource, e2e/libs/keywords/host_keywords.py, e2e/tests/regression/test_environment.robot, pipelines/utilities/longhorn_status.sh
Issue https://github.com/longhorn/longhorn/issues/11891
add Test IPv4 Only Environment test case
=> test(robot): add Test IPv4 Only Environment test case

e2e/tests/regression/test_engine_image.robot
Issue https://github.com/longhorn/longhorn/issues/11894
add Test Engine Upgrade With Extra Replicas test case
=> test(robot): add Test Engine Upgrade With Extra Replicas test case
